### ISSUE TITLE
Ex Nihilo Removing sieve recipes does nothing

### ISSUE THREAD

**Issue by Timeslice42** [jaredlll08/ModTweaker2#100]
Removing a sieve recipe from dirt, such as the following, does not actually do anything; the recipe is not removed, and there is no error.

`Sieve.removeRecipe(<minecraft:melon_seeds>);`

*edit* Gravel doesn't work either, however *adding* recipes seems to work fine.

**Comment by Bentenmaru** [comment]
you tried typing mods.exnihilo.Sieve.removeRecipe to remove it? as i have used it to remove a few from sieving dirt

**Comment by Yulife** [comment]
It's a known issue. Seems like it's an issue on @ErasmusCrowley's side.

**Comment by Timeslice42** [comment]
Dangit, I was afraid of that. I'll try reporting it to Insaneau.

**Comment by MikeLydeamore** [comment]
I've addressed this in Ex Nihilo, however, some changes will be needed in ModTweaker to ensure this works.

See https://bitbucket.org/MikeLydeamore/ex-nihilo/commits/f2adf22f1cba71620462f7b7231a843e0a4c19ef for explicit details.
I have added brand new unregister recipes for most cases. If I've missed some let me know.

**Comment by Turkey2349** [comment]
This has been fixed!

**Comment by Timeslice42** [comment]
Woot!

**Comment by Yulife** [comment]
Open the issue if the bug still persists :)

**Comment by Timeslice42** [comment]
I can't reopen, but the wiki needs to be updated as the signature has changed and I no longer know how to call the methods.

**Comment by Timeslice42** [comment]
It would also be nice if you exposed unregisterRewardFromAllBlocks and unregisterAllRewardsFromBlock, possibly as removeFromAll(outputstack) and removeAllFrom(inputstack).

**Comment by Timeslice42** [comment]
Actually, I'll just open a new ticket to be sure.
