### ISSUE TITLE
Adding furnace recipe doesn't work

### ISSUE THREAD

**Issue by Timeslice42** [jaredlll08/ModTweaker2#101]
Adding the following furnace recipe doesn't work; removing recipes works fine.

```
# Remove grout -> seared brick
furnace.remove(<TConstruct:materials:2>);
# Add grout -> nether seared brick
furnace.addRecipe(<TConstruct:CraftedSoil:1>, <TConstruct:materials:37>);
```

**Comment by Voidi** [comment]
the support for the vanilla furnace is from Minetweaker itself.
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Furnace

**Comment by Yulife** [comment]
Apart from that you always need to supply the error log.
