### ISSUE TITLE
Updating Mekanism causes crashes with NEI lookup

### ISSUE THREAD

**Issue by ChatFawkes** [jaredlll08/ModTweaker2#102]
I know this mod isn't being officially maintained, but I figured I would report this bug.

When updating to Mekanism v8, looking the recipe or usage for any block or item in NEI crashes the client. I have disabled the scripts that use the Mekanism compat, but even with those disabled it will still crash if I try to look up an recipe or usage.

[Crash Report](https://gist.github.com/ChatFawkes/cb51c2b6690e9c63bce2)
ModTweaker Version: 2-0.7.5

**Comment by Yulife** [comment]
@jaredlll08 would an update in the lib fix it?

**Comment by erkro1** [comment]
Please fix this asap, it's preventing me from really playing with it. (since you look up a lot of recipes when playing with modpacks)

**Comment by Yulife** [comment]
I am learning code but I am not capable of fixing it right now due to my missing knowledge. Calling people who have done MT like @hilburn.

**Comment by hilburn** [comment]
Ok - I've had a hunt through, pretty sure I know what's going wrong and will submit a PR with a fix this evening/tomorrow when I have a chance to sort it out.

Weird that it still crashes without using the code though

**Comment by erkro1** [comment]
@hilburn That would be great, thanks for looking into it.

**Comment by Yulife** [comment]
Thank you!

**Comment by hilburn** [comment]
Can you guys confirm that this works? https://dl.dropboxusercontent.com/u/41428129/Mods/ModTweaker%202-0.7.5.jar

I don't have time to thoroughly test it at the moment so let me know

**Comment by Manuepolis23** [comment]
it works for me

**Comment by erkro1** [comment]
Fixed it for me too, thank you very much for this!

**Comment by thephoenixlodge** [comment]
Awesome, next step would be to get the integration upgraded too. But this fix does seem to be working.

**Comment by hilburn** [comment]
Great - there are still a few things i need to tweak (remove methods) but i'll push it soon

**Comment by Yulife** [comment]
:thumbsup:

**Comment by Bunsan** [comment]
This patch seems to have fixed an error that was being thrown for the Mek infuser with Mek v8. Cheers.

**Comment by jaredlll08** [comment]
Is it crashing only after you reload the scripts? or even on first load?

**Comment by skaviouz** [comment]
reloading causes a crash on nei lookup. first load appears to work and function with no problems.

**Comment by Zixxl** [comment]
Fixed in ModTweaker2 0.9.0. Please update!
