### ISSUE TITLE
Cant remove forestry recipes properly

### ISSUE THREAD

**Issue by JasonMcRay** [jaredlll08/ModTweaker2#103]
When i try to remove for example all carpenter recipes for humus (there are 2 recipes - one regular and one from crated humus) with `mods.forestry.Carpenter.removeRecipe(<Forestry:soil>)` it will remove only one recipe at random. Whenever I reload the scripts, it will return the removed recipe and will remove the second one.

**Comment by JasonMcRay** [comment]
Found a workaround: I need to have 2times the same line to remove both recipes.

**Comment by Dream-Master** [comment]
remove it twice if you have two recipes.

mods.forestry.Carpenter.removeRecipe(<Forestry:soil>);
mods.forestry.Carpenter.removeRecipe(<Forestry:soil>);

**Comment by Dream-Master** [comment]
@JasonMcRay 
I see you make Gt Recipes for your pack too. I make addon mod for minetweaker adding fluid support and missing gt 5 machnines. http://forum.industrial-craft.net/index.php?page=Thread&threadID=11353

**Comment by Yulife** [comment]
Nette Werbung @Dream-Master ;) @JasonMcRay a new build was just built, please test it with that. Otherwise @Voidi shall take a look at it.

**Comment by Dream-Master** [comment]
@Yulife Kann es auch löschen wenn es euch stört. 
Wäre übrigens sehr schön wenn eure aktuellen Builds verfügbar währen auch ohne Passwort.

**Comment by Yulife** [comment]
Ne ne, ist ok :) Ist ja im Endeffekt zur Hilfe der Anderen.
Jared muss das machen. @jaredlll08 open up the Modtweaker2 jenkins!

**Comment by Dream-Master** [comment]
@Yulife 
Danke

**Comment by Yulife** [comment]
Kein Problem. Außerdem gute Arbeit bei dem GT6 addon :+1: !!

**Comment by Dream-Master** [comment]
@Yulife Danke. Bin noch am Anfang mit meinen Java Kenntnissen. Werden aber immer mehr ;-)

**Comment by jaredlll08** [comment]
From now on, whenever I see german or any other language besides english, I am automatically closing the issue...

**Comment by Dream-Master** [comment]
;-(

**Comment by Yulife** [comment]
Jared you nazi. If @Dream-Master is more comfortable in German and I speak it too, he is allowed to use it. @Dream-Master Try to put a translation into English under your German text though.

**Comment by Dream-Master** [comment]
;-)

**Comment by jaredlll08** [comment]
Wow call the jew a nazi... GG, the probldm is, i have no idea what you guys
are talking about... So yea...

**Comment by Yulife** [comment]
I am congratulating him for successing a Minetweaker addon. lol

**Comment by jaredlll08** [comment]
Fixed in #153
