### ISSUE TITLE
Client crashes on recipe lookups

### ISSUE THREAD

**Issue by SirWilli** [jaredlll08/ModTweaker2#105]
hey,
there is currently an issue which crashes the client if you do the following:
1. load a world
2. lookup a recipe
3. unload the world (go in to the main menu)
4. load the world again
5. look up a recipe again

The issue happened with inscriber and mekanism recipes:
Mekanism crash:
http://pastebin.com/svWMyEsk
AppliedEnergistics crash:
http://pastebin.com/DY9f9nPd

Versions:
ModTweaker 2-0.7.5
appliedenergistics2-rv2-beta-14
Mekanism-1.7.10-7.1.2.185
NotEnoughItems-1.7.10-1.0.4.90-universal

**Comment by thephoenixlodge** [comment]
It's a known issue with scripts being reloaded. Basically these recipe handlers get cached on launched (or the AE2 one does at least) and don't appreciate the contents of these handlers being changed at runtime. The only way this could really be fixed on Mod Tweaker's end would be to blacklist them from being reloaded somehow, but you'll need to convince someone to put in a pull request to do this.

**Comment by jaredlll08** [comment]
Invalid issue, we can do nothing about recipe caching
