### ISSUE TITLE
Thermal Expansion.

### ISSUE THREAD

**Issue by wujekbrezniew** [jaredlll08/ModTweaker2#106]
Hi,
On version 0.7.5 I can't add/delete any recipes from TE machines.

For example:
I copy this script (mods.thermalexpansion.Furnace.removeRecipe(<minecraft:potato>) and the Potato still exists in RedFurnace recipes.

**Comment by jaredlll08** [comment]
In the TE config there is an option that allows you to modify recipes, and I know it works...
