### ISSUE TITLE
Can't remove Blood Orb recipes

### ISSUE THREAD

**Issue by ubermentat** [jaredlll08/ModTweaker2#107]
Using version 0.7.5, I can't remove shaped/shapeless blood orb recipes. I can add them just find, but `mods.bloodmagic.BloodOrb.removeShaped(<AWWayofTime:sigilOfTheFastMiner>);` returns this error:
```
ERROR: vanillaTools.zs:41 > No such static member in mods.bloodmagic.BloodOrb: removeShaped
ERROR: Error executing vanillaTools.zs: minetweaker/api/item/IItemStackAny
```

**Comment by Yulife** [comment]
Just use the normal recipe removal.

**Comment by ubermentat** [comment]
That works perfectly. The wiki page should probably be updated/reworded to reflect this, as it currently states that each handler can have recipes added or removed.
