### ISSUE TITLE
[Suggestion] More defined recipe removal for Squeezer

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#11]
Same as the Fermenter, the recipe removal is rather unprecise at it uses the OuputFluid.
The same suggestion would go for the Fermenter, however only this would be sufficient for recipe removal in the Squeezer:
InputStack

**Comment by Yulife** [comment]
InputStack indeed.

**Comment by jaredlll08** [comment]
not possible as the squezzer uses an array

**Comment by Yulife** [comment]
Then InputArray! :'D

**Comment by jaredlll08** [comment]
not possible, sorry
