### ISSUE TITLE
Inscriber do not work with Mine/ModTweaker 

### ISSUE THREAD

**Issue by Leksandrua** [jaredlll08/ModTweaker2#110]
Please, update AE2 inscriber API if it is possible

**Comment by Yulife** [comment]
Invalid report.
Does it throw an error?
Does it crash?
How does it "not work"?

**Comment by Leksandrua** [comment]
Ok, first of all, when I released my FTB pack with modtweaker scripts, I realized crashes when I looked some recipes, futher more, I learn that without any scripts which are related to AE2 inscriber, the pack do not crash again at any circumstance at all

Crash : http://pastebin.com/fdpGxiXw

I posted report on AE2 githud: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1211 (there is more additional info, if you need it)

I try update AE2, ModTweaker2 and MineTweaker to latest version, and scripts witch were working priviously, stop working

Console said me: [Client thread/INFO]: [CHAT] ERROR: Error executing Recipes - BuildCraft AssemblyTable.zs: appeng/recipes/handlers/Inscribe$InscriberRecipe

**Comment by jaredlll08** [comment]
Fixed in one of the latest commits :)

**Comment by JAWSAWN** [comment]
Is this fixed now? Or when will it be released?

**Comment by Yulife** [comment]
Well, if @jaredlll08 would commit. *gives evil look at @jaredlll08*

**Comment by jaredlll08** [comment]
It is commited...

**Comment by Yulife** [comment]
Then release a fix! :wink:
