### ISSUE TITLE
[Suggestion] Being able to remove Blood Magic blood orb recipes

### ISSUE THREAD

**Issue by TennePG** [jaredlll08/ModTweaker2#114]
I was working on a modpack, and with the idea that I had, it would require me to remove the Blood Rune recipes. I haven't really found a way to do it, so I'm assuming that the feature for orb recipe removal wasn't added. Would it be possible to add it?

**Comment by joshiejack** [comment]
use the normal recipes.remove

also blood magic integration is in blood magic itself, not modtweaker

**Comment by TennePG** [comment]
Ah, okay. My bad >_>
