### ISSUE TITLE
Failure to Remove Railcraft Coke Oven Recipes

### ISSUE THREAD

**Issue by dexman545** [jaredlll08/ModTweaker2#117]
It appears to be impossible to remove the coke oven recipe for charcoal. 
Using: mods.railcraft.CokeOven.removeRecipe(<minecraft:coal:1>);  on version 0.8.0

**Comment by Timeslice42** [comment]
Railcraft has a tendancy to get "clever" and insure that it (thinks) it is always possible to make charcoal and steel. If it thinks that that is no longer possible it will add recipes in.

**Comment by jaredlll08** [comment]
What @Timeslice42 said. thanks would have spent days on this one xD

**Comment by CovertJaguar** [comment]
As far as I'm aware there shouldn't be anything "clever" going on.

**Comment by jaredlll08** [comment]
Ok so, first off, @CovertJaguar, I am sorry about everything I said on
twitter, it was a result of no sleep and stress(exams). Secondly, Is this
only broken for charcoal, or anyother stuff, since I checked RC source, and
as CJ says, all looks normal.

**Comment by jaredlll08** [comment]
Yea I have no idea on this one...

**Comment by CovertJaguar** [comment]
```
ICokeOvenRecipe recipe = RailcraftCraftingManager.cokeOven.getRecipe(new ItemStack(Item.coal, 1, 1));
RailcraftCraftingManager.cokeOven.getRecipes().remove(recipe);
```

**Comment by Tsyklop** [comment]
how fix this?

**Comment by Tsyklop** [comment]
Please fix this

**Comment by Yulife** [comment]
What the hell? You think spamming will fast forward the fixing of this issue? Be patient! :angry:

**Comment by Tsyklop** [comment]
@Yulife 8 more days to wait? On the problem of written 8 days ago and still no action and solutions ..

**Comment by jaredlll08** [comment]
Everytime this gets bumped, I take a day off modtweaker.

**Comment by Yulife** [comment]
@Tsyklop sometimes code takes long. In the 8 days you could've stopped complaining and learned to write Java to make a pull request that fixes it.

**Comment by Tsyklop** [comment]
@Yulife On this issue, I learned only yesterday ...
And I'm not rushing anyone. Just doing the assembly and it is a little delay its development ... I'm waiting for a fix in general.

**Comment by jaredlll08** [comment]
"also I'm not rushing anyone" you asked us to fix it twice, less than a day apart, you made an issue on the railcraft github, even though they shouldn't really care about this(since it is all our side). but yea, you aren't rushing anyone... /sarcasm

**Comment by Tsyklop** [comment]
@jaredlll08 Written back because I thought that there may be fixed a in the Railcraft.Most will not do and nowhere to write .. I'm sorry for all this.
