### ISSUE TITLE
Crash Report - 0.8.0 - java.lang.NoClassDefFoundError: appeng/api/features/IInscriberRecipe

### ISSUE THREAD

**Issue by Razorskills** [jaredlll08/ModTweaker2#118]
Here is a link to a crash report:

https://www.dropbox.com/s/4tzyy7h9o5urlwm/crash-2015-04-19_16.26.53-client.txt?dl=0

I guess something is up with Applied Energistics..
I will do some more testing though.

Reverting back to 0.7.5 solves any crashing.

**Comment by joshiejack** [comment]
Update AE2.

**Comment by Razorskills** [comment]
Oh new version isn't compatible with stable release. Il update to rv2 once it hits stable. If that is all it is, then might aswell close this? although you will probably have some other reports.

**Comment by Yulife** [comment]
Open the issue if the bug still persists :)
