### ISSUE TITLE
[Bug] Still multiplies mB amount by 100

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#12]
I just noticed this - for some reason the Still does not use exact numbers.
An example:
mods.forestry.Still.addRecipe(100, <liquid:juice> * 10, <liquid:bioethanol> * 2); 
"* 10" will use 1000mB of Fruit Juice, "* 2" will output 200mB of Ethanol.
I know this is Forestry's behaviour but could you make it so that it accepts more precise values?

**Comment by jaredlll08** [comment]
Fixed, does it happen with any other machines?

**Comment by Yulife** [comment]
Not that I noticed, lol. I will test Thermionic Fabricator and Centrifuge once you give me the compiled version :wink:

**Comment by Yulife** [comment]
Doesn't seem to work. Mhm.
