### ISSUE TITLE
[Question/Bug] "No enum constant appeng.api.features.Inscriber.ProcessType.false" error?

### ISSUE THREAD

**Issue by JAWSAWN** [jaredlll08/ModTweaker2#121]
Using the latest AE2 beta and Modtweaker. The ae2 support was broken. Have it updated yet? If it updated is there new type of script code? Old one doesn't seem to work. Also where can I see the TerraFirmaCraft support? Wiki doesn't contain that.

The code I'm having problem with:

var disc = <Quadrum:disc>;
var pan = <TConstruct:metalPattern:10>;
var note = <minecraft:noteblock>;
var plastic = <VeganOption:bioplastic>;

//inscriber
mods.appeng.Inscriber.addRecipe([plastic], pan, null, disc, false);
mods.appeng.Inscriber.addRecipe([disc], <Botania:cosmetic:11>, note, <minecraft:record_cat>, true);
mods.appeng.Inscriber.addRecipe([disc], <minecraft:leather_boots>, note, <BiomesOPlenty:record_wanderer>, true);

**Comment by Yulife** [comment]
Documentation takes a long time to test everything out, etc.
@jaredlll08 should have fixed it. Are you on 0.8?

**Comment by jaredlll08** [comment]
I had to change the method
mods.appeng.Inscriber.addRecipe(ItemStack[] imprintable, ItemStack plateA, ItemStack plateB, ItemStack out, String type)

type can be either:
Inscribe
Press

**Comment by JAWSAWN** [comment]
I didn't get what you said by "mods.appeng.Inscriber.addRecipe(ItemStack[] imprintable, ItemStack plateA, ItemStack plateB, ItemStack out, String type)" 

Can you make two example ones? Do I have to put a number to item stack or leaving it empty would do?

**Comment by JAWSAWN** [comment]
like simplified versions with gold,iron iron block, gold block? also where does null go?
I tried this:
mods.appeng.Inscriber.addRecipe([] <minecraft:gold_ingot> , <minecraft:iron_ingot>, <minecraft:gold_block>, <minecraft:iron_block>, Inscribe);

did not work. Any help?
