### ISSUE TITLE
Ex Nihilo Sieve Recipes

### ISSUE THREAD

**Issue by Timeslice42** [jaredlll08/ModTweaker2#122]
It would be nice if you exposed unregisterRewardFromAllBlocks and unregisterAllRewardsFromBlock, possibly as removeFromAll(outputstack) and removeAllFrom(inputstack). And please update the wiki to reflect the new method signatures :)

Also reloading isn't quite working. Any removed sieve recipes get stuck when reloading.

**Comment by drz2k** [comment]
Second this, also heat sources dont seem to register as well.

**Comment by Yulife** [comment]
Check the latest build please!
