### ISSUE TITLE
[Issue/Help] AE2 Support

### ISSUE THREAD

**Issue by JAWSAWN** [jaredlll08/ModTweaker2#123]
mods.appeng.Inscriber.addRecipe([] minecraft:gold_ingot , minecraft:iron_ingot, minecraft:gold_block, minecraft:iron_block, Inscribe)

Why this is not working on the recent version? What am I doing wrong? Sorry but you didn't replied to old issue. So I couln't fix it. Little bit more help with the new inscriber method? Maybe put some examples? I really need it. Keep the good work!

**Comment by jaredlll08** [comment]
this may help
https://github.com/jaredlll08/ModTweaker2/issues/121

**Comment by JAWSAWN** [comment]
I know! Thats why I made another issue! That didn't work! Can you give some examples? You didn't replied to that issue.

**Comment by jaredlll08** [comment]
http://www.blamejared.com/GetFluxed/content/2015-04-25_01-35-15.txt
here

**Comment by JAWSAWN** [comment]
Oh derpy me, didn't include the " "
Thanks alot!

**Comment by Yulife** [comment]
Well that's new @jaredlll08. What does each string do?

**Comment by JAWSAWN** [comment]
Its just the same as old one. Instead of true or false,  it have "Inscribe" and "Press" with the quotations. Trust me, #121 did not help any.
