### ISSUE TITLE
appeng/api/features/IInscriberRecipe at startup

### ISSUE THREAD

**Issue by drago87** [jaredlll08/ModTweaker2#124]
After i did a update of forge (to forge-1.7.10-10.13.3.1391-1710ls) an some of my outher mods i got a "mekanism.common.recipe.machines.BasicMachineRecipe" and they told my at the makanism issu traker that it was a modtweaker error so i uppdated the mod and whith the ModTweaker 2-0.8.0 and ModTweaker 2-0.8.1 i get "appeng/api/features/IInscriberRecipe" when i start minecraft. If i use the 0.7.5 version i get the mekanism error (when i try to look up a recipe in NEI).

OpenEye: http://openeye.openmods.info/crashes/bb486b827a78b3c724b44727b5a95837
Error report: http://pastebin.com/eAZFnaAm

**Comment by jaredlll08** [comment]
You need to use the LATEST AE2
