### ISSUE TITLE
Thaumcraft Recipes change or add don't work with 0.8.1

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#127]
Every of my Thaumcraft Recipes (new added or modified Recipes in the Crucible, Infusion ore Arcane) don't work with Modtweaker 0.81. They not be loaded at all (don't be shown in the minetweaker.log)looks like they not exist.
With Version 0.8.0 everything woks fine.
I try to decompile the newest code on git (0.8.2) and let you know if it works.

**Comment by Dream-Master** [comment]
No the newest code i compile don't show any Thaumcraft Recipes i made. What you changing between 0.8 and 0.8.1. Did you change some commands so that i have to edit my scripts?

**Comment by jaredlll08** [comment]
I did not change anything related to thaumcraft, besides adding loot bags.

**Comment by Dream-Master** [comment]
In 0.8 my scripts loading in 0.8.1 not. I looking in your commits and see a lot of changes.
Did you check if some Thaumcraft stuff is loading correctly because i dind't see any recipes loaded in the Minetweaker.log

**Comment by jaredlll08** [comment]
Like I said, I have only done loot bags, and that I backported from the rewrite, currently, until proven otherwise, this is user error

**Comment by Dream-Master** [comment]
but how my scripts be loaded in my modpack with Modtweaker 0.8 and dont loaded with Modtweaker 0.81. I dont change a single line in my script or a changing a mod or a config. I uploading later my minetweaker logs that you can see.

**Comment by jaredlll08** [comment]
I do not know, but the last thaumcraft thing was 4 days ago, which was loot bags, and IIRC it is not released, before that it is 2 months ago, so yea...

**Comment by Dream-Master** [comment]
So here the log files. With 0.8 the log files is 240 kb big with 0.81 the files has only a size of 207 kb.
I compare the two logs and see that they not loading any Thaumcraft Recipes.

Mod Tweaker 0.8 log
https://gist.github.com/Dream-Master/af0c88a2550f192bb86d#file-gistfile1-txt

Mod tweaker 0.8.1 log
https://gist.github.com/Dream-Master/0c2211b4ba6ac1eb795f#file-gistfile1-txt

The only thing in my Pack i change is the Mod tweaker Version.

**Comment by jaredlll08** [comment]
I do not know, but NOTHING has changed, AT ALL

**Comment by Dream-Master** [comment]
I said I change  only your file. With 0.8 ok with 0.8.1 not. How I can test things more or better? And the funny thing is it is only Thaumcraft. Rail craft works fine and forestry too. ???

**Comment by jaredlll08** [comment]
I HAVE CHANGED NO THAUMCRAFT THAT WILL EFFECT THIS! NO THAUMCRAFT HAS
CHANGED BESIDES FOR LOOT BAGS AND THAT WAS BACKPORTED FROM THE
REWRITE(which was working)

**Comment by Dream-Master** [comment]
If I have time in the evening I check the code on hit and maybe I find out what happened.

**Comment by Dream-Master** [comment]
Now with the last code i compiled it works fine NICE. I see you changing something in the  code.
I just start to lern java and want to understand why Thaumcraft not loaded before. What you change ?

Thank for your help.

**Comment by Yulife** [comment]
:thumbsup:

**Comment by Dream-Master** [comment]
I have to reopen the issue. Only when i entering the game it works just fine (all recipes are shown right) but when i using "/mt reload" most of the Thaumcraft Stuff I change disappears. So i think it is only partial fixed. Sorry

**Comment by jaredlll08** [comment]
Thaumcraft stuff can not be reloaded, end of story, blame azanor

**Comment by jaredlll08** [comment]
(Din't actually blame him, it isn't his fault his stuff can't be edited
during runtime)

**Comment by Dream-Master** [comment]
But in 0.8 i can. So i using this version and hope that you not implement any important features i need ;-). Why mod Authors do this. I dont understand. I adding already Thaumcraft stuff with my mod because of recipes changes (you remember the problem with non removable wands ;-). ) Changing Recipes isn't every Mod Authors thing maybe thats why. This will not stop me from making a perfect hard balaced Modpack ;-) Thanks for you help.

**Comment by Yulife** [comment]
Do you have like an addiction to triple dots jared? Don't be that guy who always puts triple dots.

**Comment by jaredlll08** [comment]
...

**Comment by Dream-Master** [comment]
;-)

**Comment by Kehaan** [comment]
Having same issue as Dream-Master. Rerolling to 0.8 works, but 0.8.2 dont.

**Comment by Sunconure11** [comment]
Did anyone find a work around for this issue? I'm trying to add aspects and warp to some items, but, I too cannot add this stuff.

**Comment by jaredlll08** [comment]
Fixed in github, not released yet

**Comment by Yulife** [comment]
There we go, Jared. :clap:

**Comment by Kehaan** [comment]
Thanks jared <3

**Comment by jaredlll08** [comment]
I wrongfully mentioned this, sorry.
