### ISSUE TITLE
Metallurgy 4: adding/removing recipes to Alloyer causes crash

### ISSUE THREAD

**Issue by PitchBright** [jaredlll08/ModTweaker2#129]
Sample recipes added in script:

mods.metallurgy.Alloyer.addRecipe(<Metallurgy:base.dust:0>, <Metallurgy:vanilla.dust:0>, <Metallurgy:orichalcum.ingot> * 2);

mods.metallurgy.Alloyer.removeRecipe(<Metallurgy:steel.ingot>);

Crash report: http://pastebin.com/2iK5UGN1

**Comment by jaredlll08** [comment]
When does the crash happen? on reload? when looking things up in nei?

**Comment by PitchBright** [comment]
When pressing "R" to see a recipe of an item (any item) in NEI.

**Comment by jaredlll08** [comment]
is this after a /mt reload? or /minetweaker reload?

**Comment by jaredlll08** [comment]
Yea... metallurgy must cache their recipes.

**Comment by PitchBright** [comment]
Does that mean there is no solution? Or should I be doing something differently?

**Comment by jaredlll08** [comment]
Well just don't use /mt reload, I am working with stan to make it that some scripts can't be reloaded.

**Comment by PitchBright** [comment]
Oh, so it works fine if the server boots with the script… but once it gets reloaded with the "/mt reload" command, it borks out?

Also, does that apply to "/minetweaker reload" command (I'm assuming it does).

**Comment by jaredlll08** [comment]
NEVER DO /mt reload or anything of the like
