### ISSUE TITLE
Thermal Expansion Pulverizer changes not working

### ISSUE THREAD

**Issue by chrisk123999** [jaredlll08/ModTweaker2#132]
Using the latest versions of Thermal Expansion, Minetweaker, and ModTweaker; Making changes to pulverizers is silently failing.

Edit: Rolling it back one version fixes it. ModTweaker 2-0.8.1.jar doesn't work, while ModTweaker 2-0.8.0.jar does.

**Comment by Yulife** [comment]
Like I said, you need to be more detailed. Post your Minetweaker log.

**Comment by chrisk123999** [comment]
http://pastebin.com/WR98TfgX

Here's the log.  As far as I can tell there isn't anything getting reported.  It simply doesn't work.

**Comment by Yulife** [comment]
Remember, the log and the script is always needed in a report. You are missing the latter.

**Comment by chrisk123999** [comment]
http://pastebin.com/VzS8eXtS

**Comment by DerOli82** [comment]
I've a similar problem. Pulverizer & Induction Smelter changes doesn't work and i get "x modifications were stuck" messages on /mt reload.

Forge: 10.13.3.1391
MineTweaker: 3.0.9C
ModTweaker2: 0.8.0 and 0.8.1
CoFHCore: 3.0.2-262
ThermalExpansion: 4.0.1-182
ThermalFoundation: 1.0.0-81
Script: https://github.com/combak/ShatteredWorld/blob/master/scripts/ThermalExpansion.zs

**Comment by jaredlll08** [comment]
https://github.com/jaredlll08/ModTweaker2/commit/31a18e8e8f923bb6951a3f71c7044d29e82ec243 fixed this
