### ISSUE TITLE
SF2.4 removeRecipe not working

### ISSUE THREAD

**Issue by wormmus** [jaredlll08/ModTweaker2#134]
Pack: Sky Factory 2.4
Ex Nihilo 1.38-36

Previously, Sky Factory 2.3 had Ex Nihilo 1.38-19, and the function worked correctly to remove Sieve drops, but with 1.38-36, it is not working correctly. 

Error recieved:
ERROR: ModTweaker.zs:5 > a method is available but none matches the parameters (minetweaker.item.IItemStack)

I did update ModTweaker to 0.8.1, with no change.
I also tried to downgrade to Ex Nihilo 1.38-19, but the pack doesn't load.

Script Line:
mods.exnihilo.Sieve.removeRecipe(<exnihilo:exnihilo.iron_broken>);

Just a note, Sky Factory 2.4 did just release, and one of the devs of the pack is saying ModTweaker broken; is this an easy fix?

**Comment by jaredlll08** [comment]
This is a user error, the sieve needs an input and an output.

**Comment by wormmus** [comment]
So the correct line should be...

mods.exnihilo.Sieve.removeRecipe(<minecraft:gravel>, [exnihilo.iron_broken]);

I am guessing?  I don't know why you would close a topic without giving a solution to it first.

**Comment by jaredlll08** [comment]
uh I have a tendency to do that :P
it would be
mods.exnihilo.Sieve.removeRecipe(minecraft:gravel, exnihilo:exnihilo.iron_broken);

**Comment by wormmus** [comment]
Thank you, Jared!  I had been trying all day, glad you solved it for me!  By the way...gotta have the <> around the item.  Thanks much!

**Comment by wormmus** [comment]
I just thought I would add a comment for you.
It seems that when an item is removed from the sieve drops, the script loads fine the first run, but after that, it throws an Error Null flag when the script is run a second time.  If anything is added to the script after it throws the null, it won't take effect.  The only option is to restart the game entirely and run the script on launch.  No big deal, just a heads up for you.

**Comment by jaredlll08** [comment]
I want to say 'known bug' but that is actually a feature, Ex nihilo is NOT
ment to be reloaded

**Comment by wormmus** [comment]
Okay.  No worries.  I just got rid of the ore chunks that drop and changed it to just the dust that drops ore, and the gravel drops the other goodies like Lapis and Glowstone.  Sand drops seeds.  I just got tired of dealing with all the different ore chunk types.
