### ISSUE TITLE
Latest AE2 issues

### ISSUE THREAD

**Issue by Carbon-Ghost** [jaredlll08/ModTweaker2#137]
I think you will need to update modtweaker, as before you used a hack to access AE2 inscribers, like Algo. said, but now there is compatibility, but you need to update as using inscribers related recipes outputs Script.zs null reloaded RECIPE.

**Comment by jaredlll08** [comment]
already done. the script usage changed, it should be updated on the wiki. @Yulife

**Comment by Carbon-Ghost** [comment]
Did modtweaker got an update ?

**Comment by jaredlll08** [comment]
yes, this is in 0.8.1

**Comment by Carbon-Ghost** [comment]
Thx :D

**Comment by Yulife** [comment]
@jaredlll08 What's up? What needs to be changed? :)
