### ISSUE TITLE
Infuser bug with Mekanism 7.x + Modtweaker latest

### ISSUE THREAD

**Issue by Carbon-Ghost** [jaredlll08/ModTweaker2#138]
Why does my script output "no such member infuser, even though everything is correct in my script" :C

**Comment by Carbon-Ghost** [comment]
Wait, I think the whole infusion system is broken with the latest ModTweaker, latest mekanism or not, sames goes for Thaumcraft integration...

**Comment by thephoenixlodge** [comment]
It's not broken, It's completely commented out. Stick with Mek 7 and Modtweaker 0.7.4 until jared gets around to updating that handler (if he ever does)

**Comment by jaredlll08** [comment]
Sorry I have school and other mods! #jsonableThaumcraftWandCapsAndWands

**Comment by Carbon-Ghost** [comment]
Will you still fix it xD ? Anyway, ok, but then I have another problem, this version of modtweaker is not compatible with AE2 :/

**Comment by Yulife** [comment]
Why report this in this issue? Make a **DETAILED** new one.

**Comment by Carbon-Ghost** [comment]
Well it's already fixed in the NEWEST VERSION, but in the NEWEST VERSION, mekanism infusion is broken, so is TC integration, so I need to revert to the old one, which has it's compat BROKEN WITH THE NEW AE2 ;P xD

**Comment by joshiejack** [comment]
ModTweaker can't be compatible with every single version of a mod. If you wish to make a complaint. Go direct it at the mod authors for not including MineTweaker3 support themselves.

**Comment by Carbon-Ghost** [comment]
I am going to test latest modtweaker with mekanism 8, if I stayed with 7 it's because I had issues before, but if everything works, I close the issues, else it means that the whole infusion system is broken.

**Comment by Yulife** [comment]
Mek 7 support has been dropped, move onto V8 :)

**Comment by Carbon-Ghost** [comment]
Yes I know, but 8 support is broken atm, jared told me he is fixing atm ;)

**Comment by Yulife** [comment]
Uhhh I think Zixxl fixed it. lol

**Comment by Carbon-Ghost** [comment]
Is there a new version then :D ?

**Comment by Yulife** [comment]
Not sure, wait for ita haha

**Comment by Carbon-Ghost** [comment]
;c *Day 35, still waiting, the slight hope of Modtweaker compat updating I had disappeared again, it's getting tough out here, not sure if I will make it...* My modpack will never see the light at this rate ;(

**Comment by jaredlll08** [comment]
I am sorry, some people actually have lives to live, we are doing the best we can with the huge mess that modtweaker was left in, so you WILL wait and you WILL keep your mouth shut about how long we take, if we released right now, which we really CAN do, we would get spammed with bug reports because we made a big change recently.

**Comment by Carbon-Ghost** [comment]
I know, Jared, I was joking here, I didn't wanted to anger you, sorry xD

**Comment by Zixxl** [comment]
Fixed in ModTweaker2 0.9.0. Please update! (Also update to Mekanism v8)

**Comment by Carbon-Ghost** [comment]
Nice ^^ Also again, sorry if you took that as an annoying reminder, I tried to re-use an old HL3 joke, sorry :/

**Comment by Yulife** [comment]
Don't worry, Jared's patience is just under average :P
