### ISSUE TITLE
Thaumictinkerer Ichorcloth arcane removal fails

### ISSUE THREAD

**Issue by Mrbysco** [jaredlll08/ModTweaker2#139]
I tried removing ichorcloth temporarily.
I tried: "mods.thaumcraft.Arcane.removeRecipe(<ThaumicTinkerer:ichorclothHelm>);"
and it gave me: "ERROR: Error executing Thaumcraft.zs: null"

**Comment by Carbon-Ghost** [comment]
Thaumcraft integration is broken atm, from what I understand.

**Comment by jaredlll08** [comment]
I need more information on this, it never just gives that one line of code, check the minetweaker log, it will give a stacktrace.

**Comment by jaredlll08** [comment]
Fixed by @Zixxl
