### ISSUE TITLE
Tinkers Recipes (Basin and Table) can't be removed with Galacticraft > 3.0.11.334 in a Pack

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#141]
Since Version 3.0.12.335 something is change in Galacticraft that I can't reload the Tinkers Construct Recipes (Basin and Table ) anymore.(Version 3.0.11.334 works fine) The first load of the scripts works fine but when i reload the scripts (/mt reload) Basin and Table recipes (remove code ) from tinkers give me out this Error in the Minetweaker.log

Minetweaker log:

https://gist.github.com/Dream-Master/50470b02f3667228a70a#file-gistfile1-txt

Tinkers Script:

https://gist.github.com/Dream-Master/01769c1b4c96509c91dc

**Comment by jaredlll08** [comment]
Some mods can not be reloaded, At all

**Comment by Dream-Master** [comment]
I thought Modtweaker is for tweaking and testing the scripts with the reload Code but when i have to restart all time my Game this isn't fun.
If I find a way to make it reloadable can I make a pull Request and you ar willing to add this code?

**Comment by jaredlll08** [comment]
NO! the problem not with modtweaker! it is with the actual mods! For once, can you just fucking listen to me when I say, NO!

**Comment by Dream-Master** [comment]
@jaredlll08 
radfast from Galacticraft said.

``````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

It's not a Galacticraft bug.

The only possible change we made which can be related to this is that Galacticraft Tin, Copper and Aluminium Blocks are now included in the OreDictionary so are oredict-compatible with Tinker's Construct - I guess these blocks can probably be made in the Casting Basin now when they could not before.

Maybe that affects your scripts, or maybe there's a bug in MineTweaker, I really don't know but it's not a Galacticraft bug.

``````````````````````````````````````````````````````````````````````````````````````````````````````````````
