### ISSUE TITLE
Ex Nihilo Error in removeRecipe Sieve

### ISSUE THREAD

**Issue by BoavaNet** [jaredlll08/ModTweaker2#143]
Added this " mods.exnihilo.Sieve.removeRecipe(<minecraft:dye:4>); "

And got this

a method available but none matches the parameters (minetweaker.item.IItemStack)

Forge 10.13.3.1408
Mod Used
https://github.com/BoavaNet/WoA-MineCraft-Mod-Pack

**Comment by Timeslice42** [comment]
No one has bothered to update the wiki yet. The format is like this:
    Sieve.removeRecipe(InputStack, OutputStack);
So specify what you're removing *from* first, then what you're removing.

**Comment by BoavaNet** [comment]
Thx For that

**Comment by jaredlll08** [comment]
ok seems to be fixed.
