### ISSUE TITLE
Tinkers script works fine the first time, then crashes on reload.

### ISSUE THREAD

**Issue by tgstyle** [jaredlll08/ModTweaker2#144]
Script
https://gist.github.com/tgstyle/0497bd8aa8d67c36bacd

Crash
https://gist.github.com/tgstyle/c5cf6e37bbcd6c1d769b

**Comment by Dream-Master** [comment]
Use Modtweaker 0.8

**Comment by tgstyle** [comment]
0.8 does the same thing.

**Comment by tgstyle** [comment]
Please re-open.

**Comment by Dream-Master** [comment]
You dont say what mods you are using.
Mod List please.
Galacticraft >334 can throw out this error too (because of ordicted things)

**Comment by Dream-Master** [comment]
Some time Recipes in Thinkers changing when you add or delete a mod. If there is a Basin or Table Recipes that not exists any more the game will crash too.

**Comment by tgstyle** [comment]
This is a complete mod list. Galacticraft is among them, is there any solution? No mods have been added or removed.

https://gist.github.com/tgstyle/0364fa50aa555e6e9247

**Comment by tgstyle** [comment]
Tried the lastest GC 339 and still has the same error.

**Comment by Dream-Master** [comment]
The error is in row 12 so something with the table recipes that you remove are wrong.
What did you change (configs, scripts mods) because before it works?
Try to disable some recipes and enable line by line. I know this is a long and difficult Job but when i got an error i do the same.
I recommend you using Modtweaker 0.8

(Sorry i mean <334)

**Comment by tgstyle** [comment]
Yes I am trying it with 0.8. I went line by line and it only happens when removing Tinkers own ingots/nuggets from the casting table. Lines 12-16 in the script. Any one of those will cause it to crash.

**Comment by Zixxl** [comment]
This issue should be fixed with #151, haven't encountered any NullPointerException while testing.

**Comment by jaredlll08** [comment]
Judging by what @Zixxl said. it is fixed! thanks @Zixxl
