### ISSUE TITLE
Can't add forestry still recipes

### ISSUE THREAD

**Issue by BBoldt** [jaredlll08/ModTweaker2#146]
This shows up in NEI and stuff but doesn't actually work:

```
// XP & Mob Essence Conversions
mods.forestry.Still.addRecipe(50, <liquid:xpjuice> * 25, <liquid:mobessence> * 83);
mods.forestry.Still.addRecipe(50, <liquid:mobessence> * 83, <liquid:xpjuice> * 25);
```

**Comment by Dream-Master** [comment]
Which version do you use?

**Comment by BBoldt** [comment]
* ModTweaker 2-0.8.1
* forestry_1.7.10-3.5.6.15

**Comment by Dream-Master** [comment]
Can you try it with version 0.8 because many thinks like thaumcraft not working in this version.

**Comment by Voidi** [comment]
and please post the corresponding from minetweaker.log

**Comment by Zixxl** [comment]
Can't reproduce this bug with ModTweaker2-0.8.2 and forestry_1.7.10-3.5.0.471.

**Comment by jaredlll08** [comment]
Usually if it shows up in nei, but doesn't work, it is user error. since nei is simply reading and displaying.  maybe you put the wrong stuff in. also as @Zixxl said, can't reproduce.
