### ISSUE TITLE
[bug] Ex Nihilo Hammer Recipe removal fails, expects rewards method.

### ISSUE THREAD

**Issue by hephinator** [jaredlll08/ModTweaker2#148]
According to ModTweaker2's hammer removeRecipe handler, all that is required is an IItemStack Output, and as such, only a single argument is passed, as shown below.

Script:
mods.exnihilo.Hammer.removeRecipe(<exnihilo:exnihilo.tin_broken>);
mods.exnihilo.Hammer.removeRecipe(<exnihilo:exnihilo.silver_broken>);
mods.exnihilo.Hammer.removeRecipe(<exnihilo:exnihilo.lead_broken>);

But, when a single argument, specifying the output to get removed is passed, you get the following:
[Client thread/INFO]: [CHAT] ERROR: Error executing ExNihilo-Hammer.zs: rewards

ExNihilo 1.38-40
ModTweaker2 0.8.1

I've checked and rechecked to ensure it wasn't a scripting error.
MineTweaker Log:

INFO: Adding command minetweaker
INFO: Adding minetweaker command tooltips
INFO: Adding minetweaker command entities
INFO: Adding minetweaker command materials
INFO: Adding minetweaker command chiselGroups
INFO: Adding minetweaker command chiselVariations
INFO: Adding minetweaker command mfr
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 0 recipes
INFO: Removing ExNihilo Hammer recipe of obtaining exnihilo.tin_broken
ERROR: Error executing ExNihilo-Hammer.zs: rewards
java.lang.NoSuchFieldError: rewards
	at modtweaker2.mods.exnihilo.handlers.Hammer$Remove.apply(Hammer.java:94)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.exnihilo.handlers.Hammer.removeRecipe(Hammer.java:79)
	at ExNihilo-Hammer.__script__(ExNihilo-Hammer.zs:1)
	at __ZenMain__.run(ExNihilo-Hammer.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:555)
	at minetweaker.mc1710.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:166)

**Comment by Dallandra** [comment]
Try 0.8 or earlier, 0.8.1 seems to be massively broken in every regard, yet jaredlll08 hasn't done anything in about a month and said 5 days ago he'd take a "long needed vaction" from the modding community. Expect this to die soon.

**Comment by hephinator** [comment]
0.8.1: No go
0.8.0: No go
0.7.5: No go (in fact, actually makes it worse, since the Sieve breaks too due to less arguments required than passed in 0.8+) :)

I think the issue is that the method for removing items from the Hammer changed on ExNihilo's end.

**Comment by hephinator** [comment]
I've reached out to the current maintainer of ExNihilo (InsaneAU) to perhaps fork the ModTweaker2 repo and fix the issue on Ex Nihilo or ModTweaker's end to ensure compatibility. Guess we will have to see how this shakes out.

**Comment by jaredlll08** [comment]
@Turkey2349

**Comment by Turkey2349** [comment]
I have an idea of why its not working, i can make a quick fix sometime today.

**Comment by Turkey2349** [comment]
@hephinator im good freinds with insaneAU, ill talk to hik my self :)

**Comment by hephinator** [comment]
So about that fix :P

**Comment by Turkey2349** [comment]
He changed things up and there is currently no way for me to add in a removeval of rewards :/

**Comment by MikeLydeamore** [comment]
I added that in today. Will be in next build. 
https://bitbucket.org/MikeLydeamore/ex-nihilo/commits/df9927d3b2995fb9a872746c04a4ff4a1fbb7ac0

**Comment by jaredlll08** [comment]
I litteraly just started doing the fix xD

**Comment by Turkey2349** [comment]
@MikeLydeamore thanks man!

**Comment by hephinator** [comment]
Woot!

**Comment by hephinator** [comment]
Re-opened, waiting for Build 42 from @MikeLydeamore which hopefully ModTweaker 0.8.2? can properly fix.

**Comment by hephinator** [comment]
Fixed w/ EN 1.38-42 & MT2 0.8.2.
