### ISSUE TITLE
Add compatibility for Mekanism v8 Metallurgic Infuser recipes

### ISSUE THREAD

**Issue by Xee1** [jaredlll08/ModTweaker2#149]
Hi @jaredlll08 , If possible,could you re-add that ability? Thank you for this awesome mod! Keep it up!

**Comment by jaredlll08** [comment]
From what I saw mekanism removed it, if you can show me different, then
maybe

**Comment by Xee1** [comment]
You mean metallurgic infuser? @jaredlll08 
I'm using Mekanism 8.1.3(latest version) and metallurgic infuser is present and fully working. It's the basic of Mekanism(especially for the circuits). Here a screenshot
![aasa](https://cloud.githubusercontent.com/assets/8685029/7938296/14c88fb8-0945-11e5-87ed-b677bc4223b0.png)

**Comment by jaredlll08** [comment]
I mean the api for it...

**Comment by Xee1** [comment]
Oh sorry,  yes there is, but now recipes works with IMC, the RecipeHelper is deprecated

**Comment by jaredlll08** [comment]
Then no support sorry.

**Comment by Xee1** [comment]
if I can know, Why? @jaredlll08 
For example AOBD support Mekanism v8 and adds recipes for every single ore, see this: https://github.com/ganymedes01/Another-One-Bites-the-Dust/blob/mc1.7/src/main/java/ganymedes01/aobd/recipes/modules/Mekanism.java

**Comment by jaredlll08** [comment]
Because MINEtweaker does not support IMC messages, the scripts loads to late.

**Comment by Xee1** [comment]
Oh, now I understand,sorry, thank you for your time!

**Comment by jaredlll08** [comment]
Actually thank you, I can tell people why I can't support it. :)

**Comment by Eyo0** [comment]
Actualy I don't know if it's important but the recipe tweaker on the Metalurgic infuser from Mekanism V8 work well with Modtweaker 0.7.5

**Comment by Yulife** [comment]
:clap:

**Comment by Xee1** [comment]
@Eyo0 I tried but doesn't work, can you write the script you used to make a recipe?
I'm using Mekanism 8.1.3

**Comment by Eyo0** [comment]
@Xee1 
mods.mekanism.Infuser.addRecipe("DIAMOND", 20, redstone * 2, basicwafer);
mods.mekanism.Infuser.addRecipe("OBSIDIAN", 20, redstone * 2, advwafer); 

Actualy I'm using Mekanism 8.1.1 haven't test with Meka 8.1.2 or 8.1.3 but I know than ModTweaker 0.8 don't work with Mekanism 8.1.1 so maybe they had been other change on Infuser since 8.1.1. Btw I think I'd see than they're some bugs with Metalurgic Infuser on Mekanism 8.1.3 not sure though.

Good luck :)
