### ISSUE TITLE
Thermal Expansion doesn't work at all

### ISSUE THREAD

**Issue by BaseCrusher** [jaredlll08/ModTweaker2#152]
Hello there,
well the title said it already. I'm trying to remove and to add some TE4 recipes and it doesnt recognize them. Even the exemple recipes from the wiki won't work.

Currently I'm using:
MineTweaker3-1.7.10-3.0.9C
ModTweaker 2-0.8.2
ThermalExpansion-[1.7.10]4.0.1-182

And befor i forget with ModTweaker 2-0.8.0 I was atleast able to add recipes.
Looking forward for the fix and thx. :)

**Comment by Yulife** [comment]
Is there an error? Please post your minetweaker.txt after you reload :)

**Comment by BaseCrusher** [comment]
Well not an error that would say it won't work. :/

ERROR: system: AutoSpawner is already defined in that package
ERROR: system: AutoSpawner is already defined in that package
INFO: Adding command minetweaker
INFO: Adding minetweaker command tooltips
INFO: Adding minetweaker command entities
INFO: Adding minetweaker command research
INFO: Adding minetweaker command aspectList
INFO: Adding minetweaker command materials
INFO: Adding minetweaker command lexiconCategories
INFO: Adding minetweaker command lexiconPages
INFO: Adding minetweaker command botaniaBrews
INFO: Adding minetweaker command lexiconKnowledgeTypes
INFO: Adding minetweaker command botaniaOrchid
INFO: Adding minetweaker command chiselGroups
INFO: Adding minetweaker command chiselVariations
INFO: Adding minetweaker command mfr
INFO: Removing 6 recipes
INFO: Adding recipe for Oak Wood Planks
INFO: Removing 6 recipes
INFO: Adding recipe for Spruce Wood Planks
INFO: Removing 5 recipes
INFO: Adding recipe for Birch Wood Planks
INFO: Removing 6 recipes
INFO: Adding recipe for Jungle Wood Planks
INFO: Removing 3 recipes
INFO: Adding recipe for Acacia Wood Planks
INFO: Removing 3 recipes
INFO: Adding recipe for Dark Oak Wood Planks
INFO: Removing 1 recipes
INFO: Adding recipe for Sacred Oak Wood Planks
INFO: Removing 1 recipes
INFO: Adding recipe for Cherry Wood Planks
INFO: Removing 1 furnace recipes
INFO: Adding minetweaker command tooltips
INFO: Adding minetweaker command entities
INFO: Adding minetweaker command research
INFO: Adding minetweaker command aspectList
INFO: Adding minetweaker command materials
INFO: Adding minetweaker command lexiconCategories
INFO: Adding minetweaker command lexiconPages
INFO: Adding minetweaker command botaniaBrews
INFO: Adding minetweaker command lexiconKnowledgeTypes
INFO: Adding minetweaker command botaniaOrchid
INFO: Adding minetweaker command chiselGroups
INFO: Adding minetweaker command chiselVariations
INFO: Removing minetweaker command chiselVariations
INFO: Removing minetweaker command chiselGroups
INFO: Removing minetweaker command botaniaOrchid
INFO: Removing minetweaker command lexiconKnowledgeTypes
INFO: Removing minetweaker command botaniaBrews
INFO: Removing minetweaker command lexiconPages
INFO: Removing minetweaker command lexiconCategories
INFO: Removing minetweaker command materials
INFO: Removing minetweaker command aspectList
INFO: Removing minetweaker command research
INFO: Removing minetweaker command entities
INFO: Removing minetweaker command tooltips
INFO: Restoring 1 furnace recipes
INFO: Removing recipe for Cherry Wood Planks
INFO: Restoring 1 recipes
INFO: Removing recipe for Sacred Oak Wood Planks
INFO: Restoring 1 recipes
INFO: Removing recipe for Dark Oak Wood Planks
INFO: Restoring 3 recipes
INFO: Removing recipe for Acacia Wood Planks
INFO: Restoring 3 recipes
INFO: Removing recipe for Jungle Wood Planks
INFO: Restoring 6 recipes
INFO: Removing recipe for Birch Wood Planks
INFO: Restoring 5 recipes
INFO: Removing recipe for Spruce Wood Planks
INFO: Restoring 6 recipes
INFO: Removing recipe for Oak Wood Planks
INFO: Restoring 6 recipes
INFO: Removing minetweaker command mfr
INFO: Removing minetweaker command chiselVariations
INFO: Removing minetweaker command chiselGroups
INFO: Removing minetweaker command botaniaOrchid
INFO: Removing minetweaker command lexiconKnowledgeTypes
INFO: Removing minetweaker command botaniaBrews
INFO: Removing minetweaker command lexiconPages
INFO: Removing minetweaker command lexiconCategories
INFO: Removing minetweaker command materials
INFO: Removing minetweaker command aspectList
INFO: Removing minetweaker command research
INFO: Removing minetweaker command entities
INFO: Removing minetweaker command tooltips
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command tooltips
INFO: Adding minetweaker command entities
INFO: Adding minetweaker command research
INFO: Adding minetweaker command aspectList
INFO: Adding minetweaker command materials
INFO: Adding minetweaker command lexiconCategories
INFO: Adding minetweaker command lexiconPages
INFO: Adding minetweaker command botaniaBrews
INFO: Adding minetweaker command lexiconKnowledgeTypes
INFO: Adding minetweaker command botaniaOrchid
INFO: Adding minetweaker command chiselGroups
INFO: Adding minetweaker command chiselVariations
INFO: Adding minetweaker command mfr
INFO: Removing 6 recipes
INFO: Adding recipe for Oak Wood Planks
INFO: Removing 6 recipes
INFO: Adding recipe for Spruce Wood Planks
INFO: Removing 5 recipes
INFO: Adding recipe for Birch Wood Planks
INFO: Removing 6 recipes
INFO: Adding recipe for Jungle Wood Planks
INFO: Removing 3 recipes
INFO: Adding recipe for Acacia Wood Planks
INFO: Removing 3 recipes
INFO: Adding recipe for Dark Oak Wood Planks
INFO: Removing 1 recipes
INFO: Adding recipe for Sacred Oak Wood Planks
INFO: Removing 1 recipes
INFO: Adding recipe for Cherry Wood Planks
INFO: Removing 1 furnace recipes

**Comment by Zixxl** [comment]
Tested the functions in the development environment and found 2 bugs. For one thing the check ```java if (!TweakerPlugin.hasInit())``` prevents, that the functions do anything, because hasInit() returns true, after minecraft has loaded. After i removed the check, i ran into another problem. I tried to remove the recipe for baked potato. But the dev version i used (ThermalExpansion-[1.7.10]4.0.0-176-dev) holds the recipe twice and i can only remove one recipe. The second call to ```java FurnaceManager.getRecipe(input);``` returns null, despite there is a second recipe for baked potato. This seems to be a bug in ThermalExpansion.

**Comment by BaseCrusher** [comment]
So, is there something I can do now without waiting for the next version? (Sorry, not that familiar programing)

**Comment by Zixxl** [comment]
The second bug seems to only affect default food items (porkchop, beef, chicken, potato and fish) which are added in ThermalExpansion / FurnaceManager, other recipes have no duplicates and can be removed.
I am also new to modding, so maybe someone who developed this mod knows, why the check ```if (!TweakerPlugin.hasInit())``` was implemented.

**Comment by Zixxl** [comment]
The check ```(!TweakerPlugin.hasInit())``` was implemented in commit 0f461a7815473bcda6a53b01db3dc500d0405a7b. Maybe it should actually be without the negation?
