### ISSUE TITLE
Removed Inscriber Press Recipie -> Crash with NullPointerException

### ISSUE THREAD

**Issue by DerOli82** [jaredlll08/ModTweaker2#154]
Cross-Ref: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1602

Quote:
Minimal Setup:
- Forge: 10.13.3.1428
- Applied Energistics rv2 stable 5
- CodeChickenCore 1.0.7.46
- MineTweaker 3.0.9c
- ModTweaker 0.8.2
- NotEnoughItems 1.0.5.110

ModTweaker Script: http://pastebin.com/f9XXTgSJ
Crash-Report: http://pastebin.com/Cn4E122r

First i got no problems by looking up the Inscriber Press recipe in NEI. After sending /mt reload command the game crashs if i looking up the Inscriber Press recipe again.

**Comment by Zixxl** [comment]
You have to specify the output not the press to remove the recipes. I've fixed the NullPointerException after ```/mt reload``` with #153.

Corrected Script: http://pastebin.com/ib95emKZ

**Comment by jaredlll08** [comment]
Seems to be fixed by @Zixxl thanks! @Zixxl would you be interested in helping me fix modtweaker?

**Comment by Zixxl** [comment]
Do mean this Version (ModTweaker2) or the Version for Minecraft 1.6.4? I'm working on my own modpack so i'll definitly continue to work on the 1.7.10 Version. Personally i don't need the Version for 1.6.4, but if you need help i can help you fix this as well.

**Comment by jaredlll08** [comment]
AE2 caches their recipes. Also any issue with the words /mt reload is being
thrown in the bin. It is not safe or good to use.
