### ISSUE TITLE
Misc. Errors when adding recipes

### ISSUE THREAD

**Issue by Gideonseymour** [jaredlll08/ModTweaker2#156]
Modtweaker occasionally throws an error upon adding a modtweaker recipe, such as a Thermal Expansion Pulveriser recipe or a Railcraft Blast Furnace recipe. After doing the /mt reload, all of the minetweaker scripts stop working. They all throw an error along the lines of "Missing --)".

Removing lines from the script does nothing, unless all Modtweaker lines are removed. The unmodified script will begin working again once the game is restarted. Reloading the world will not affect it.

**Comment by Gideonseymour** [comment]
Reloading the world without restarting the game does not fix the issue

**Comment by jaredlll08** [comment]
I need more info on this, I need to know exact errors and I need a minetweaker log.

**Comment by jaredlll08** [comment]
http://www.reddit.com/r/feedthebeast/comments/3acdqc/psa_never_use_mt_reload_or_anything_of_the_like/
