### ISSUE TITLE
Ex Nihilo... again.

### ISSUE THREAD

**Issue by wujekbrezniew** [jaredlll08/ModTweaker2#157]
Removal of Ex Nihilo recipes still doesn't work.
I use this script mods.exnihilo.Sieve.removeRecipe(<example drop>); and i get error "a method available but none matches the parameters" .

**Comment by jaredlll08** [comment]
This is a user erro, it means that you do nit provide the correct arguments

**Comment by wujekbrezniew** [comment]
I don't know what does the "correct arguments" mean. I copied this code from wiki.

**Comment by jaredlll08** [comment]
@Yulife update the wiki please.
You are missing an argument, that is what the error means, iirc it now takes, output and input

**Comment by Yulife** [comment]
Huh? :o What argument is missing?
