### ISSUE TITLE
Aura Cascade Wiki Fix

### ISSUE THREAD

**Issue by DrasticDemise** [jaredlll08/ModTweaker2#159]
Broken Script:
//Pylon Recipes
//OutputStack, AuraInput, InputStack, 
mods.auraCascade.Pylon.addRecipe(<minecraft:diamond>, <aura:RED_AURA>*50, <minecraft:dirt>);
//OutputStack, AuraInput1, InputStack1, AuraInput2, InputStack2, AuraStack3, InputStack3, AuraStack4, InputStack4
mods.auraCascade.Pylon.addRecipe(<minecraft:diamond>, <aura:GREEN_AURA*1>, <minecraft:dirt>, <aura:RED_AURA*30>, <minecraft:dirt>, <aura:BLUE_AURA*90>, <minecraft:dirt>, <aura:WHITE_AURA*1500>, <minecraft:dirt>;
//OutputStack
mods.auraCascade.Pylon.removeRecipe(<minecraft:diamond>);

Fixed:
http://pastebin.com/9yrgv8mk

Red aura bracket out of place and a missing parenthesis after dirt on the second output stack.

**Comment by Yulife** [comment]
You can edit the wiki yourself. :) You just need an account. I can edit it if you don't want to, though.

**Comment by DrasticDemise** [comment]
I think Jared fixed it, I hit him up on IRC.

**Comment by jaredlll08** [comment]
I did nothing >.> you did it all!
