### ISSUE TITLE
Can't delete Thaumcraft copper/gold... capped Wand Arcane Recipes

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#16]
Now after Azanor change some code i can delete the iron capped wand but i cant remove the other wands. The Arcane remove Recipes code works only with researchable Items.

mods.thaumcraft.Arcane.removeRecipe(Thaumcraft:WandCasting:2.withTag({cap: "copper", rod: "wood"}));

i try also
mods.thaumcraft.Arcane.removeRecipe(Thaumcraft:WandCasting:*

my new Recipes work but the old original one too.

mods.thaumcraft.Arcane.addShaped("CAP_copper", Thaumcraft:WandCasting:2.withTag({cap: "copper", rod: "wood"}), "aer 10, terra 10, ignis 10, aqua 10, ordo 10, perditio 10", [
[TwilightForest:item.trophy:1, ore:screwAluminium, Thaumcraft:WandCap:3],
[ore:screwAluminium, Forestry:oakStick, ore:screwAluminium],
[Thaumcraft:WandCap:3, ore:screwAluminium, ore:craftingToolScrewdriver]]);

I using CAP_copper because the Wand no have any research.
Maybe i did something wrong ?

**Comment by Dream-Master** [comment]
I posted the issue in the Thaumcraft Git too.
https://github.com/Azanor/thaumcraft/issues/1532

**Comment by jaredlll08** [comment]
Read what @Azanor said... He mentions it right there, wands use custom code that bypass vanilla recipes...

**Comment by Dream-Master** [comment]
Is it possible to writing new Recipes with Java ? Or i change the recipes not using Caps any more and make new caps research Sites in the book.
Before i thought i can change everything with Minetweaker/Modtweaker but i can't. So finally i have to learn more Java.

**Comment by jaredlll08** [comment]
If you can't do it in modtweaker (the method doesn't work) then you can't do it in java

**Comment by Dream-Master** [comment]
Ok thanks for your help.
I try to changing the Thaumcraft Wand Caps to some things else or make new Items with Java and new Researches in the Book.
With the Reipes it is so important for me because I try to make a Hardcore Modpack and many Recipes from Thaumcraft are to easy.
Will Modtweaker add some new Mod Support in the Future? I think Galacticraft and Witchery would be nice.
I hope my Questions not annoying you. I have a plan how my Recipes have to look like and i want to find a way to do that.

**Comment by Yulife** [comment]
GC is not capable of recipe removing and Witchery has no API. No API, no support.

**Comment by Dream-Master** [comment]
I can remove/add/change Recipes in GC only the Rocket and the Moon Buggy Recipes I cant change. Maybe have to asking about an api for witchery.

**Comment by Yulife** [comment]
Do not ask. It's been highly requested, the author will do it when he feels like doing it.
