### ISSUE TITLE
Thermionic Fabricator Cast recipes cant be removed with Version 0.8.3

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#160]
I tested your new 0.8.3 Version and everthing in Thaumcraft seems to work now but Forestry Thermionic Fabricator Recipes i cant remove.

I try my recipes and your Sample recipes from the wiki and it dind work

mods.forestry.ThermionicFabricator.removeCasts(<Forestry:stained>);

mods.forestry.ThermionicFabricator.removeCasts(<Forestry:thermionicTubes>);

Is there something change which is not ducumented on the WIKI.

With Version 0.8.0 it works.

https://gist.github.com/Dream-Master/1f7287cb4a465f64212f#file-gistfile1-txt

https://gist.github.com/Dream-Master/4e3dcee1e44f4ab34e69

Why its say in the error log smelting. i remove a casting recipes not a smelting one.

**Comment by Voidi** [comment]
Are you using the recent build from Jenkins? If so, then this must associated with the latest changes from @Zixxl 
I will take a deeper look at this tomorow, as i want to rework the Forestry functions anyway.

**Comment by Zixxl** [comment]
Maybe i broke something, i changed a lot of classes :-\ I'll take a look at the changed i made.

**Comment by Dream-Master** [comment]
I thought your jenkins is private. I dont have the link any more. I using the curse link
