### ISSUE TITLE
[Enhancement] Add mt command to list smeltery recipes

### ISSUE THREAD

**Issue by BakermanLP** [jaredlll08/ModTweaker2#162]
Hello there,

could you please add a /mt command to list all smeltery recipes and alloys?

That would be quite usefull to alter the smeltery. At the moment in our modpack there are about 38 materials to smelt into cobalt for example. This would help a lot.

Thanks for reading

Michael (aka BakermanLP)

**Comment by jaredlll08** [comment]
I could do this, which would be easy. however, I would the need to add the command for every recipe(to get rid of favoritism).

**Comment by Zixxl** [comment]
Something like this?

/mt tconstruct smeltery
http://pastebin.com/j6aPTvhV

**Comment by BakermanLP** [comment]
That is exactly the result I am looking for. Great work!

**Comment by Zixxl** [comment]
Added to ModTweaker2 0.9.0. Please update!
