### ISSUE TITLE
[Enhancement] Add TinkersConstruct Smeltry Fuel possibility

### ISSUE THREAD

**Issue by BakermanLP** [jaredlll08/ModTweaker2#164]
Hello,

would be nice to have a possibility to add some other fuels to the smeltery of TinkersConstruct

Michael (aka BakermanLP)

**Comment by Zixxl** [comment]
I looked at the code, should be pretty easy to add the support for smeltery fuel.

**Comment by jaredlll08** [comment]
Take a look at jsonables, dors exaclty this

**Comment by Dream-Master** [comment]
But add this feature to Modtweaker would be nice too!

**Comment by jaredlll08** [comment]
I just don't see the point in adding the exact same feature to 2 of my own
mods.

**Comment by Dream-Master** [comment]
You can add fuels in Gregtech Machines with minetweaker too. I think adding Fuels have to be in Modtweaker for my opinion. Why I have to add a new mod only for one or two lines of code?

**Comment by jaredlll08** [comment]
Because it is not 2 lines of code? Modtweaker is for recipe tweaks, not
adding things like the fuel would be.

**Comment by Zixxl** [comment]
Was actually 50 lines of code.

**Comment by Yulife** [comment]
Jared it doesn't matter if it exists in both of your mods. Most of the people use Modtweaker, not JSONables.

**Comment by jaredlll08** [comment]
It is not being lazy, it is just that there should not be any reason for me to write code twice.

**Comment by Yulife** [comment]
Aka lazy. Then let someone else do it.

**Comment by jaredlll08** [comment]
I am, if you looked in irc a while ago, I told @Zixxl why I didn't want to do it, and said I had no problem with him doing it

**Comment by Zixxl** [comment]
Added commands:
```
mods.tconstruct.Smeltery.addFuel(Liquid, (int)Power, (int)Duration)
mods.tconstruct.Smeltery.removeFuel(Ingredient)
```

Examples:
```
mods.tconstruct.Smeltery.addFuel(<liquid:water>, 1300, 80); // adds water as fuel

mods.tconstruct.Smeltery.removeFuel(<liquid:lava>); // remove lava
mods.tconstruct.Smeltery.removeFuel(<*>); // remove all fuels
```

**Comment by BakermanLP** [comment]
Thank you very much. Works great in our modpack. Top support!

Zixxl <notifications@github.com> schrieb am Di., 14. Juli 2015 um 14:24 Uhr:

**Comment by Zixxl** [comment]
Added to ModTweaker2 0.9.0. Please update!
