### ISSUE TITLE
More a question then an issue.

### ISSUE THREAD

**Issue by bookerthegeek** [jaredlll08/ModTweaker2#165]
Sorry for posting here but unable to find the info elsewhere. 

Thaumcraft and/or add-ons introduce shards that drop only from vanilla nether mobs.

Special mobs converts all nether mobs to non-vanilla variations. 

Now, no more shards. What would be the best way to add them as a drop? I could not find a script to either add the shards to other mobs (in this case modifying the thaumcraft add on code) or making the special mobs drop shards (by tweaking special mobs code)

Thank you for your help. And again sorry for posting this here.

**Comment by UndeadZeratul** [comment]
[Mob Properties](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282771-forge-father-toasts-mods-special-mobs-mob) might be what you're looking for.

**Comment by bookerthegeek** [comment]
While helpfull, and thank you, more so looking to be able to script in drops for mobs, either by adding drops to the mobs or specifying additional mobs that can drop an item.

**Comment by jaredlll08** [comment]
Already attempted this, couldn't get it working, ALSO it is on the todo list for MINEtweaker, so I would say, just wait.

**Comment by bookerthegeek** [comment]
Thank you. I did search their but must have missed it. 

I will quietly wait. :)
