### ISSUE TITLE
Tinkers Construct - Disable Stencil Table Crating

### ISSUE THREAD

**Issue by Nentify** [jaredlll08/ModTweaker2#166]
Would it be possible to disable crafting of some stencils such as the hammer head crafting in this table?

Thanks!

**Comment by Zixxl** [comment]
Difficult task, because the stencil table and the crafting recipes arre tied to the ui components. I don't know which side effects this would have.

**Comment by jaredlll08** [comment]
Not possible, due to the ui stuff

**Comment by ubermentat** [comment]
Is it safe to assume the ui problem would also apply to adding handlers for part builder recipes? If not I can open a new issue for that request.
