### ISSUE TITLE
what am I doing wrong?

### ISSUE THREAD

**Issue by skellitor301** [jaredlll08/ModTweaker2#167]
I dont know what I'm doing wrong. My original goal was to be able to make platinum an alloy using manasteel and redstone, using the tinkers construct smelter to accomplish this. I've run into the error "1 method available but none matches the parameters". I've simplified it down to just one modification, after trying several itterations and each failing to work, to where I would just smelt coal down into the shiny ingot in the smeltery. Even this doesn't work. Here's the script so you can see what is trying to run:
mods.tconstruct.Smeltery.addMelting("minecraft:coal", "TConstruct:fluid.molten.shiny" * 20, 100, "minecraft:coal_block");

each item id was given using the /mt hand command so the id's aren't the issue. 

Note: Due to Github hiding the "<" and ">" brackets I've changed them to "

**Comment by Voidi** [comment]
The function expects as second parameter a fluid name from the forge fluid registry.
For Shiny/Platinum this would be `<liquid:platinum.molten>`.
What you specified is the fluid block which represents the fluid in the world.

**Comment by Yulife** [comment]
Ya, you don't enter liquids like that in Minetweaker @skellitor301. Instead, you use a special bracket type, namely "liquid:[liquidname". You can get all liquid names via the command /mt liquids  and look in your Minetweaker.txt file in your minecraft folder.

**Comment by Voidi** [comment]
@Yulife actually it's minetweaker.log

**Comment by skellitor301** [comment]
Ah, kinda confusing when the tutorials say use /mt hand to get the names and it doesn't give you the proper one for the mod itself to use. Anyway, thanks for the help guys
