### ISSUE TITLE
AE2 crash on removed Inscriber recipes

### ISSUE THREAD

**Issue by JasonMcRay** [jaredlll08/ModTweaker2#169]
In InfiTech 2 modpack I am removing all AE2 inscriber recipes and moving them into GT machine. But if I remove all Inscriber recipes and I try to look uses with nei on ANY item, i am greeted with crash: http://pastebin.com/BCMztEtB

Exact steps to reproduce.
1) Make a script
```mods.appeng.Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:15>);
mods.appeng.Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:13>);
mods.appeng.Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:14>);
mods.appeng.Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:19>);
mods.appeng.Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:18>);
mods.appeng.Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:16>);
mods.appeng.Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:17>);
mods.appeng.Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:20>);
mods.appeng.Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:22>);
mods.appeng.Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:23>);
mods.appeng.Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:24>);
```

2) Start minecraft and log into world
3) Check uses with "U" on any item. It will show correctly
4) Now reload the scripts using /mt reload
5) Check uses again on any item. It will crash with the crash above.

Used versions
ModTweaker: 0.8.2
MineTweaker: 3.0.9C
AE2: rv2 stable 9
Forge: 1420

**Comment by Zixxl** [comment]
Jared will get angry if he reads "/mt reload" :D Use ModTweaker 0.8.3, the bug was fixed in the last version.

**Comment by JasonMcRay** [comment]
I understand that mt reload can and will break stuff, but it is bit annoying to need after every script edit restart MC. :)

But thanks, will get 0.8.3 (i must have missed it when I was making an update on sunday :) )

**Comment by jaredlll08** [comment]
The reason I hate mt reload is because of this, nei is looking for a recipe
at position 5 however, you just removed the recipe at position 5 so it has
nothing to look at, therefor crashing.

**Comment by JasonMcRay** [comment]
Well it also happend when the recipes were already removed. As I said in
the reproduce steps. I made the script, then started minecraft and then did
/mt reload because I was doing other recipe changes.

2015-07-01 10:39 GMT+02:00 Jared <notifications@github.com>:

> The reason I hate mt reload is because of this, nei is looking for a recipe
> at position 5 however, you just removed the recipe at position 5 so it has
> nothing to look at, therefor crashing.
>
>

**Comment by jaredlll08** [comment]
Yep! Side effect, even if there is no change, minetweaker undoes the
action, the. Readds it

**Comment by JasonMcRay** [comment]
Oh I see. That makes "sense"

2015-07-01 11:37 GMT+02:00 Jared <notifications@github.com>:

> Yep! Side effect, even if there is no change, minetweaker undoes the
> action, the. Readds it
>
