### ISSUE TITLE
Growthcraft Support [SUGGESTION]

### ISSUE THREAD

**Issue by Sunconure11** [jaredlll08/ModTweaker2#171]
I know Growthcraft support has been planned for a while now, but, its probably possible now, the source has been released.

https://github.com/Gwafu/Growthcraft-1.7

If however you take suggestions for your support, I suggest stuff for the ferment barrel, so new forms of booze can be created. I have a few ideas of what I want to do with it, including some drinks that should have been put in Growthcraft but never got added.

**Comment by Voidi** [comment]
Have youasked the Growcraft Developer to add Minetweaker support himself?
Because it's always easier to have that in a mod itself, than external in modtweaker.

**Comment by Sunconure11** [comment]
Because the dev of Growthcraft is rather inactive.

**Comment by Yulife** [comment]
Isn't @Gwafu back in action again? He has opened a repo and the latest commit is a day old.

**Comment by Sunconure11** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286298-growthcraft-jul-15-2014-proper-1-7-10-release?comment=2081

**Comment by Yulife** [comment]
I believe the devs of the Growthcraft Community Edition want to make native support :)
