### ISSUE TITLE
Railcraft compacting chest

### ISSUE THREAD

**Issue by bookerthegeek** [jaredlll08/ModTweaker2#174]
Can't seem to find handlers for this issue.
https://github.com/CovertJaguar/Railcraft/issues/650

**Comment by jaredlll08** [comment]
Uh. Wat. That isn't a modtweaker issue, he is saying, if Immersive
Engineering adds a steel block, it can not be used in railcraft

**Comment by Zixxl** [comment]
You can add missing recipes with mods.railcraft.Rolling.addShaped().

**Comment by bookerthegeek** [comment]
Thank for the rolling machine handlers.

Was more so for the ability to tweak the output of the compacting chest. ( might have the name wrong.) It turns ingots into blocks, but only outputs railcraft ore blocks.

**Comment by Zixxl** [comment]
You want that bars of modification X will output blocks of modification X instead that all blocks are converted to the Railcraft version of the blocks?

**Comment by bookerthegeek** [comment]
Yes, exactly.

**Comment by Zixxl** [comment]
I don't think we can change the behavior of Railcraft for the metal chest.

**Comment by jaredlll08** [comment]
the RC author said it was a bad idea, sorry.
