### ISSUE TITLE
More witching gadgets handlers

### ISSUE THREAD

**Issue by bookerthegeek** [jaredlll08/ModTweaker2#176]
Original issue
https://github.com/BluSunrize/WitchingGadgets/issues/66

Is this something that can be added here or are we needing to wait for the mod author to add/change something? If something is needed on the other side, what would it be that is needed?

**Comment by thephoenixlodge** [comment]
Witching Gadgets MT support has nothing to do with Modtweaker, and is housed entirely in WG itself.

**Comment by Zixxl** [comment]
WitchingGadgets has native support for MineTweaker, so new functions / commands should also be implemented directly in the mod.
