### ISSUE TITLE
[SUGGESTION] Moar Botania Support

### ISSUE THREAD

**Issue by Neodark7** [jaredlll08/ModTweaker2#177]
Hi, can you add pure daisy support ? To ( remove the op blaze to obsidian thing ) add more x to y block recipes :D

**Comment by jaredlll08** [comment]
You sure we don't have this already? also your name is familiar? *checks twitter* ;)

**Comment by Neodark7** [comment]
yeah i'm the "where is the template D:" dude, and no i don't think MT have that, or the wiki is outdated.. update your documentation geeez D: ( The JSONables one too :v )

**Comment by Neodark7** [comment]
D: D: D: http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Botania_Support

**Comment by Yulife** [comment]
Jared some things have been added to Botania anyway so check the Botania API for updates ;)

**Comment by Zixxl** [comment]
Added #185

**Comment by Zixxl** [comment]
Added to ModTweaker2 0.9.0. Please update!
