### ISSUE TITLE
[INFO] Infusion Enchantment recipes add and remove

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#178]
I adding Infusion Enchantment recipes to the WIKI.

//Infusion Enchantment recipes
//ResearchKey, Enchantment ID, Instability, AspectsList, ArrayOfInputStacks,
mods.thaumcraft.Infusion.addEnchantment("XPBOOST", 45, 5, "victus 10, cognitio 8, vitreus 6",  [<minecraft:experience_bottle>, <minecraft:experience_bottle>,<minecraft:experience_bottle>,
 <Thaumcraft:ItemResource:14>]);
//ResultStack
mods.thaumcraft.Infusion.removeEnchant(45);

**Comment by jaredlll08** [comment]
So? why is this an issue?

**Comment by Dream-Master** [comment]
Thanks for complaining every time.

**Comment by jaredlll08** [comment]
What? This isn't am issue is it? If it is then please elaborate, but I am
homestly not sure why youade this bug report...

**Comment by jaredlll08** [comment]
If you are just notifying me that you did that, then thanks, but next time, just open an issue and close it, that way, I know it isn't a bug, and you are just notifying me
or I am always in IRC
#jaredlll08 on espernet

**Comment by Yulife** [comment]
I assume this is because this handler is missing on the doc?

**Comment by Dream-Master** [comment]
I add it already.

**Comment by Yulife** [comment]
Thank you!!! :thumbsup:
