### ISSUE TITLE
Relocation of Forestry Executions

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#18]
I swear to god Jared, I will bug you into infinity if you do not relocate these!

**Carpenter:**
*Original:* addRecipe(int packagingTime, ILiquidStack liquid, IItemStack product, IItemStack[] ingredients, IItemStack ingredient)
*New:* addRecipe(int packagingTime, ILiquidStack liquid, IItemStack[] ingredients, IItemStack ingredient, IItemStack product)

**Centrifuge:**
*Original:* addRecipe(IItemStack[] output, int[] chances, int timePerItem, IItemStack itemInput)
*New:* addRecipe(int timePerItem, IItemStack itemInput, int[] chances, IItemStack[] output)

**Fermenter:**
*Original:* addRecipe(IItemStack resource, int fermentationValue, float modifier, ILiquidStack output, ILiquidStack liquid)
*New:* addRecipe(IItemStack resource, ILiquidStack liquid, int fermentationValue, float modifier, ILiquidStack output)

**Thermionic Fabricator:**
*Original:* addSmelting(IItemStack itemInput, int fluidOutput, int meltingPoint)
*New:* addSmelting(IItemStack itemInput, int meltingPoint, int fluidOutput)

**Comment by Voidi** [comment]
Actually the form (Output, Input1, Inout2, ...) is more similar to the original Minetweaker recipe functions.

**Comment by jaredlll08** [comment]
@Voidi When it comes to inap, just do what he says >.>

**Comment by Yulife** [comment]
>:D
