### ISSUE TITLE
Forestry withTag recipes (Backpacks)

### ISSUE THREAD

**Issue by JasonMcRay** [jaredlll08/ModTweaker2#180]
I am adding a recipe for Forestry Woven Backpacks into Carpenter, it works when the backpack is freshly created. But when I put anything into the backpack and then take it out, it will seize to work.

Found possible reason and thats "used" Forestry backpack is using NBT information. This NBT has random UID value. 
Example: `<<Forestry:minerBag>>.withTag({UID: -882233916, Slots: {}})`

I tried to wildcard (*) the UID value using: `<<Forestry:minerBag>>.withTag({UID: *, Slots: {}})`
but I get an error: `Invalid Expression, last token: *`

is there anything you can do, or is it up to core MineTweaker?

The script I use is: mods.forestry.Carpenter.addRecipe(600, <liquid:seedoil> * 5000, [<Forestry:craftingMaterial:3>, <Forestry:craftingMaterial:3>, <Forestry:craftingMaterial:3>,<Forestry:craftingMaterial:3>, <Forestry:craftingMaterial:3>, <Forestry:craftingMaterial:3>,<Forestry:craftingMaterial:3>, <Forestry:craftingMaterial:3>, <Forestry:craftingMaterial:3>],<Forestry:minerBag>.withTag({UID: *, Slots: {}}), <Forestry:minerBagT2>);

Also I have tried it with `.onlyWithTag` still same.

**Comment by jaredlll08** [comment]
Minetweaker. not us.

**Comment by JasonMcRay** [comment]
:( So probably will not be fixed since I havent seen any update for quite a while on MT3 :( Thanks for information

**Comment by Voidi** [comment]
The wildcard can't be used in the NBT Data, but i think this is not MineTweaker problem more with the handling NBT in general.

That a item with NBT isn't valid for the recipe has nothing to do with Mine/Modtweaker, it depends how Forestry check for valid items. I will take a look at that.

**Comment by Yulife** [comment]
@mezz might want to look into that in Forestry? ;)

**Comment by Voidi** [comment]
I wouldn't even consider this a bug.

**Comment by Yulife** [comment]
Of course not. Just something for polishing lol
