### ISSUE TITLE
Thaumcraft aspectList command doesn't work

### ISSUE THREAD

**Issue by Killarflame** [jaredlll08/ModTweaker2#182]
Attempting to use this command throws this in the console: 
http://pastebin.com/zwmEyHMN

MineTweaker3-1.7.10-3.0.9C
ModTweaker 2-0.8.1

**Comment by Yulife** [comment]
Close the unvalid issues please in the other repos :)

**Comment by Killarflame** [comment]
I already have, or at least it says they are on my end.

**Comment by Zixxl** [comment]
Same issue: #147
Already fixed in newer versions. Please update ModTweaker2.
