### ISSUE TITLE
[Request] Add fuels for the Railcraft Blast Furnace

### ISSUE THREAD

**Issue by SynfulChaot** [jaredlll08/ModTweaker2#193]
Would it be possible to create a handler for adding new fuels to the Railcraft Blast Furnace?

**Comment by Zixxl** [comment]
It would be possible to add / remove items to the filter (accepted items) but you can't specify the fuel value for the items.

**Comment by SynfulChaot** [comment]
I know that current fuels in the Blast Furnace have differing fuel values.  Perhaps it uses the default value of the fuel itself?

**Comment by Zixxl** [comment]
The blast furnace uses some hard coded fuel values for coal coke, blaze rods and so on. If it doesn't know the fuel value, it will retrieve the value from the vanilla furnace.
So if you want adding new fuels to the railcraft blast furnace, you have to add a valid fuel source for the vanilla furnace and then add this item to the item filter for accepted items.
We could add a handler to manipulate the filter.

**Comment by Yulife** [comment]
Well, it would be possible to edit the vanilla fuel value Railcraft wants to grab. How would you imagine the manipulation @Zixxl?

**Comment by Voidi** [comment]
I original thougt the same way as zixxl that Tailcraft uses vanilla furnace fuel list.
But looking at https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/util/crafting/BlastFurnaceCraftingManager.java#L37 it seems the build an own list.
Shouldn't that complicated to modify.

**Comment by Zixxl** [comment]
Seems like the Railcraft lib in the repository is outdated. If it includes a list in newer versions, we could add a handler.

**Comment by Zixxl** [comment]
```fuels = Collections.unmodifiableList(fuel);```
Someone really wants to prevent modifications :disappointed:

**Comment by Dream-Master** [comment]
So it will be possible or not to set new Fuels with the newest Version?

**Comment by Zixxl** [comment]
Kind of. I've added the handlers to my dev branch. But you can only modify the filter, it must be a valid fuel item known by the vanilla furnace.

**Comment by SynfulChaot** [comment]
So it can be added to but it's limited to anything that's registered as a fuel for vanilla furnaces?

**Comment by Zixxl** [comment]
Exactly, you can burn your sticks for example or remove coal coke as a valid input. 
If you want to add custom fuels, you have to register it first with MineTweaker as a vanilla fuel. E.g. you want to use redstone, you can use:
```furnace.setFuel(<minecraft:redstone>, 100);```

**Comment by UndeadZeratul** [comment]
How breaking would it be to register an item as a vanilla fuel, then add it to the furnace, then remove the item as a vanilla fuel?

I'm going to assume Railcraft won't know what to do with the item anymore since it's no longer a fuel, but it was registered as one at the time of being enabled as a furnace fuel.

**Comment by Zixxl** [comment]
Sadly doesn't work this way. Railcraft has a list with all the items which can be used as an input. This list can be modified with the changes. But the fuel value will be fetched everytime the fuel will be used. Your method will lead to an exception.

**Comment by UndeadZeratul** [comment]
Darn, I was afraid of that.

**Comment by SynfulChaot** [comment]
Cool!  That's functionality enough, I think.  After all, what would be used in a blast furnace as fuel that wouldn't be burnable everywhere else?

**Comment by Yulife** [comment]
@Zixxl this doesn't seem to work very well - it just churns through the fuel in a matter of seconds although I set the burn time to 4000000. [Proof](https://www.dropbox.com/s/t6jq3o938k54qlq/2015-09-24_21-45-51.mp4?dl=0)

**Comment by Tsyklop** [comment]
http://pastebin.com/GmYUjSwa

my Error

**Comment by Yulife** [comment]
With error I meant that you should post your script, MT log and a description of the issue.

**Comment by Tsyklop** [comment]
@Yulife Fixed?

**Comment by Voidi** [comment]
it works for me with Railcraft 9.7.0, Modtweaker latest git version
