### ISSUE TITLE
vazkii/botania/common/item/block/ItemBlockSpecialFlower

### ISSUE THREAD

**Issue by Tsyklop** [jaredlll08/ModTweaker2#195]
Erro log: http://pastebin.com/TxyZq5sK

ModTweaker 0.9.0

Railcraft.zs -> http://pastebin.com/R9cmiwdG

If I comment on the second and fourth lines is that there is no error.

**Comment by Zixxl** [comment]
ModTweaker2 0.9.0 does not work without Botania. This Bug has been fixed in the repo, a new version will be released soon.

**Comment by Tsyklop** [comment]
@Zixxl Botania not installed
