### ISSUE TITLE
[bug] Can't remove Mekanism Metallurgic Infuser recipes (different issue this time)

### ISSUE THREAD

**Issue by Kataiser9** [jaredlll08/ModTweaker2#196]
I hate to bring back #91 after all this nice and mostly-functional Mekanism rewriting, but Infuser.removeRecipe() is borked again, in an entirely different way.

Attempting to call mods.mekanism.Infuser.removeRecipe(xyz) results in  "ERROR: fixes.zs:34 > No such static member in mods.mekanism.Infuser:removeRecipe".

Infuser.addRecipe() works fine, as did the other machine recipe removal I tested, Enrichment.removeRecipe().

Latest Modtweaker, Minetweaker, and Mekanism versions.

**Comment by Zixxl** [comment]
Woops, the annotation is missing. Will be fixed in the next release.

**Comment by Zixxl** [comment]
Fixed in Release 0.9.1.
