### ISSUE TITLE
[ThermEx] Adding oredict recipes to smelter

### ISSUE THREAD

**Issue by Nentify** [jaredlll08/ModTweaker2#199]
Edit: Figured the first issue out, the smelter stacks are in reverse, just needed to switch them over and it seemed to work.

When trying to add a new recipe using oredict values to the smelter with `Smelter.addRecipe(1, <ore:dustRedstone> * 4, <ore:ingotIron>, <bluepower:red_alloy_ingot>);`, I get the error below.

![2nd error](http://i.nentify.me/VoRIVP6M.png)

**Comment by jaredlll08** [comment]
NEVER RELOAD SCRIPTS

**Comment by Nentify** [comment]
AHHHH I'M SORRY.

I still get the error on a fresh game launch though.

![error](http://i.nentify.me/5Bfzp413.png)

**Comment by Zixxl** [comment]
The handler for adding recipes to the TE Smelter currently has no oredict support.

**Comment by Yulife** [comment]
Jared how about you add a warning to /mt reload in Modtweaker.

**Comment by Voidi** [comment]
This issue has nothing to do with reload? Instead maybe you could update the wiki witch type of parameter the functions accept?

**Comment by Zixxl** [comment]
Thermal Expansion does not support adding oredict entries for recipes, only values of type ItemStack. However internally TE fetches the OreID from the item. I've not tested it, but i think it is enough to just add one item from the oredict entry and the Smelter will automatically allow all items which have the same OreID from the ore dictionary.

Using ```Smelter.addRecipe(1, <minecraft:redstone> * 4, <minecraft:iron_ingot>, <bluepower:red_alloy_ingot>);``` should be enough.

**Comment by jaredlll08** [comment]
@yulife, I did that, look at the commit logs, and I got ahouted at so much
by the community.

**Comment by Yulife** [comment]
A proper warning. Not a joke. I told you that as well ;)
