### ISSUE TITLE
[Suggestion] HEE Support for the other three Altars

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#2]
Basically there are 3 altars left that aren't supported by Modtweaker yet:

Dragon Essence Altar

Fiery Essence Altar

Spectral Essence Altar

Calling @chylex! :D

**Comment by chylex** [comment]
Fiery Essence Altar requires implementing an interface, and Spectral Essence Altar doesn't exist :P

**Comment by jaredlll08** [comment]
So @chylex can I close this?

**Comment by Yulife** [comment]
Dragon Essence's left.
