### ISSUE TITLE
/mt LexiconPages throws error

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#20]
Regarded to @soundlogic2236.
The other commands like /mt LexiconCategories/Entries work fine and print it in the minetweaker.txt. However, /mt LexiconPages throws [this](http://paste.ee/p/OI29Q) error when used. It is both when non-defined and defined ( /mt LexiconPages ,  /mt LexiconPages flowers).
The [minetweaker.txt](http://paste.ee/p/ffY8h) doesn't say much about the error, though.

**Comment by soundlogic2236** [comment]
Does this still occur for you in build 7?

**Comment by Yulife** [comment]
Nope! :)
