### ISSUE TITLE
[AE2 Inscriber] Error msg

### ISSUE THREAD

**Issue by Tsunayoshi** [jaredlll08/ModTweaker2#200]
Hello,

since version 9.1 (maybe I have skiped some updates) I got error messages from the infuser recipes. Because the wiki hasn't updated an I can't find some related update nodes in the changelog. I don't know what is worng here:

Message:
ERROR: [ModTweaker2] Required parameters missing for Applied Energistics 2 Inscriber Recipe.
This msg appears 6x.

Script:

	//IMPORTS
	import mods.appeng.Inscriber;

	//VARS
	val processorGold = <appliedenergistics2:item.ItemMultiMaterial:22>;
	val processorCert = <appliedenergistics2:item.ItemMultiMaterial:23>;
	val processorDia = <appliedenergistics2:item.ItemMultiMaterial:24>;

	val printedGold = <appliedenergistics2:item.ItemMultiMaterial:18>;
	val printedCert = <appliedenergistics2:item.ItemMultiMaterial:16>;
	val printedDia = <appliedenergistics2:item.ItemMultiMaterial:17>;
	val printedSili = <appliedenergistics2:item.ItemMultiMaterial:20>;

	val chipGold = <BuildCraft|Silicon:redstoneChipset:2>;
	val chipQuartz = <BuildCraft|Silicon:redstoneChipset:5>;
	val chipDia = <BuildCraft|Silicon:redstoneChipset:3>;
	val chipRedstone = <BuildCraft|Silicon:redstoneChipset>;

	val pressLogi = <appliedenergistics2:item.ItemMultiMaterial:15>;
	val pressCalc = <appliedenergistics2:item.ItemMultiMaterial:13>;
	val pressEngi = <appliedenergistics2:item.ItemMultiMaterial:14>;

	val quartz = <appliedenergistics2:item.ItemMultiMaterial:10>;
	val dia = <minecraft:diamond>;
	val gold = <minecraft:gold_ingot>;

	//Inscriber Recipes
	//InputArray, plateA, plateB, OutputStack, TypeString //TypeStrings avaible are "Inscribe" and "Press"
	//Inscriber.addRecipe([<minecraft:iron_ingot>], <minecraft:redstone>, <minecraft:cobblestone>, <minecraft:piston>, "Inscribe");
	//Inscriber.removeRecipe(<appliedenergistics2:item.ItemMultiMaterial:15>);
	//Press -> Verbruachen
	//Inscriber -> Behalten

	//Cert
	Inscriber.removeRecipe(printedCert);
	Inscriber.addRecipe([chipQuartz], pressCalc, null, printedCert * 3, "Inscribe");  <---------------
	Inscriber.removeRecipe(processorCert);
	Inscriber.addRecipe([chipRedstone], printedCert, printedSili, processorCert, "Press");  <---------------

	//Dia
	Inscriber.removeRecipe(printedDia);
	Inscriber.addRecipe([chipDia], pressEngi, null, printedDia * 3, "Inscribe");  <---------------
	Inscriber.removeRecipe(processorDia);
	Inscriber.addRecipe([chipRedstone], printedDia, printedSili, processorDia, "Press");  <---------------

	//Gold
	Inscriber.removeRecipe(printedGold);
	Inscriber.addRecipe([chipGold], pressLogi, null, printedGold * 3, "Inscribe");  <---------------
	Inscriber.removeRecipe(processorGold);
	Inscriber.addRecipe([chipRedstone], printedGold, printedSili, processorGold, "Press");  <---------------

**Comment by Zixxl** [comment]
Hmm, i think i've made a logical mistake in the input check :disappointed:

**Comment by Tsunayoshi** [comment]
:smile: I am sure you can fix it. Take your time, I am not in a hurry with it.

**Comment by Zixxl** [comment]
Fixed in ModTweaker2 0.9.2. Please update!
