### ISSUE TITLE
Overwritten recipes mariculture.Anvil

### ISSUE THREAD

**Issue by Tsunayoshi** [jaredlll08/ModTweaker2#201]
Hello,

with the newest version (9.1) I got some error messages at login. Before that version all "addRecipe" where added side by side (as intened from my side). Now it seems that every line overwrite the gravel recipe. In game the only avabile recipe is the last cobbleblock from UBmetamprophic.

MSG:
WARNING: [ModTweaker2] Overwritten Mariculture Anvil Recipe for <minecraft:gravel> * 1

SCRIPT:

	////Imports
	import mods.mariculture.Anvil;

	//Vars
	val cobblestone = <minecraft:cobblestone>;
	val cobblestoneUBigneous = <UndergroundBiomes:igneousCobblestone:*>;
	val cobblestoneUBmetamorphic = <UndergroundBiomes:metamorphicCobblestone:*>;

	//Blacksmith's Anvil Recipes
	//InputStack, OutputStack, NumberOfHits
	Anvil.addRecipe(cobblestone, <minecraft:gravel>, 10);
	Anvil.addRecipe(cobblestoneUBigneous, <minecraft:gravel>, 15);
	Anvil.addRecipe(cobblestoneUBmetamorphic, <minecraft:gravel>, 20);
	Anvil.addRecipe(<minecraft:gravel>, <minecraft:sand>, 40);

**Comment by Zixxl** [comment]
The handler looks up the ore ID from the item you are providing. If all 'cobblestones' have the same ore id, then they are considered the same input. This behavior hasn't changed during the last versions, but you are now getting warning messages if they overwrite each other. All inputs should.
Maybe we can change this behavior, so you can specify if you want an item or an ore dict entry as input.

**Comment by Zixxl** [comment]
Looked at the code of Mariculture, nothing we can do. If we add the items without the oredict name, then Mariculture won't be able to fetch the recipe, because it will always look up the oredict name for the input.
The only solution i could imagine is to remove the items from the oredict before adding the recipes. This way neither the ModTweaker2 handlers nor Mariculture won't be able to lookup the oredict name.

**Comment by Tsunayoshi** [comment]
Ok I see the problem, i think your workaround is good for me. Thank you for this solution :smile:
