### ISSUE TITLE
[bug] Mekanism recipe removal doesn't work until reload command

### ISSUE THREAD

**Issue by Kataiser9** [jaredlll08/ModTweaker2#202]
(Wasn't totally sure if this should be here or on the Minetweaker tracker, but hey, it's about mod compatibility.)

Like the title says, using recipes.remove() on a Mekanism recipe doesn't take effect on session start, but only works after using "/mt reload". remove() is the only way I know of to remove "Mekanism Shaped/Mekanism Shapeless" recipe (in fact, if this info helps at all, removeShaped() doesn't work; it has to be remove()).

**Comment by Zixxl** [comment]
Hmm, maybe mekanism adds some of its recipes after minetweaker executes the scripts. Can you post the command you are using?

**Comment by Kataiser9** [comment]
val digiMiner = <Mekanism:MachineBlock:4>;
recipes.remove(digiMiner);

**Comment by jaredlll08** [comment]
Mekanism adds recipes after the world starts, therefor, mekanism issue. A mod is NEVER meant to do that, with minetweaker excluded.
