### ISSUE TITLE
Forestry's Squeezer has some issues with the addRecipe function

### ISSUE THREAD

**Issue by utoc** [jaredlll08/ModTweaker2#205]
Good afternoon!

I come forth with an issue after struggling with Modtweaker's Forestry documentation and have a few things to ask and have clarified.  From the wiki:

```
// Squeezer Recipes
//Time recipe requires (Ticks), InputArray, OutputFluid, OutputStack, Chance for OutputStack //The last two are optional
mods.forestry.Squeezer.addRecipe(4000, [<minecraft:packed_ice> * 4, <minecraft:snowball>], <liquid:ice> * 1000, <Forestry:craftingMaterial:5> * 2, 40);
```

So I used the following in my own scripts, `mods.forestry.Squeezer.addRecipe(100, [<ExtraBees:propolis:2>, <ExtraBees:propolis:2>], <liquid:fuel> * 500);`

This results in the error `ExtraBees.zs:10 > a method available but none matches the parameters (int, any[], minetweaker.liquid.ILiquidStack)`  As Modtweaker is designed now, you MUST specify a secondary drop and the chances.  I've skirted this issue temporarily by adding a propolis with 0% chance.  Is this intended and perhaps the documentation is outdated?

Also, I have one more request for clarification.  The input, in the case of the squeezer, must be an array.  What are we meant to do if we only want one propolis to be used in the squeezer?  I've tried `[<ExtraBees:propolis:2>]` and `[<ExtraBees:propolis:2>, null]` with no luck.

**Comment by Voidi** [comment]
The first thing will be fixed in the next version.
I will investigate the second thing.
