### ISSUE TITLE
[Request] TechReborn support

### ISSUE THREAD

**Issue by TheQuantumGeneral** [jaredlll08/ModTweaker2#208]
Gregtech 4 brought to 1.7.10, any chance of support this? 

https://github.com/TechReborn/TechReborn

https://github.com/TechReborn/TechReborn/issues/70

**Comment by Zixxl** [comment]
Gregtech support is provided by MineTweaker, they already added commits to the repo for the new GT versions.

**Comment by TheQuantumGeneral** [comment]
Tech Reborn isn't Gregtech, however I think they are adding it natively anyway.
