### ISSUE TITLE
Lexica Botania Category Entry Changer

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#21]
For @soundlogic2236.
Thaumcraft 4 Research Modtweaker Support is capable of moving research within tabs. So why not move Entries within Categories?

**Comment by soundlogic2236** [comment]
Unfortunately, it looks like the way entries are coded the category they are listed in is final. However, I might be able to write a function which copies over all the pages to a new entry. Functions which do multiple things at once will come, but I want to get all the 'primitive' functions out of the way and stable first.
