### ISSUE TITLE
Arcane Table remove recipes

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#210]
@jaredlll08 
@Zixxl 
@Voidi 
I know it is an old issue but i asking again.
Some recipes can't be removed like the wands. Azanor not let us do it. Is there now a possibility to hide this recipe that no one can see it. On my Server I disabled the wand caps and put new ones in side my core mod to change this recipes. Now my new Recipes are shown and the old not working thaumcraft recipes are there.

Thanks in advance

https://www.dropbox.com/s/zeh0vgwef4oovk0/Screenshot%202015-07-30%2013.54.07.png?dl=0
https://www.dropbox.com/s/ukh3nonauv9ltw7/Screenshot%202015-07-30%2013.54.09.png?dl=0
https://www.dropbox.com/s/jfdjqhmcxxjixrc/Screenshot%202015-07-30%2013.54.15.png?dl=0
https://www.dropbox.com/s/6igtboeckplrdc5/Screenshot%202015-07-30%2013.54.35.png?dl=0

**Comment by jaredlll08** [comment]
No way to hide it sorry.
Also hiding(not sure if possible via the nei api) would still allow people
to craft it with the old recipe.

**Comment by Dream-Master** [comment]
If i disabled the caps it is not possible to craft this wand but this only the second best way not the best one.

I think when i hide it in Nei all Wands are be hidden because they using meta Ids as far i know nei heide all items from this id.

**Comment by Yulife** [comment]
Well, you could remove their 'Nomicon entry with Modtweaker and show the new recipes in a rewritten one :)

**Comment by Dream-Master** [comment]
Yes but when i use Thaumcraft Nei Plugins the wrong recipes are shown. Maybe i have to kick this mod it for the other recipes it is very handy.

**Comment by Yulife** [comment]
Well, you can't have everything working in the world, sadly.
