### ISSUE TITLE
FR: "give back"- command for Thaumcraft Infusion

### ISSUE THREAD

**Issue by netzgeist** [jaredlll08/ModTweaker2#214]
Im adding a custom TC4 Infusion, and I need a way to keep or even replace an (non-main-item) ingrident after a successful infusion.

Example: Bucket of Water as an ingredient. Give me an empty bucket back.
Example2: Primordial Pearl as an inigredient. Give me the pearl back.

**Comment by jaredlll08** [comment]
Not possible. due to thaumcraft limitations
