### ISSUE TITLE
"/mt botaniaOrchid" command typo, should be "/mt botaniaOrechid"

### ISSUE THREAD

**Issue by Zyin055** [jaredlll08/ModTweaker2#220]
As the title says, there's a typo in the command for "/mt botaniaOrchid". Orechid has an 'e' in it. The botaniaOrechid command is unrecognized, but is spelled that way on the 
Botania support page: http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Botania_Support.

**Comment by Yulife** [comment]
https://github.com/jaredlll08/ModTweaker2/commit/8c974ec7e96c456013a346d6936ef3ac9b722fc8
There you go ;)
