### ISSUE TITLE
Mekanism Purification Chamber wiki/code issue

### ISSUE THREAD

**Issue by iPencil** [jaredlll08/ModTweaker2#221]
Hi,

in the wiki it says:

```//Purification Chamber
//InputStack, OutputStack
mods.mekanism.Purification.addRecipe(<minecraft:mossy_cobblestone>, <minecraft:cobblestone>);
//OutputStack
mods.mekanism.Purification.removeRecipe(<Mekanism:Clump:1>);```

However it's actually //InputStack, InputGas, OutputStack

Which doesn't really make sense because you can only pump oxygen into the machine anyways. 

Example:

````mods.mekanism.Purification.addRecipe(<creepgamingmod:PoorOreIron>, <Mekanism:Clump:0>);````

throws an error

````mods.mekanism.Purification.addRecipe(<creepgamingmod:PoorOreIron>, <gas:oxygen>, <Mekanism:Clump:0>);````

works fine.

Someone without modding background would have probably thought the recipe is bugged and wouldn't have figured it out, it should be changed :)

**Comment by Yulife** [comment]
The wiki is free to edit. :)

**Comment by iPencil** [comment]
I have a github account not a wiki account. I'm not gonna edit there. Also mind explaining why you can specify a gas when it only accepts oxygen in the first place? @Yulife

**Comment by Yulife** [comment]
A wiki account is easy to make. I can edit it now but for future reference please make an account there so you can easily edit it :) I don't know if it only accepts oxygen, is it hardcoded into Mekanism?

**Comment by Yulife** [comment]
Yup, it's hardcoded in. See https://github.com/aidancbrady/Mekanism/blob/42ce42aee23f9c73f0bd06ba3175354142805d47/src/main/java/mekanism/common/recipe/machines/PurificationRecipe.java#L17

**Comment by iPencil** [comment]
I did not only post it here because it's simply a wiki error, as I outlined in my first post, I don't think you can pump anything else into it, hence it would be easier to remove the gas input variable. Possibly the other processing machines are hardcoded too?
