### ISSUE TITLE
Request for IC2 Classic support by Speiger

### ISSUE THREAD

**Issue by Carbon-Ghost** [jaredlll08/ModTweaker2#223]
We want modtweaker support ^^

**Comment by jaredlll08** [comment]
![simply](http://media.makeameme.org/created/one-does-not-wa459t.jpg)

**Comment by Carbon-Ghost** [comment]
So no or yes ? :C 

 Confused xD

**Comment by Yulife** [comment]
Currently there are other plans for future Modtweaker support.
Some examples are:
- Big Reactors
- Growthcraft
- Updating current support
and so on. The IC2 Classic support is kind of miscellaneous so I suggest you ask the mod dev to add support natively :)

**Comment by Carbon-Ghost** [comment]
No that is what we want to do, but he need some help, can you talk with Speiger ?

**Comment by jaredlll08** [comment]
github username?

**Comment by Carbon-Ghost** [comment]
Speiger ^ ^

**Comment by jaredlll08** [comment]
got a repo for IC2 classic?

**Comment by Carbon-Ghost** [comment]
https://github.com/TinyModularThings/IC2Classic Here ^ ^
