### ISSUE TITLE
Useful addition for simplifying our lives

### ISSUE THREAD

**Issue by Carbon-Ghost** [jaredlll08/ModTweaker2#224]
When a script is loaded and a line is ignored due to the fact that a recipe is missing or it's a duplicate, it would be nice that the chat notifies us which line is deprecated ^^

**Comment by jaredlll08** [comment]
hhm this is more of a minetweaker thing :/ not sure how we would catch the line...

**Comment by Zixxl** [comment]
In the latest versions this is already implemented for some handlers. The logging will be further expanded in upcoming versions.

**Comment by Zixxl** [comment]
I'm closing this issue, because it is already planned to futher improve the logging.
