### ISSUE TITLE
[ExNihilo] Can't override/remove heat sources

### ISSUE THREAD

**Issue by DerOli82** [jaredlll08/ModTweaker2#225]
Versions:
- MineTweaker: 3.0.9C
- ModTweaker: 0.9.1
- Ex Nihilo: 1.38-45
- Ex Astris Rebirth: 1.01-45

If i try this to remove all heat sources: mods.exnihilo.Crucible.removeHeatSource(<*>); 
I get these warnings: http://pastebin.com/qF6suB8c

Same with only one removal: mods.exnihilo.Crucible.removeHeatSource(<minecraft:torch>);
I get: http://pastebin.com/uB9Uw54Q

The removed heat sources still works.

**Comment by jaredlll08** [comment]
Does ex astris have Nything to do with it? Like can this be duplicated
without it?

**Comment by DerOli82** [comment]
I get the same warnings without Ex Astris Rebirth.

**Comment by jaredlll08** [comment]
Ignore the warning, just the removing heat

**Comment by DerOli82** [comment]
The Problem is that the removed heat sources are still available.

**Comment by Zixxl** [comment]
I derped:

```RemoveHeatSource extends BaseMapAddition```

should be

```RemoveHeatSource extends BaseMapRemoval```

**Comment by Zixxl** [comment]
Fixed in ModTweaker2 0.9.2. Please update!
