### ISSUE TITLE
Planned features for ModTweaker2 0.9.4

### ISSUE THREAD

**Issue by Zixxl** [jaredlll08/ModTweaker2#228]
Thaumcraft:
- [ ] Add possibility to specify the recipe for displaying in Thaumonomicon instead of picking the first recipe which matches the output (#142)
- [ ] Add as much features from the vanilla crafting table to the arcane table. Transformers, maybe functions http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2364943-modtweaker-0-7-x?comment=92

Common:
- [ ] Change handlers with chances to use WeightedItemStack

**Comment by Yulife** [comment]
Thermal Expansion 4:
- [ ] Inverted Input1 and Input2 because they were the opposite (1 was 2 and 2 was 1) (https://github.com/jaredlll08/ModTweaker2/commit/4e7da8fa8476f3e82dfbbad7ad13cc9063a96b66)

**Comment by jaredlll08** [comment]
uh, if that is already done... then why is it not ticked off?

**Comment by Yulife** [comment]
Sssshhhh

**Comment by jaredlll08** [comment]
- [] this is a test

**Comment by jaredlll08** [comment]
- [ ] Add EXU support
- [ ] Remove TFC support
- [ ] Add IC2 Classic Support

**Comment by UndeadZeratul** [comment]
Out of curiosity, why was TFC Support moved to its own mod?

**Comment by jaredlll08** [comment]
Because it is anoyying, it is to invasive of the minecraft environment to actually test other mods, it added a good 5 minutes to the load time (on my laptop, samsung SSD, 16GB of ram, core i7), and then the world has to be a TFC world, that is the reason it was moved.

**Comment by UndeadZeratul** [comment]
Ah, alright; wasn't aware it caused that much of an impact.  Thanks for the clarification.

**Comment by jaredlll08** [comment]
also, it was really anoyying just disabling it, since eclipse would mark it as an error

**Comment by Tsyklop** [comment]
Add the wiki how to work with QED...

**Comment by Yulife** [comment]
Ever heard of please? lol
I will add it soon but for future reference, the wiki is open to edit for everyone.

**Comment by Tsyklop** [comment]
@Yulife Please)

**Comment by Yulife** [comment]
@Tsyklop [there you go :)](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Extra_Utilities_Support)

**Comment by Tsyklop** [comment]
@Yulife Wow. THX!

**Comment by Yulife** [comment]
General:
- [x] The mod string for the command is now called after the package of the
mod in the "mods" folder and [FILTER], or now called [HANDLER] got renamed to the Handler Java
classes for each mod (https://github.com/jaredlll08/ModTweaker2/commit/1a09d9f1151c1a65f0370e91e1311ab258f4f610)

**Comment by Yulife** [comment]
Factorization:
- [x] Switched Output numbers (https://github.com/jaredlll08/ModTweaker2/commit/fe52e2ad88de6b698bf13ee5f2c9f9050e20e593

**Comment by Yulife** [comment]
Forestry:
- [x] Switched Output and Input (https://github.com/jaredlll08/ModTweaker2/commit/29a40d4d67a647e7a73775d8fcc35ffc60c76d24) // This should affect no one as the code modified is not used in the wiki. This will now be used as the leading example in the wiki

**Comment by Yulife** [comment]
Thermal Expansion:
- [x] Disabled logging for Phytogenic Insolator (https://github.com/jaredlll08/ModTweaker2/commit/3ea99014f66f643d6877e209ca36bbea7d0283f2)
- [x] Switched Input parameters in the Induction Furnace removeRecipe method to the correct order  - **no backwards compability possible, users that use this function need to switch their InputStacks** (https://github.com/jaredlll08/ModTweaker2/commit/4607835f4b6a7e64c3a40ae4629bbd1905f61727, https://github.com/jaredlll08/ModTweaker2/commit/137a334965b3c9bef27adf224f1c222fd48f3211)

**Comment by Tsyklop** [comment]
add support for BigReactors pls!

**Comment by Yulife** [comment]
Seriously?

**Comment by Tsyklop** [comment]
@Yulife what? I have something not asked?

**Comment by Yulife** [comment]
You don't just barge in a random issue and ask for something, read the guidelines and make an own issue for it. :angry:

**Comment by Blue64** [comment]
@Yulife at least he remembered please xD
