### ISSUE TITLE
[TE4] Suport for Phytogenic Insolator

### ISSUE THREAD

**Issue by botaBG** [jaredlll08/ModTweaker2#229]
Can you add suport for the new Thermal Expansion machine Phytogenic Insolator.

**Comment by Yulife** [comment]
[??](https://github.com/jaredlll08/ModTweaker2/blob/master/src/main/java/modtweaker2/mods/thermalexpansion/handlers/Insolator.java)

**Comment by botaBG** [comment]
Nice :) but what I am doing wrong then:

ERROR: TE4.zs:1 > a method available but none matches the parameters (int, minetweaker.item.IItemStack, minetweaker.item.IItemStack, minetweaker.item.IItemStack, minetweaker.item.IItemStack, minetweaker.liquid.ILiquidStack)
ERROR: TE4.zs:2 > a method available but none matches the parameters (minetweaker.item.IItemStack)

TE4.zs file:
http://pastebin.com/XyQD1pny

**Comment by botaBG** [comment]
I dont see this file. Thank you

**Comment by Yulife** [comment]
You don't define a fluid in the handler, it's just water. The last part of the parameter should be the percentage of the secondary output.

**Comment by Yulife** [comment]
[The documentation has been updated](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Thermal_Expansion_Support). Look there if you want to have a working example :) I changed some stuff regarding the order of the two Inputs so don't be surprised if your order changes in 0.9.3.

**Comment by botaBG** [comment]
I was adding fluid and this was my problem, but now is ok. Thank you again

**Comment by Yulife** [comment]
:grin:
