### ISSUE TITLE
Botania (210) Lexica addEntry() doesn't work after API update

### ISSUE THREAD

**Issue by Wolwrig** [jaredlll08/ModTweaker2#230]
mods.botania.Lexicon.addEntry(string, string) doesn't work anymore. Looks like Vazkii updated the API and changed something. Running Botania version 210

Here is the error I get:
ERROR: BotaniaRecipes.zs:28 > a method available but none matches the parameters (string, string)

**Comment by Yulife** [comment]
addEntry needs an ItemStack now.

**Comment by jaredlll08** [comment]
so, @Yulife do we need to do anything? or can I close this?

**Comment by Yulife** [comment]
Wait for feedback lol :)

**Comment by Wolwrig** [comment]
So is this just a change I need to make in he script?

**Comment by jaredlll08** [comment]
Yea, you know how in the lexicon there is sometimes an icon next to an entry? we added support for that, your script should look something like (String, String, ItemStack)
so
mods.botania.lexicon.addEntry("String1", "String2", <minecraft:diamond>);

**Comment by Wolwrig** [comment]
Yes that works, as a note of clarity you example should be 

mods.botania.lexicon.addEntry("string1", "string2", <minecraft:diamond>);

to be syntactically correct

**Comment by Yulife** [comment]
Haha I'm glad my code crossover worked lol. :thumbsup:
