### ISSUE TITLE
New versions output error when adjusting TC output 

### ISSUE THREAD

**Issue by l3CY** [jaredlll08/ModTweaker2#231]
On updating to the latest version of Modtweaker many of my Tinkers Construct casting adjustments are returning errors.  For example the line

 mods.tconstruct.Casting.removeTableRecipe(<Forestry:ingotBronze>);

has traditionally worked but no longer does so.

**Comment by Yulife** [comment]
Well, please paste your script and the error ,_,

**Comment by l3CY** [comment]
Script: mods.tconstruct.Casting.removeTableRecipe(Forestry:ingotBronze);


Output: WARNING: [ModTweaker2] No TConstruct Casting Recipe found for output <Forestry:ingotBronze>, material <*> and cast <*>. Command ignored!

**Comment by jaredlll08** [comment]
... ... ... ... ... ... ... ... ... ... no, in the past it has just not thrown errors, this is a user error, it is basiclly saying, there is no recipe for that item, in the past, the code work go through, but wouldn't do anything, this has changed.
