### ISSUE TITLE
Thaumcraft 4 - Arcane Table function support

### ISSUE THREAD

**Issue by MagisterXero** [jaredlll08/ModTweaker2#234]
Hi, is there a way to get recipes like this to work?
In the mineTweaker3 itself, there are suboptions on items within the crafting recipes that allow you to giveBack(), transformReplace(), noReturn(), etc etc.

Are these suboptions/functions supported in a different way for Thaumcraft Arcane table recipes and Thaumcraft Infusion recipes?

mods.thaumcraft.Arcane.addShapeless("KEY", createdItem * 9, "ordo 5", [<itemDomain:itemIdentifier>.transformReplace(<itemDomain:itemIdentifier>), <ore:stone>]);

**Comment by MagisterXero** [comment]
Nevermind, just saw this is in the planned support.

**Comment by jaredlll08** [comment]
Thanks for looking at the planned features :) if only others did the same...

**Comment by MagisterXero** [comment]
hahaha if only I had checked sooner!
