### ISSUE TITLE
I can not remove a recipe from InductionSmelter.

### ISSUE THREAD

**Issue by Tsyklop** [jaredlll08/ModTweaker2#235]
I need to remove from the InductionSmelter bronze ingot. But I was faced with such a problem.
One of the recipes: 3 ingot of copper and tin ingot 1. But when I look in NEI it shows me that there is working OreDictionary. 

I write this: 
mods.thermalexpansion.Smelter.removeRecipe(<ThermalFoundation:material:64> * 3, <ThermalFoundation:material:65>);

But it does not work! He writes that this recipe is not! I tried to expose and oreDist other ingots but it is not working.

**Comment by jaredlll08** [comment]
Can I please have the log

**Comment by Tsyklop** [comment]
http://pastebin.com/VzJ3Jm0t
![2015-09-05_02 22 03](https://cloud.githubusercontent.com/assets/6783568/9696232/0a745bf8-5375-11e5-86eb-a30beedb6cd2.png)

**Comment by jaredlll08** [comment]
That is very self explanatory, there is no recipe for what you have provided, may I suggest trying, 
'mods.thermalexpansion.Smelter.removeRecipe(<ThermalFoundation:material:64>, <ThermalFoundation:material:65>);'

**Comment by Tsyklop** [comment]
as I then remove the recipe bronze?
It works OreDict and ingots are substituted with different mods ... what exactly to choose what to delete, I do not know ...

**Comment by Tsyklop** [comment]
How do I delete a recipe while bronze?

**Comment by Yulife** [comment]
You should look in the registry of Thermal Expansion to get the exact recipes.

**Comment by Tsyklop** [comment]
@Yulife where to look? I first heard about this just ...

**Comment by Tsyklop** [comment]
I figured out how to delete.

**Comment by Yulife** [comment]
Sorry, didn't see your reply! :( Could you post how you fixed it for others who may run into the same problem?

**Comment by Tsyklop** [comment]
@Yulife Like this:
mods.thermalexpansion.Smelter.removeRecipe(<ore:dustBronze> * 2, <minecraft:sand>);

<minecraft:sand> - first slot IS

<ore:dustBronze> * 2 - second slot IS

**Comment by Yulife** [comment]
:thumbsup:
