### ISSUE TITLE
Fails to reload script or load world after closing world. Client restart is needed.

### ISSUE THREAD

**Issue by bsaksida** [jaredlll08/ModTweaker2#236]
I added a lot of thaumcraft mods to FTB Infinity. I had more than 18 mods, so thoumonicon (Probably spelled it wrong) tabs overlapped. Other suggested using mod tweaker. So i did some moving. I even removed some research, because it was a copy of a duplicate and created new connection to original.
Upon testing, my script failed to reload because of script modifying research tabs for the mod Thaumaturgical Knowledge. Script works, expect i can not reload or even reload world after the use.

In logs, this part is intresting:
Intresting part: http://pastebin.com/1GA7E2bM
Complete log: (Too large for pastebin)
My Script: http://pastebin.com/aVL8RKXN

**Comment by jaredlll08** [comment]
Thaumcraft cannot be reloaded. End of story.
