### ISSUE TITLE
Not working interaction with the AE2

### ISSUE THREAD

**Issue by Tsyklop** [jaredlll08/ModTweaker2#237]
I took the example of a wiki:

mods.appeng.Inscriber.addRecipe([<minecraft:gold_block>], <appliedenergistics2:item.ItemMultiMaterial:15>, null, <appliedenergistics2:item.ItemMultiMaterial:18> * 9, "Press");

And:

![2015-09-06_21 21 33](https://cloud.githubusercontent.com/assets/6783568/9705921/685057b8-54dd-11e5-86c9-839ed69fbb2e.png)

**Comment by jaredlll08** [comment]
Downgrade AE2.

**Comment by Tsyklop** [comment]
and the other option?

**Comment by jaredlll08** [comment]
Downgrade AE2. No other option.
(I am assuming you are using an unstable build? If so downgrade, if not
then did ae2 get a new stable?)

**Comment by Tsyklop** [comment]
@jaredlll08  I`m using rv-3 alpha 5

**Comment by jaredlll08** [comment]
Yep, alpha, downgrade. I refuse to support alpha versions. Since everyone
that is not using an alpha has to update.

**Comment by Tsyklop** [comment]
@jaredlll08 Ok. When a wait for the update?

**Comment by jaredlll08** [comment]
Yes, when ae2 upgrades, we will.

**Comment by Tsyklop** [comment]
When AE2 upgrade to the stable 3?

**Comment by jaredlll08** [comment]
When the current changes are in a stable build.

**Comment by Tsyklop** [comment]
OK. I understood. thank.
