### ISSUE TITLE
[Request Feature] TinkerConstruct support: a way to disable a modifier

### ISSUE THREAD

**Issue by ExDomino** [jaredlll08/ModTweaker2#238]
I'm wondering if there is a way to remove a modifier from TinkweConstruct, the flux capacitor modifier. My need is to remove the modifier completely, so make unable for player to add this modifier on their tool in the tool station. Thank in advance! ^^

**Comment by Voidi** [comment]
Should already be possible: https://github.com/jaredlll08/ModTweaker2/blob/master/src/main/java/modtweaker2/mods/tconstruct/handlers/Modifiers.java
