### ISSUE TITLE
QED Table remove funktion missing

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#245]
I try to remove all QED Table recipes.

````````````
 mods.extraUtils.QED.removeRecipe(<*>);
```````````````````
it not works.

in Railcraft this works
``````````````
mods.railcraft.RockCrusher.removeRecipe(<*>);
````````````````
I hope you can add this funktion.

**Comment by Voidi** [comment]
`addShapedRecipe(IItemStack output, IItemStack[][] recipe)`
`<*>` funktionier nur bei IIngriedent

**Comment by Dream-Master** [comment]
@Voidi 
Kann man das vielleicht hinzufügen im code?
Can you add this in the code?

**Comment by Voidi** [comment]
I try it.
Denglish mixing ll the time.

**Comment by Dream-Master** [comment]
cool
