### ISSUE TITLE
Thermal Expantion problems

### ISSUE THREAD

**Issue by NanoSymmetry** [jaredlll08/ModTweaker2#246]
So im making a private mod pack and i cant figure out why this is broken it sometimes says it loads the script successfully but dosen't change the recipie.

recipes.remove(ThermalExpansion:Frame);
recipes.addShaped(ThermalExpansion:Frame,
 [[ore:ingotSteel, ore:blockGlass, ore:ingotSteel],
  [ore:blockGlass, ore:gearTin, ore:blockGlass],
  [ore:ingotSteel, ore:blockGlass, ore:ingotSteel]]);

Mods---\/
Mantle (by mDiyo)
Tinkers Construct (by mDiyo)
CodeChickenCore (by chicken_bones)
CoFH Core (by TeamCoFH)
JourneyMap (by techbrew)
Inventory Tweaks (by Kobata)
Thermal Foundation (by TeamCoFH)
Jabba (by ProfMobius)
Waila Harvestability (by squeek502)
NEI Addons (by bdew)
NEI Integration (by tonius111)
Applied Energistics 2 (by AlgorithmX2)
TiC Tooltips (by squeek502)
Thermal Dynamics (by TeamCoFH)
AromaBackup (by Aroma1997)
Blood Magic (by WayofTime)
CoFHLib (by TeamCoFH)
Simply Jetpacks (by tonius111)
Iguanas Tinker Tweaks (by bonusboni)
NetherOres (by skyboy026)
Carpenter's Blocks (by Syntaxial)
OpenModsLib (by OpenMods)
OpenBlocks (by OpenMods)
ExtraTiC (by JeanGlassmaker)
Ender IO (by CrazyPants_MC)
ChickenChunks (by chicken_bones)
Solar Flux (by Nauktis)
Dense Ores (by RWTema)
Ender Storage (by chicken_bones)
RFTools (by McJty)
Morpheus (by quetzi)
Translocators (by chicken_bones)
ExtraCells2 (by DrummerMC)
iChunUtil (by iChun)
Morph (by iChun)
FastLeafDecay (by Olafskii)
ArmorStatusHUD (by bspkrs)
HelpFixer (by matthewprenger)
QmunityLib (by quetzi)
MobiusCore (by ProfMobius)
Blue Power (by quetzi)
MmmMmmMmmMmm (by bonusboni)
Warp Book (by panicnot42)
FoxLib (by KitsuneKihira)
Tails (by KitsuneKihira)
Extra Utilities (by RWTema)
Minefactory Reloaded (by skyboy026)
Chisel 2 (by TheCricket26)
WR-CBE-Universal (by chicken_bones)
MineTweaker3 (by StanH)
ModTweaker (by jaredlll08)
Guide-API (by TehNut)
Baubles (by azanor)
CompactStorage (by tattyseal)
Biomes Tweaker (by Zehir_)
Aroma1997Core (by Aroma1997)
Buildcraft (by CovertJaguar)
Waila (by ProfMobius)
Logistics Pipes (by RS485)
McJtyLib (by McJty)
Ex Nihilo (by Erasmus_Crowley)
Storage Drawers (by jaquadro)
NotEnoughItems (by chicken_bones)
Thermal Expansion (by TeamCoFH)

**Comment by Yulife** [comment]
That's a Minetweaker, not Modtweaker issue.
