### ISSUE TITLE
Don`t work ThermalExpansion - Fluid Transposer

### ISSUE THREAD

**Issue by Tsyklop** [jaredlll08/ModTweaker2#249]
![2015-09-26_15 53 54](https://cloud.githubusercontent.com/assets/6783568/10117644/dbff3b82-6466-11e5-8cbf-dc1831b9ee7f.png)

ModTweaker2-0.9.3, TE laset verion, 
Script:
`Transposer.addExtractRecipe(1000, <Railcraft:fluid.creosote.bucket>, <liquid:creosote>*1000, <minecraft:bucket>, 100);`

**Comment by jaredlll08** [comment]
This is user error.

**Comment by jaredlll08** [comment]
Also PLEASE do not post a picture of the error, give us the Minetweaker.log
file. This is a final warning.

**Comment by Tsyklop** [comment]
http://pastebin.com/GmYUjSwa

TE errors in the log no.

**Comment by jaredlll08** [comment]
This is user error. Your syntax is incorrect

**Comment by Tsyklop** [comment]
@jaredlll08 I copied the text from the wiki and it does not work either.

**Comment by Tsyklop** [comment]
@jaredlll08 It you have a problem ... even this does not work:
`mods.thermalexpansion.Transposer.addExtractRecipe(2000, <minecraft:leaves>, <liquid:water> * 50, <minecraft:stick>, 100);`

Although written in the wiki ..

Check again.

**Comment by Voidi** [comment]
@Tsyklop Your Example is for addExtractRecipe not addFillRecipe, they have a different Parameter Order.

**Comment by Tsyklop** [comment]
@Voidi I know .. I'm talking about what does not work "addExtractRecipe" which is even written in the wiki. So it's not my mistake ...

**Comment by jaredlll08** [comment]
Yes, but when you get an error saying "a method available, but none matches the parameters..." that means that there is a problem with your script.

**Comment by jaredlll08** [comment]
Yes, but when you get an error saying "a method available, but none matches the parameters..." that means that there is a problem with your script.

**Comment by Tsyklop** [comment]
@jaredlll08 Okey. look this: https://youtu.be/a8ljn8SDj5Q

**Comment by Voidi** [comment]
Assuming you don't you use not a Dev Build from the Jenkis server this our fault.
The Wiki was already updatet to reflect the changes in the upcoming version.
The old Signature is `addExtractRecipe(int energy, IItemStack input, IItemStack output, ILiquidStack liquid, int chance)`

**Comment by jaredlll08** [comment]
SEE @Yulife I TOLD YOU! DON'T UPDATE THE DOC FOR UNRELEASED VERSION! >:(

**Comment by Yulife** [comment]
It's just motivation for you to release 0.9.4 :wink:

**Comment by Tsyklop** [comment]
@Voidi send please the link to Jenkins

**Comment by Yulife** [comment]
Dude, didn't you read the [Bug Reporting Guidelines](https://github.com/jaredlll08/ModTweaker2/wiki/Bug-Reporting-Guidelines)?

**Comment by Tsyklop** [comment]
@Yulife read

**Comment by Yulife** [comment]
By the way, don't use Jenkin builds in modpacks.

**Comment by Tsyklop** [comment]
@Yulife Okey. Thx
