### ISSUE TITLE
Known issues on Build 7

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#25]
For @soundlogic2236 
These are the issues so far that I still experienced when using build 7 on jenkins:
~~**1:**
For some reason the commands that you added appear ingame sometimes and sometimes not. I have to restart the game if they don't appear.~~
**See Issue 7**

~~**2:**
Not really an issue but something I thought about.. what happens if you make an ItemMapping for and inside of the Lexica Botania (You suggested the Diamond Block) but the block already has an ItemMapping, [like this](https://i.imgur.com/AeqatMk.png), in the minecraft wiki? Will test tomorrow.
*EDIT:* Did some testing today. It indeed does not overwrite the wiki feature of Botania and will not appear. Removing the ItemMapping doesn't function either.~~
**Partly Not Possible**

~~**3:**
Botania's Knowledge Levels still do not work. 
Using [this script](http://paste.ee/p/FBDzW) I still get an [error](http://paste.ee/p/WN99A).~~
**Fixed**

~~**4:**
If I use a fuzzy wildcard in, for example, an Alchemy recipe, using <minecraft:sandstone:*> it does not cycle through all the types of sandstone inside of the Lexica. However, it does in **NEI** if I implement the the crafting using old Modtweaker methods.~~ 
**Not Possible**

~~**5:** 
Just a reminder as you know this already, the Lexicon Index Category does not work. No one tell her!~~
**Fixed**

This shall be continued.

**Comment by Yulife** [comment]
Alright, tested a bit more stuff:

**6:**
ItemMapping removal does not work.
[Proof](https://i.imgur.com/Li6huGH.png)
[Script](http://paste.ee/p/cRGAe)

**7:**
For some reason your recently added commands dissapear from /mt help and do not work if typed either.

**Comment by Yulife** [comment]
Updated issue **2**

**Comment by soundlogic2236** [comment]
1) I will look into this
2) That might actually overlap with issue 6
3) That... looks like a compile error? Maybe? I'll check that out.
4) For the lexica recipes you list the recipes and it cycles through them. It doesn't automatically handle wildcards, but it can handle things that wildcards can't (for example, a page can cycle through the ways to make a wand of the forest, even though those are all separate recipes)
5) Glad you caught that before vazkii did
6) Could you check if it works for links inside the lexica? It might be that the in world lookups aren't being synced properly
7) Is this issue 1 with more detail? And is that then a general minetweaker issue?

**Comment by Yulife** [comment]
Oops, 2) and 7) are kinda duplicates, haha. 

Seems like Knowledge Levels, commands after reload and ItemMapping are the only issues right now. Will test the ItemMapping in the book once I come back from gym =]

**Comment by Yulife** [comment]
Updated OP and continuation.

**Comment by joshiejack** [comment]
Yeah 2/7 it's a minetweaker issue. Stan said the commands need to be readded on reload, but I don't know if he added an event/whatever for that.

**Comment by Yulife** [comment]
Moved to here: https://github.com/jaredlll08/ModTweaker2/issues/34
