### ISSUE TITLE
Trying to change the golem core recipe, what am I doing wrong?

### ISSUE THREAD

**Issue by Sunconure11** [jaredlll08/ModTweaker2#250]
This recipe does not appear to be broken, but, how do I get it to show up on the appropriate page?

http://pastebin.com/wriJZ7iy

Format became derpy as soon as I put it in pastebin.

**Comment by Sunconure11** [comment]
I think I see what I'm doing wrong. I'll open this up if I cannot figure it out.

**Comment by Sunconure11** [comment]
Okay, what am I doing wrong now?

**Comment by Sunconure11** [comment]
http://pastebin.com/f7MigS7D

**Comment by Sunconure11** [comment]
I cannot see the new recipe in the desired page. Did I forget to do something?

**Comment by Sunconure11** [comment]
Recipe works, it just does not show up on the page.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/uhq4lf7sl87j5nu/Screenshot%202015-09-26%2018.25.48.png?dl=0

https://www.dropbox.com/s/2wn5y90w0cvll19/Screenshot%202015-09-26%2018.26.18.png?dl=0

**Comment by Sunconure11** [comment]
asfawrfwafcawsfc

im so dumb

**Comment by Yulife** [comment]
You did nothing wrong. The Thaumonicon just doesn't sync with modified recipes like the Lexica Botania does.

**Comment by Yulife** [comment]
Huh, it's fixed now? :grin:

**Comment by Sunconure11** [comment]
Yeah, that got fixed, but, I'm having a hard time seeing what I did wrong with this infusion recipe:

mods.thaumcraft.Infusion.addRecipe(ROD_NECROMANCER_staff", <Thaumcraft:WandRod:57>, [<ThaumicExploration:pureZombieBrain>, <minecraft:bone>, <minecraft:bone>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:skull:1>], "auram 8, mortuus 32, perditio 16, spiritus 16", <ThaumicExploration:necroStaffCore> * 1, 5);

**Comment by Sunconure11** [comment]
It seems some characters do not show up properly in the comments.

**Comment by Sunconure11** [comment]
http://pastebin.com/ZS7mSmDu

**Comment by Sunconure11** [comment]
Figured it out. Nyeh.

**Comment by Yulife** [comment]
You need to apply blockcode formatting if you post issues on Github ;:)
