### ISSUE TITLE
Rock Crusher recipes not respecting subitems

### ISSUE THREAD

**Issue by IdleMuse** [jaredlll08/ModTweaker2#251]
When creating recipes for the Rock Crusher (Railcraft), it doesn't respect different recipes for different subitems. Example:

<mod:GenericItem:1> -> <minecraft:stick>
<mod:GenericItem:2> -> <minecraft:cobble>

Result: both items produce stick. Swapping them around in the script means both produce cobble.

(This may be a bug with the Rock Crusher, not ModTweaker, because the recipes show up correctly in NEI).

**Comment by Voidi** [comment]
We need the script, Forge and Minetweaker log, not as embedded quote, but rather linkend via something like pastebin.
And are you aware that the Rockcrusher handler has a parameter to ignore Metadata?
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Railcraft_Support

**Comment by IdleMuse** [comment]
> And are you aware that the Rockcrusher handler has a parameter to ignore Metadata?
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Railcraft_Support

Yes, the behaviour is identical irrelevant of that setting.

Here is the .zs file in question: http://sprunge.us/HKjV ; the problem lines are the ones which are currently commented out.

Will generate some clean logs on a reduced install.

**Comment by Bunsan** [comment]
Yes you have the matchDamage set to false in that script. So it is ignoring the meta data value. Use:
`mods.railcraft.RockCrusher.addRecipe(<Railcraft:ore:7>, true, false, [<RotaryCraft:rotarycraft_item_extracts:25>, <minecraft:cobblestone>, <minecraft:gravel>], [0.2, 0.1, 1]);`

**Comment by IdleMuse** [comment]
> matchDamage

Ah, I had stupidly set matchNBT to true, not matchDamage. Works as intended now, many thanks!

**Comment by Yulife** [comment]
@Voidi why is Meta and NBT a boolean btw? :P Isn't this handled in IIngredient or is that not compatible with RC fully?

**Comment by Voidi** [comment]
@Yulife Because the ZenScript method Reflect the Railcraft-Api, where there are these two additional parameter.
But i will simplyfie this like I made it for the Cokeoven.
