### ISSUE TITLE
Crash with Forestry 4.0

### ISSUE THREAD

**Issue by Filvandrel** [jaredlll08/ModTweaker2#252]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 27.09.15 17:02
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: forestry/core/utils/ShapedRecipeCustom
at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
at net.minecraft.client.Minecraft.func_71384_a(Unknown Source)
at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: forestry/core/utils/ShapedRecipeCustom
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
at java.lang.Class.privateGetPublicMethods(Unknown Source)
at java.lang.Class.getMethods(Unknown Source)
at stanhebben.zenscript.type.ZenTypeNative.complete(ZenTypeNative.java:157)
at minetweaker.runtime.GlobalRegistry.registerNativeClass(GlobalRegistry.java:95)
at minetweaker.MineTweakerAPI.registerClass(MineTweakerAPI.java:340)
at modtweaker2.mods.forestry.Forestry.(Forestry.java:17)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at modtweaker2.utils.TweakerPlugin.load(TweakerPlugin.java:18)
at modtweaker2.utils.TweakerPlugin.register(TweakerPlugin.java:12)
at modtweaker2.ModTweaker2.init(ModTweaker2.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
... 10 more
Caused by: java.lang.ClassNotFoundException: forestry.core.utils.ShapedRecipeCustom
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 52 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 398146168 bytes (379 MB) / 1178595328 bytes (1123 MB) up to 9650569216 bytes (9203 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn125M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 173 mods loaded, 173 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHI mcp{9.05} Minecraft Coder Pack 
UCHI FML{7.10.99.99} Forge Mod Loader 
UCHI Forge{10.13.4.1492} Minecraft Forge 
UCHI appliedenergistics2-core{rv2-stable-10} AppliedEnergistics2 Core 
UCHI CodeChickenCore{1.0.6.43} CodeChicken Core 
UCHI ivtoolkit{IvToolkit} 1.2 
UCHI Micdoodlecore{} Micdoodle8 Core 
UCHI NotEnoughItems{1.0.4.107} Not Enough Items 
UCHI OpenComputers|Core{1.5.18.36} OpenComputers (Core) 
UCHI technomCore{0.12.0A} Technomancy Core 
UCHI ThaumicTinkerer-preloader{0.1} Thaumic Tinkerer Core 
UCHI WitchingGadgetsCore{1.1.9} Witching Gadgets Core 
UCHI OpenModsCore{0.8} OpenModsCore 
UCHI {000} CoFH ASM 
UCHI {0} DragonAPI ASM Data Initialization 
UCHI debug{1.0} debug 
UCHI battlegear2{1.7.10} Mine & Blade Battlegear 2 - Bullseye 
UCHI bspkrsCore{6.15} bspkrsCore 
UCHI ArmorStatusHUD{1.28} ArmorStatusHUD 
UCHI StatusEffectHUD{1.27} StatusEffectHUD 
UCHI Baubles{1.0.1.10} Baubles 
UCHI adventurebackpack{1.7.10-0.8b} Adventure Backpack 
UCHI AgriCraft{1.7.10-1.4.0-beta-3} AgriCraft 
UCHI AncientWarfare{2.4.112-beta-MC1.7.10} Ancient Warfare Core 
UCHI CoFHCore{1.7.10R3.0.3} CoFH Core 
UCHI BuildCraft|Core{7.0.25} BuildCraft 
UCHI AncientWarfareAutomation{2.4.112-beta-MC1.7.10} Ancient Warfare Automation 
UCHI AncientWarfareNEIPlugin{2.4.112-beta-MC1.7.10} Ancient Warfare NEI Plugin 
UCHI AncientWarfareNpc{2.4.112-beta-MC1.7.10} Ancient Warfare NPCs 
UCHI AncientWarfareStructure{2.4.112-beta-MC1.7.10} Ancient Warfare Structures 
UCHI appliedenergistics2{rv2-stable-10} Applied Energistics 2 
UCHI AquaTweaks{1.0} AquaTweaks 
UCHI asielib{0.4.2} asielib 
UCHI ATG{0.10.0} Alternate Terrain Generation 
UCHI MineFactoryReloaded{1.7.10R2.8.0} MineFactory Reloaded 
UCHI Thaumcraft{4.2.3.5} Thaumcraft 
UCHI MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} MFR Compat: Thaumcraft 
UCHI Waila{1.5.10} Waila 
UCHI Automagy{0.26.3} Automagy 
UCHI betterstorage{0.13.1.126} BetterStorage 
UCHI BiblioCraft{1.11.2} BiblioCraft 
UCHI ThermalFoundation{1.7.10R1.2.0} Thermal Foundation 
UCHI ThermalExpansion{1.7.10R4.0.3B1} Thermal Expansion 
UCHI BigReactors{0.4.3A} Big Reactors 
UCHI Mantle{1.7.10-0.3.2.jenkins188} Mantle 
UCHI Natura{2.2.0} Natura 
UCHI BiomesOPlenty{2.1.0} Biomes O' Plenty 
UCHI AWWayofTime{v1.3.3} Blood Magic: Alchemical Wizardry 
UCHI qmunitylib{1.0} QmunityLib 
UCHI bluepower{0.2.962} Blue Power 
UCHI Botania{r1.7-223} Botania 
UCHI BuildCraft|Builders{7.0.25} BC Builders 
UCHI BuildCraft|Transport{7.0.25} BC Transport 
UCHI BuildCraft|Energy{7.0.25} BC Energy 
UCHI BuildCraft|Silicon{7.0.25} BC Silicon 
UCHI BuildCraft|Robotics{7.0.25} BC Robotics 
UCHI BuildCraft|Factory{7.0.25} BC Factory 
UCHI IC2{2.2.763-experimental} IndustrialCraft 2 
UCHI Forestry{4.0.0.27} Forestry for Minecraft 
UCHI BuildCraft|Compat{7.0.12} BuildCraft Compat 
UCHI CarpentersBlocks{3.3.7} Carpenter's Blocks 
UCHI ChickenChunks{1.3.4.17} ChickenChunks 
UCHI Railcraft{9.7.0.0} Railcraft 
UCHI TwilightForest{2.3.7} The Twilight Forest 
UCHI UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} Universal Electricity 
UCHI ForgeMultipart{1.2.0.345} Forge Multipart 
UCHI chisel{2.5.1.44} Chisel 2 
UCHI ComputerCraft{1.74} ComputerCraft 
UCHI Mystcraft{0.12.3.00} Mystcraft 
UCHI ExtraUtilities{1.2.11} Extra Utilities 
UCHI ImmersiveEngineering{0.5.4} Immersive Engineering 
UCHI TConstruct{1.7.10-1.8.7.build979} Tinkers' Construct 
UCHI DragonAPI{1.0} DragonAPI 
UCHI eplus{1.7.10-3.0.1} Enchanting Plus 
UCHI endercore{1.7.10-0.1.0.24_beta} EnderCore 
UCHI EnderIO{1.7.10-2.3.0.415_beta} Ender IO 
UCHI EnderStorage{1.4.7.36} EnderStorage 
UCHI ExtraTiC{1.4.5} ExtraTiC 
UCHI factorization.notify{1.0} Factorization Notification System 
UCHI factorization.dimensionalSlice{0.8.95} Factorization Dimensional Slices 
UCHI factorization{0.8.95} Factorization 
UCHI factorization.misc{0.8.95} Factorization Miscellaneous Nonsense 
UCHI farseek{1.0.9} Farseek 
UCHI FastCraft{1.21} FastCraft 
UCHI Steamcraft{0.28.10} Flaxbeard's Steam Power 
UCHI GalacticraftCore{3.0.12} Galacticraft Core 
UCHI GalacticraftMars{3.0.12} Galacticraft Planets 
UCHI GraviSuite{1.7.10-2.0.3} Graviation Suite 
UCHI Growthcraft{2.1.0a} Growthcraft 
UCHI Growthcraft|Cellar{2.1.0a} Growthcraft Cellar 
UCHI Growthcraft|Apples{2.1.0} Growthcraft Apples 
UCHI Growthcraft|Bamboo{2.1.0} Growthcraft Bamboo 
UCHI Growthcraft|Bees{2.1.0} Growthcraft Bees 
UCHI Growthcraft|Fishtrap{2.1.0a} Growthcraft Fishtrap 
UCHI Growthcraft|Grapes{2.1.0} Growthcraft Grapes 
UCHI Growthcraft|Hops{2.1.0} Growthcraft Hops 
UCHI Growthcraft|Rice{2.1.0a} Growthcraft Rice 
UCHI guideapi{1.7.10-1.0.1-20} Guide-API 
UCHI IC2NuclearControl{2.2.5a-GoingForTheKill} Nuclear Control 2 
UCHI immersiveintegration{0.5.4} Immersive Integration 
UCHI inventorytweaks{1.58-147-645ca10} Inventory Tweaks 
UCHI IronChest{6.0.62.742} Iron Chest 
UCHI JABBA{1.2.1} JABBA 
UCHI journeymap{@JMVERSION@} JourneyMap 
UCHI magicalcrops{1.7.2 - 0.1 ALPHA} Magical Crops 
UCHI malisiscore{1.7.10-0.12.9} MalisisCore 
UCHI malisisdoors{1.7.10-1.10} Malisis' Doors 
UCHI Mekanism{8.1.7} Mekanism 
UCHI MekanismGenerators{8.1.7} MekanismGenerators 
UCHI MekanismTools{8.1.7} MekanismTools 
UCHI ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} Resonant Engine 
UCHI MFFS{@MAJOR@.@MINOR@.@REVIS@} Modular Force Field System 
UCHI MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} MFR Compat: Applied Energistics 
UCHI MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} MFR Compat: Atum 
UCHI MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} MFR Compat: BackTools 
UCHI MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} MFR Compat: BuildCraft 
UCHI MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} MFR Compat: Chococraft 
UCHI MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} MFR Compat: ExtraBiomes 
UCHI MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} MFR Compat: Forestry 
UCHI MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} MFR Compat: ForgeMicroblock 
UCHI MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} MFR Compat: IC2 
UCHI MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} MFR Compat: Mystcraft 
UCHI MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} MFR Compat ProjectRed 
UCHI MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} MFR Compat: Railcraft 
UCHI MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} MFR Compat: Sufficient Biomes 
UCHI MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} MFR Compat: Thermal Expansion
UCHI MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} MFR Compat: Tinkers' Construct 
UCHI MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} MFR Compat: TwilightForest 
UCHI MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} MFR Compat: Vanilla 
UCHI MineFactoryReloaded|CompatMagicalCrops{1.0beta} MFR Compat: MagicalCrops 
UCHI MineTweaker3{3.0.9B} MineTweaker 3 
UCHI testdummy{1.0} MmmMmmMmmMmm 
UCHE modtweaker2{0.9.2} Mod Tweaker 2 
UCHI NEIPlugins{1.1.0.11-unofficial} NEI Plugins Unofficial 
UCHI NetherOres{1.7.10R2.3.1RC1} Nether Ores 
UCHI OpenMods{0.8} OpenMods 
UCHI OpenBlocks{1.4.4} OpenBlocks 
UCHI OpenComputers{1.5.18.36} OpenComputers 
UCHI openglasses{1.0.43} OC Glasses 
UCHI openmodularturrets{2.1.4-183} Open Modular Turrets 
UCHI PneumaticCraft{1.11.11-133} PneumaticCraft 
UCHI ProjectE{1.7.10-PE1.9.2} ProjectE 
UCHI quiverchevsky{b100} QuiverBow 
UCHI RedstoneArsenal{1.7.10R1.1.1} Redstone Arsenal 
UCHI RotaryCraft{1.0} RotaryCraft 
UCHI SGCraft{1.9.0} Greg's SG Craft 
UCHI StevesCarts{2.0.0.b18} Steve's Carts 2 
UCHI StevesFactoryManager{A93} Steve's Factory Manager 
UCHI StorageDrawers{1.7.10-1.6.2} Storage Drawers 
UCHI streams{0.1.5} Streams 
UCHI thaumcraftneiplugin{1.7.10-1.6a} Thaumcraft NEI Plugin 
UCHI thaumicenergistics{0.8.10.10} Thaumic Energistics 
UCHI ThaumicTinkerer{unspecified} Thaumic Tinkerer 
UCHI ThaumicExploration{0.6.0} Thaumic Exploration 
UCHI ThaumicHorizons{1.1.5} Thaumic Horizons 
UCHI ThermalDynamics{1.7.10R1.1.0} Thermal Dynamics 
UCHI TiCTooltips{1.1.11b} TiC Tooltips 
UCHI TMechworks{0.2.14.100} Tinkers' Mechworks 
UCHI Translocator{1.1.1.14} Translocator 
UCHI TravellersGear{1.16.5} Traveller's Gear 
UCHI witchery{0.24.1} Witchery 
UCHI WitchingGadgets{1.1.9} Witching Gadgets 
UCHI WR-CBE|Core{1.4.1.9} WR-CBE Core 
UCHI WR-CBE|Addons{1.4.1.9} WR-CBE Addons 
UCHI WR-CBE|Logic{1.4.1.9} WR-CBE Logic 
UCHI yegamolchattels{1.1.2} Ye Gamol Chattels 
UCHI McMultipart{1.2.0.345} Minecraft Multipart Plugin 
UCHI MrTJPCoreMod{1.1.0.31} MrTJPCore 
UCHI aobd{2.8.3} Another One Bites The Dust 
UCHI denseores{1.0} Dense Ores 
UCHI IguanaTweaksTConstruct{1.7.10-2.1.5.140} Iguana Tinker Tweaks 
UCHI technom{0.12.0A} Technomancy 
UCHI ForgeMicroblock{1.2.0.345} Forge Microblocks 
GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon R9 200 Series'
OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
Class transformer null safety: all safe
CoFHCore: -[1.7.10]3.0.3-303
AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
MineFactoryReloaded: -[1.7.10]2.8.0-104
ThermalFoundation: -[1.7.10]1.2.0-102
ThermalExpansion: -[1.7.10]4.0.3B1-218
Mantle Environment: Environment healthy.
TConstruct Environment: Environment healthy.
NetherOres: -[1.7.10]2.3.1RC1-18
RedstoneArsenal: -[1.7.10]1.1.1-89
ThermalDynamics: -[1.7.10]1.1.0-161
EnderIO: Found the following problem(s) with your installation: "An unsupportted old RF API is installed (1.7.10R1.0.1 from Railcraft_1.7.10-9.7.0.0.jar). Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
Stencil buffer state: Function set: GL30, pool: forge, bits: 8

**Comment by Yulife** [comment]
Are you using a script that uses Forestry MT Support?

**Comment by Manuepolis23** [comment]
i have this problem too and no script that uses forestry mt support

**Comment by Voidi** [comment]
It seemes they changed something with the internal recipe handling.
I will check this.

**Comment by AnodeCathode** [comment]
Lot of classname and container renaming:
https://github.com/jaredlll08/ModTweaker2/pull/255

**Comment by Voidi** [comment]
If anybody want to test https://github.com/Voidi/ModTweaker2/releases/tag/0.9.5

**Comment by Haggle1996** [comment]
Does this make this update of ModTweaker incompatible with Forestry <4.x?

**Comment by Voidi** [comment]
@Haggle1996 yes
The Last Version which supports Forestry 3.* is Modtweaker2 0.9.4

**Comment by Iarinu** [comment]
I've tried with your version 2.0.9.4 and now the client crashes because something else.
CrashReport: http://0wx.org/addc4b48005ed8521c8120d6bec43a3c/
