### ISSUE TITLE
Error with Forestry 4.03 and latest repo build of MT2 - NoClassDefFoundError

### ISSUE THREAD

**Issue by AnodeCathode** [jaredlll08/ModTweaker2#254]
MineTweaker.log: http://pastebin.com/tHmGBguX

Using Forestry 4.0.3
minetweaker3-1.7.10-3.0.10b
modtweaker2 built from repo at:
https://github.com/jaredlll08/ModTweaker2/commit/b45ff6ad01fbc75c0be24cc7ce9ba2a736f50315

Edit: deleted the openeye link, realize that's the data from the https://github.com/jaredlll08/ModTweaker2/issues/252 issue.

**Comment by AnodeCathode** [comment]
Bah, realize it's the same error as https://github.com/jaredlll08/ModTweaker2/issues/252

Thought the commits were a fix for this issue.

**Comment by Yulife** [comment]
Uhhhh, #252? Why did you reopen?

**Comment by AnodeCathode** [comment]
Because this is not the same error as 252. The server loads and then we get a script error on recipe.remove.

**Comment by AnodeCathode** [comment]
Covered under the general Forestry 4.0.x is broken topic. Should be fixed with:

https://github.com/jaredlll08/ModTweaker2/pull/255
