### ISSUE TITLE
TCon seared stone is not registered with the right name

### ISSUE THREAD

**Issue by EfficiencyVI** [jaredlll08/ModTweaker2#256]
I'm not 100 % sure if this is a bug (here or in TConstruct) or I'm just doing it wrong. I want to add a recipe for seared stone in the casting table. The problem is most fluids are registered as fluid.molten.type, so here fluid.molten.glass and then I can do something like this:

```
mods.tconstruct.Casting.addTableRecipe(<harvestcraft:bakewareItem>, <liquid:glass.molten> * 8000, <IguanaTweaksTConstruct:clayBucketFired>, true, 200);
```

But now the problem: stone is registered as molten.stone (so no fluid. ahead). How do I add a recipe on the TiCo table for seared stone?

**Comment by jaredlll08** [comment]
have you tried `<liquid:molten.stone>`?

**Comment by EfficiencyVI** [comment]
Yes:

```
mods.tconstruct.Casting.addTableRecipe(<harvestcraft:juicerItem>, <liquid:molten.stone> * 54, <minecraft:flower_pot>, true, 200);
```

results in:

```
[18:27:05] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:158]: MineTweaker: Loading Crafting.zs
[18:27:05] [Client thread/INFO]: [CHAT] ERROR: Crafting.zs:206: Could not resolve <liquid : molten . stone>
```

However this error message only appears one time and after that I don't get any error messages, but the recipe is also not added.

**Comment by UndeadZeratul** [comment]
I haven't had any issue with ```<liquid:stone.seared>```, does that work for you?

**Comment by Voidi** [comment]
the command /minetweaker liquids prints the name of registered Fluids to the log.

**Comment by EfficiencyVI** [comment]
Well then, `stone.seared` works. Maybe the "/minetweaker liquids" command should be mentioned on the wiki because not even google knew that. Thank you for your help!

**Comment by Dream-Master** [comment]
@EfficiencyVI 
You can add this to the WIFE by yourself. Only you need to be registered there.
