### ISSUE TITLE
witchery support (stub). i assume this is not possile atm due to no api?

### ISSUE THREAD

**Issue by trollworkout** [jaredlll08/ModTweaker2#259]
ill leave this as a stub but i am wondering if there is anything you can do to support witchery crafting esp cauldron crafting. or that's completely impossible?

**Comment by jaredlll08** [comment]
Completely impossible.

**Comment by Dream-Master** [comment]
Witchery not have any api. So it could be complicated or impossible.

**Comment by trollworkout** [comment]
yeah i think he was working on an api but whenever that's done who knows. may be possible in the near future thought. i have hope.

**Comment by Dream-Master** [comment]
Not for 1.7.10 I think.

**Comment by trollworkout** [comment]
honestly he doesn't want his mod to be open and he doesn't want people to deobfuscate or reverse engineer his code . is probably really easy but he said that he likes to keep his mod as closed as possible. i think it may never be possible . :/
