### ISSUE TITLE
modtweaker 2 0.9.4 (thaumcraft aspects component) does not work in multiplayer (lan or server)

### ISSUE THREAD

**Issue by trollworkout** [jaredlll08/ModTweaker2#261]
edit: this  bug is confirmed (by me right now see my last post)

BUG: modtweaker 2 thaumcraft aspect component does not work for multiplayer  clients
DESIRED EFFECT: any thaumcraft aspects added in script should show in multiplayer game
ACTUAL EFFECT: any  thaumcraft aspects set in script do NOT show up for multiplayer clients  although script runs successfully and it seems in LAN multiplayer only the serving computer sees the script aspects
REPRODUCIBLE: always

my initial assumption is maybe thaumcraft api may be out of date hasn't been updated in 9 months. 

I have a setup with my friend using a modpack of 26 mods and I use minetweaker 3 + modtweaker 2 to integrate everything.  i have thaumcraft installed and i have a file specifically for adding aspects to mod stuff. seems the script works in single player but in multiplayer is simply not loading as if the script doesn't exist. but strangely enough the minetweaker 3 script side works. only the modtweaker 2 thaumcraft aspects don't work.

ModTweaker2-0.9.3 + MineTweaker3-1.7.10-3.0.10
1.7.10-Forge10.13.4.1448

animalsPlus-1.2
Automagy-1.7.10-0.26.3
Baubles-1.7.10-1.0.1.10
BiblioCraft[v1.11.2][MC1.7.10]
CraftGuide-1.6.9.0-forge
DynamicLights-1.7.10
Et Futurum-1.4.4
fastcraft-1.21
Forbidden Magic-1.7.10-0.57
Forge_GuiLibv1.0.7.2 (used by MSC2)
forge-1.7.10-10.13.4.1448-1.7.10-installer
growthcraft-2.2.2-complete
LevelUp!-0.10(1.7.10)
MineTweaker3-1.7.10-3.0.10
ModTweaker2-0.9.3
MSC2
mystcraft-1.7.10-0.12.3.00
OptiFine_1.7.10_HD_U_C1
Ruins-1.7.10
SoundFilters-0.8_for_1.7.X
Thaumcraft-1.7.10-4.2.3.5
TheErebus-0.3a
twilightforest-1.7.10-2.3.7
weaponmod-1.14.3
Wild-Caves-Mod-1.7.10
witchery-1.7.10-0.24.1

the scripts are in  minecraft/scripts
tweaks.zs  <- this works everywhere
aspects.zs <- this one only works locally  (thaumcraft aspects)

i have this in a script
mods.thaumcraft.Aspects.set(<minecraft:fence>, "arbor 1");

i copy that script and give it to my friend he is serving . i  have same script + same mods and same   everything. 

am i missing something?? should i put the script in the world rather than in minecraft/scripts ?

**Comment by Yulife** [comment]
Could you please give a log?

**Comment by trollworkout** [comment]
yes. is pretty lengthy.

http://pastebin.com/MwdCx9EF

 i will give you my single player one. i will have to get the multiplayer from my friend.but is identical same game, same versions, same script in the same folder.

**Comment by Yulife** [comment]
Are you sure the host of the world has the script in his minecraft/scripts directory? What happens if the host does /mt reload? Is the TC4 part affected?

**Comment by trollworkout** [comment]
100% he has the scripts. i made a mistake on one recipe and i modified a vanilla recipe and he noticed right away. and i had to fix it and re-upload and tested it and worked fine. then i noticed all the aspects i added in my single player test world are not available in multiplayer.

**Comment by trollworkout** [comment]
seems to me only minetweaker 3 recipes work on multipalyer

**Comment by jaredlll08** [comment]
minetweaker.log file please

**Comment by trollworkout** [comment]
see the pastebin link above that's the minetweaker log

**Comment by Voidi** [comment]
Please read our guidelines https://github.com/jaredlll08/ModTweaker2/blob/master/contributing.md.
In case of doubt we need all logs, Minetweaker and Minecraft log from Client and Server.

**Comment by trollworkout** [comment]
hmm. ill see what i can do . this is regarding thaumcraft aspects so it has to be installed in order to test. i need 2 computers running to see if i can reproduce this. 

is odd that same script works single player but not lan multiplayer.

**Comment by Voidi** [comment]
you can run dedicated server and client on the machine

**Comment by trollworkout** [comment]
the thing is it has to be a LAN specifically. might work on a server but maybe the issue is open LAN network multiplayer specific . no?

**Comment by trollworkout** [comment]
i have another computer here kinda old but maybe might work. i will try to see i f i can get some testing done.

**Comment by Voidi** [comment]
why should the Netweork connection make any difference? as far as i know Minetweaker didn't anything with networking itself, everything is done via Minecraft

**Comment by trollworkout** [comment]
i am gonna get a bit of setup done and i will confirm with you guys shortly

**Comment by jaredlll08** [comment]
You could just open to minecraft instances...

**Comment by trollworkout** [comment]
ah yea?? how do i do that?

**Comment by trollworkout** [comment]
open -n /Applications/ApplicationName.app  EZ

**Comment by trollworkout** [comment]
seems i cannot use my own username to join my own game haha name is already taken :)

**Comment by trollworkout** [comment]
just did a lil hack went offline and  modified my displayedUsername to a bogus name in profiles json and used open -n /Applications/Minecraft.app  play offine.  i connected to myself via lan on same computer.

i can confirm this is a bug. i can do this as many times as you want.

also it appears the serving computer has the aspects working fine but the connecting computer does not. minetweaker 2 seems to work only locally for server or anyone really.

**Comment by trollworkout** [comment]
here is proof 

i have the arbor knowledge for both players ..arbor being tree
i look trough serving computer lens right..says arbor 1
i look trough served (connecting) computer lens left...says Nothing can be learned from this

notice the setup file clearly says 
mods.thaumcraft.Aspects.set(<minecraft:fence>, "arbor 1");

conclusion: only serving computer sees the modtweaker 2 thaumcraft aspect settings via LAN direct connection

![screen shot 2015-10-13 at 7 17 33 am](https://cloud.githubusercontent.com/assets/6987027/10453498/8c06ae8c-717a-11e5-88c7-791be2f11ec5.png)

**Comment by trollworkout** [comment]
let me test this again.

**Comment by trollworkout** [comment]
ok disregard that. seems minetweaker is unable to load itself twice like all other mods. it only loads first time properly then it crashes with odd bizarre errors on any subsequent loads if you run it as a separate instance.  i need to test it on 2 different computers with different accounts.

**Comment by trollworkout** [comment]
so i did more testing and although i have no proof i can confirm yet again this behaviour is real.


i cannot test using two instances since minetweaker 3 crashes on second instance probably due to the way is scripted relfections and weird stuff . i don't know. so i HAVE to test it on two different computers  or server + computer situation.

i have done a few tests with my friend's computer and seems he sees the aspects fine but i don't.

from what i gather modtweaker 2 only works locally in multiplayer LAN and remotely it doesn't. minetweaker 3 works remotely fine and is loaded. this has to be  a modt2 issue. 

seems i can reproduce this behaviour every single time. two computers make a lan game. the serving computer sees all the thaumcraft aspects. the connecting computer does not. can someone else confirm and try to reproduce this?

**Comment by trollworkout** [comment]
i made a local forge server same version as the client same mods except i removed all client sided mods .

the aspects STILL don't show up in the game. the modtweaker 2 log says aspects have been added but nothing is there.

**Comment by trollworkout** [comment]
it doesn't work mutliplayer. i have done everything possible. placed the scripts under server/scripts/ placed them in server/world/scripts/ placed them in server/imcScripts/ . reduced the mods to 4. i am using the latest version ModTweaker2-0.9.4 . 

4 mods loaded. thaumcraft 4.2 (works) + minetweaker  3 (works!) + modtweaker 2 (only single player) + et futurum (works)

the scripts load fine is successful but in the game nothing happens no effect.  see attached  image. 

![screen shot 2015-10-14 at 8 50 38 pm](https://cloud.githubusercontent.com/assets/6987027/10502021/75fc13de-72b5-11e5-9cd7-68d2979197b7.png)

**Comment by trollworkout** [comment]
hey guy good news i managed to make it work using latest beta release of minetweaker 3 + latest release of modtweaker 2. i was using the release ...3.10 this mod only works with ..3.10B of minetweaker 3.

**Comment by trollworkout** [comment]
@Voidi  it still doesn't work o LAN but only on server
