### ISSUE TITLE
IngredientStacks funky logging

### ISSUE THREAD

**Issue by mmelvin0** [jaredlll08/ModTweaker2#262]
I noticed you did some cleanup on how items get logged. When I have a stack of multiple items (e.g. `<ore:ingotCopper> * 3`, it logs as such: `minetweaker.api.item.IngredientStack@65d292c`.

This is a very minor issue of course, mainly just a note for myself so I can submit a pull request when I have some time.

**Comment by Voidi** [comment]
as a note: IOreDictEntry need to override toString()

**Comment by jaredlll08** [comment]
This isn't an issue for us, it is more an issue for minetweaker.
