### ISSUE TITLE
ModTweaker issue with Thermal Expansion

### ISSUE THREAD

**Issue by helkarakse** [jaredlll08/ModTweaker2#263]
I'm running a server on the Beyond Reality Divergence mod pack, and this is running Minetweaker 3.0.9C and ModTweaker 0.9.4. This server is also running KCauldron 1481.148. The issue is only repeatable on my server and is not repeatable on a local installation. I have tested this issue with forge 1448, forge 1481, and on KCauldron 1481.148 (albeit all with fresh worlds) and there is no issue.

Process:
1. On my server, when I restart it or start it, any recipes that use the ModTweaker method of addition or removal (ie, with BC Assembly Tables or Botania Altars) do not work. There is no error log in latest.log, or in fml-server-latest.log, and there is no information in minetweaker.log. There is also no error on the client side log until I progress to the next step which is
2. Running ./mt reload. When I run ./mt reload, I immediately get client side only errors as seen here: http://i.imgur.com/qXBjUWw.png (server side: http://i.imgur.com/3c6G2BG.png). Assembly table recipes and botania altar recipes immediately begin to work, but now, I'm missing a huge chunk of pulverizer (thermal expansion) related recipes as seen here:
- server's thermal expansion recipe list: http://pastebin.com/THmJTVkJ (2595 lines)
- actual thermal expansion recipe list taken from forge installation: http://pastebin.com/0GRRfypM (2770 lines)

So between the two files I'm missing about 175 lines of thermal expansion recipes. So far, this issue appears to only affect Thermal Expansion.

Edit: It appears that I am also missing the Thermal Expansion recipes from server start onwards, despite no errors in logs.

Edit: I have also tested this with Minetweaker 3.0.10B to no avail. It still has the same result.

**Comment by Voidi** [comment]
With local installation you mean single player or dedicated server on your machine?
As i don't understand this exact: can you reproduce this when you run your server with forge(only)?

**Comment by helkarakse** [comment]
I cannot reproduce this issue with forge or with KCauldron locally. I can reproduce this issue with forge and with KCauldron on the dedicated server.

**Comment by Voidi** [comment]
This Cache theory sounds weird (where did they should save this?) but maybe that's how it is, i don't know anything about KCauldron.
Could you try to create a new Minecraft instance of your server/modpack? copying only the mods, scripts and relevant config, if the cached some via file, it should work.

**Comment by helkarakse** [comment]
That is the thing. I already tested this without the world file and it works. This issue is only specific to the remote server. Downloading the world file without some sort of indicator as to the root problem is not going to be doable as the world is very much larger.

**Comment by Voidi** [comment]
Another thing: make sure you have not Scripts in the world-specific directory.
Aside from that, i don't know how this could related directly to Mine/Modtweaker, they don't cache like that.

**Comment by helkarakse** [comment]
Yeah I checked that there were no scripts in the world specific directory. The only scripts are in the ./scripts folder. Anyway, this issue is just here in case someone else ever has the same issue. I have found a workaround by re-adding the missing recipes manually in a separate minetweaker file.
