### ISSUE TITLE
TiCon Entity Smelting

### ISSUE THREAD

**Issue by Durpady** [jaredlll08/ModTweaker2#264]
Tinker's Construct allows you to pull certain fluids from entities when they expire inside the Smeltery.  Could you perhaps add a way for us to tweak this?  Allow us to, say, extract Lava from a Spider?

**Comment by Voidi** [comment]
not possible

**Comment by Yulife** [comment]
Why? Couldn't you use strings for the entities?

**Comment by jaredlll08** [comment]
There is no handler for it

**Comment by Voidi** [comment]
It's hardcoded https://github.com/SlimeKnights/TinkersConstruct/blob/ac202c3a17be7491b583ad9d21ee39b7b54a51ad/src/main/java/tconstruct/smeltery/logic/SmelteryLogic.java#L324
