### ISSUE TITLE
Thermal Expansion Induction Smelter requiring IItemStacks intead of IIngredients

### ISSUE THREAD

**Issue by TheTrueForce** [jaredlll08/ModTweaker2#265]
Hi,

I'm trying to override the recipes for IC2 refined Iron in the T-Ex induction Smelter, and make them return Mekanism Steel Ingots. The recipes themselves are mostly fine, the output is all I'm trying to change. I'm using this command in my script(I've imported the relevant class):

Smelter.addRecipe(8000, <Mekanism:OtherDust:1>, <ore:dustCoal> * 2, <Mekanism:Ingot:4>);

Trouble is, the * 2 in the 3rd argument means that that is an IIngredient, and Smelter.addRecipe calls for an IItemstack there. I'm getting this error:
ERROR: oreBlocks.zs:191 > 2 methods available but none matches the parameters (int, minetweaker.item.IItemStack, minetweaker.item.IIngredient, minetweaker.item.IItemStack)

Could you please rectify this? Or tell me where I've messed up, either's good.
Thanks.

**Comment by Voidi** [comment]
The Induction Smelter (like a lot of other methods from mods) doesn't support OreDict so only IItemStacks are used as parameters.

@Yulife see you people will ask, because they don't know the parameter types.

**Comment by TheTrueForce** [comment]
Hang on a moment, here. Why do you say that the induction smelter doesn't support oreDict? I can see in the game that it's using dustCoal in the pre-existing recipes. (At least, it certainly looks like it.)
I do apologise for not doing my homework properly, but my point still stands. Can you please make the ModTweaker Induction Smelter handler allow the use of IIngredients in the input areas?

**Comment by jaredlll08** [comment]
There is a big difference between what we allow you to do, and what TE allows you to do, I am sure there is a reason for no oredict support, but I cannot remember it, but the machine does support oredict, our handler however does not.

**Comment by Voidi** [comment]
The functions to add OreDict recipes only work for Ore Processing.

**Comment by TheTrueForce** [comment]
Thank you Jared, for your clear reply. I daresay I can write a small mod that adds the recipes(I think I know how), but I'd much prefer to script it. Still, you say there's a reason behind it, so it's no biggie.

**Comment by Zixxl** [comment]
I think Thermal Expansion has build in oreDict support. If you add recipies with an item which is listed in the ore dictionary, than other items should also work.
