### ISSUE TITLE
Support Suggestions: Buildcraft & EnderIO

### ISSUE THREAD

**Issue by fishmealx** [jaredlll08/ModTweaker2#268]
Buildcraft: Assembly Table
EnderIO: Alloy Smelter, Enchanter

**Comment by fishmealx** [comment]
I realized there's assembly table support, but EnderIO? No?

**Comment by Dream-Master** [comment]
EnderIo have own scripts for the machines where you can add or delete some recipes.

**Comment by Dream-Master** [comment]
As an Example 
AlloySmelterRecipes_User.xml
Here you can control all Alloy Smelter recipes.

**Comment by Dream-Master** [comment]
For the Enchanter using
EnchanterRecipes_User.xml

All files found in configs/enderio/

**Comment by Yulife** [comment]
Due to EnderIO having its own configuration ,support is very low priority currently :)

**Comment by Fortanono** [comment]
At the time this was a low priority, but FTB Tweaks doesn't work with configs/non-MT scripts, so I feel one should have the ability to work with FTB Tweaks and EIO.
