### ISSUE TITLE
Support Suggestion: Forestry bottler

### ISSUE THREAD

**Issue by fishmealx** [jaredlll08/ModTweaker2#269]
and maybe for right clicking fluids with jars/bottles/buckets?

**Comment by Voidi** [comment]
What specific support do you suggest? What type of Recipe do you want to add.

**Comment by fishmealx** [comment]
Hm. I just assumed it wouldn't work for non-Forestry after it didn't do one specific thing I was trying, sorry. I can play with it a bit more.
What didn't work: Making a BiomesOPlenty Honey jar out of Forestry liquid Honey. The jar can only hold like 2 different things.
Perhaps what I need to do is actually combine the ore dictionary entries for the liquids instead? Is that a thing? If not, that's my new suggestion. :P

**Comment by Voidi** [comment]
The Forestry bootler work only with registered Fluids and FluiContainers. I doubt that the BoP Jar is one.

**Comment by Yulife** [comment]
Well if I recall correctly @BluSunrize 's Bottling Machine only works with Fluid Containers too but he made Minetweaker support too :) May be wrong though.
