### ISSUE TITLE
Support Suggestion: Forestry/Gendustry Apiary

### ISSUE THREAD

**Issue by fishmealx** [jaredlll08/ModTweaker2#270]
That is, to adjust which species of bee drops what items at what % chance.
There's also Magic Bees and Extra bees if that's not too much of a stretch. NEI can display it all as %'s so I assume the capacity exists.

Thanks, of course. Sorry to keep making suggestions, especially some bad ones. I'm just getting carried away using this mod for everything.
I did try to see if it could be done with or without your mod this time. :P

**Comment by Voidi** [comment]
You mean the chances that bee queen produce specific items? Then is should be only forestry related.
This would be very interessting for pack makers.

**Comment by fishmealx** [comment]
Yes, that's what I mean. I'm making a pack, and it started with wanting to remove the honey drops and put in regular dye, but it would be pretty cool to be able to modify the chances of everything. The kind of princesses you get would be fun to modify too, if that is treated differently from the other outputs.

**Comment by Voidi** [comment]
I won't work on this (at least at the moment).
To complex.
