### ISSUE TITLE
[Bug][Chisel]

### ISSUE THREAD

**Issue by SHIuSH** [jaredlll08/ModTweaker2#272]
http://imgur.com/CsHcoUU
Command just don't work. Gives ERROR message in chat
tried with iron block: no messages in chat but this command still doesn't work

**Comment by jaredlll08** [comment]
This does not follow the rules.
https://github.com/jaredlll08/ModTweaker2/blob/master/CONTRIBUTING.md

**Comment by Yulife** [comment]
No need to close the issue. Just let him edit it, Jared.
