### ISSUE TITLE
[Not a Bug] Forestry Centrifuge add.Recipe

### ISSUE THREAD

**Issue by Dulciphi** [jaredlll08/ModTweaker2#273]
Possibly related to #205

On first attempt to make a new centrifuge recipe (simply using cut and paste from the [powerofbytes.com wiki](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Forestry_Support)):

mods.forestry.Centrifuge.addRecipe([<minecraft:leaves> % 200, <minecraft:stick> % 80, <Forestry:beeCombs> % 20], <minecraft:sapling>, 20);

That results in error: 2 methods available but none matches the parameters (minetweaker.item.WeightedItemStack[], minetweaker.item.IItemStack, int)

I notice the wiki says 
//Centrifuge
//OutputArray + %, Time in Ticks, InputStack

..so I changed the recipe to:

mods.forestry.Centrifuge.addRecipe([<minecraft:leaves> % 200, <minecraft:stick> % 80, <Forestry:beeCombs> % 20], 20, <minecraft:sapling>);

##note the InputStack comes last.

..and it works just fine. It's just a tiny wiki editing error but one that no doubt confuses non-coder users (like myself).

I'm not sure if the same issue affects the other Forestry handlers' wiki entries. I'm not up to that part yet.

Anyway, I now have my Centrifuge recipe working:

mods.forestry.Centrifuge.addRecipe([<Forestry:honeyDrop:0> % 50, <harvestcraft:waxcombItem:0> % 100, <harvestcraft:royaljellyItem> % 1], 20, <harvestcraft:honeycombItem>);

and it's working perfectly. Thank you so much for all your work on this.

**Comment by Voidi** [comment]
@Yulife See you the Problem?

I'm thinking about generating the documentation automatic via Javadoc, because the wiki format isn't that readable. But don't expect that soon.

**Comment by Yulife** [comment]
...what?

**Comment by ubermentat** [comment]
This isn't a bug, it's just a typo on the wiki. The example for the addRecipe handler on the Centrifuge should read `mods.forestry.Centrifuge.addRecipe([<minecraft:leaves> % 200, <minecraft:stick> % 80, <Forestry:beeCombs> % 20], 20, <minecraft:sapling>);` (currently the example has the input stack and tick time swapped)

**Comment by Yulife** [comment]
Ah cheers. For reference, the wiki is open to be edited btw.

**Comment by Nephatrine** [comment]
I'm using ModTweaker 0.9.5 and it seems this has somehow reversed again as I have had to put the ticks at the end after the inputstack to get it to work. Perhaps the documentation could be updated again if this has indeed changed.
