### ISSUE TITLE
Forestry Carpenter

### ISSUE THREAD

**Issue by aikpoppel** [jaredlll08/ModTweaker2#279]
Hey,
i cant remove any carpenter recipes or add new ones.

script example:
```
mods.forestry.Carpenter.removeRecipe(<Forestry:core:1>, <liquid:seedoil>);
mods.forestry.Carpenter.addRecipe(<Forestry:core:1>, [[<ore:planksWood>, null, null], [<ore:planksWood>, <ore:planksWood>, <ore:planksWood>], [<ore:planksWood>, null, <ore:planksWood>]], <liquid:plantoil> * 500, 200);
```
If i reload this script i get:
"ERROR: Error executing forestry.zs
forestry/factory/gadgets/MachineCarpenter$RecipeManager

Forge 10.13.4.1558, Forestry 4.2.0.47, MineTweaker 3.0.10B, ModTweaker: 0.9.4

**Comment by Voidi** [comment]
Modtweaker 0.9.4 only supports Forestry 3. Use a modtweaker dev build from the jenkis server or wait for a release.
