### ISSUE TITLE
FSP removeMelting does not work

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#28]
With [this script](http://paste.ee/p/89HYX) I could in theory remove the melting of Gold Ingots in a Crucible.
Though, it doesn't work but it also gives no error.
![2015-01-24_16 17 52](https://cloud.githubusercontent.com/assets/8559428/5887801/8f393ae8-a3e4-11e4-8ce9-2349eb032c50.png)

**Comment by jaredlll08** [comment]
Does anything FSP actually work?

**Comment by Yulife** [comment]
You tell me :P What didn't work got reported.

**Comment by jaredlll08** [comment]
FSP is not modtweaker friendly.
