### ISSUE TITLE
java.lang.NoClassDefFoundError: forestry/core/utils/ShapedRecipeCustom

### ISSUE THREAD

**Issue by Tsyklop** [jaredlll08/ModTweaker2#283]
Error in the log file: 
http://pastebin.com/V8QrbDqR

ModTweaker-2-0.9.5
forestry_1.7.10-4.2.1.48

**Comment by shifuren** [comment]
same thing here
http://pastebin.com/BMqUtfzX
ModTweaker-2-0.9.5
forestry_1.7.10-4.2.1.48

**Comment by Voidi** [comment]
Wrong Jar was uploaded to Curseforge, Download it again please.
