### ISSUE TITLE
0.9.5 JAR on CurseForge self-reports as 0.9.4

### ISSUE THREAD

**Issue by jarrett** [jaredlll08/ModTweaker2#285]
The 0.9.5 JAR that's currently up on CurseForge self-reports as 0.9.4. It contains this:

    // ModTweaker2.class
    @Mod(modid="modtweaker2", version="0.9.5", dependencies="required-after:MineTweaker3")

There was also a good JAR file on CurseForge for part of today and yesterday. (I know because I happened to download to my local installation yesterday and to my server today.) As a result, clients with the bad JAR cannot connect to servers with the good one.

**Comment by Voidi** [comment]
ah Thanks for this report!
To many ocurances where i have to change Versionnumbers, i have forgotten some.

**Comment by Voidi** [comment]
Download while it's fresh, hot and not available else http://ci.tterrag.com/job/ModTweaker2/166/
