### ISSUE TITLE
[Suggestion] Include support for the Terrasteel Algamation Plate Plate

### ISSUE THREAD

**Issue by Kurbz** [jaredlll08/ModTweaker2#286]
I do not know how the plat itself is coded, but if possible it would be an interesting tool to be able to change the inputs or outputs of the plate's crafting. It is a small thing, only one recipe without tweaking more in. 

I am sort of sorry to ask for something so selfish. I only ask because I was wanting to change it so that it would craft some sort of "inert Terrasteel" that was added with something like Quadrum, and require an activation process similar to Thaumium Wand Caps from Thaumcraft.

**Comment by Voidi** [comment]
Sorry the items are hardcoded
