### ISSUE TITLE
[Suggestion] Support for Forestry Bottler

### ISSUE THREAD

**Issue by TheOnlyRupert** [jaredlll08/ModTweaker2#287]
I would love to be able to add/remove recipes to Forestry's Bottler machine. I use it a lot because I don't have Thermal Expansion or any other mod installed where I can fill up containers with liquids.

**Comment by Voidi** [comment]
Why? The Bottler should automatically add recipes for all fluid/fluidcontainer combinations.

**Comment by Yulife** [comment]
Well, it'd be the same as the Filling Machine from IE. Iirc @BluSunrize has recipes for all fluid / container recipes as well but has custom support for those out of that area.

**Comment by TheOnlyRupert** [comment]
Sorry it took long to delay. Weekends are not ideal for me.

Even though there is no option to empty liquid into the machine and keep containers such as cans and capsules like in Thermal Expansion, I want to add custom recipes for some high tier items to force players to use the Bottler to fill up with certain fluid.

**Comment by Voidi** [comment]
a cautious maybe
