### ISSUE TITLE
Suggestion to be added in for a good perpose 

### ISSUE THREAD

**Issue by mightydanp** [jaredlll08/ModTweaker2#288]
Is there a way for you guys to add a add/remove in tinkers construct for modifiers. so like for me i want to remove certus quarts as a modifier so it will not give sharpness to anything if i try to use it in the tool station and such

**Comment by Voidi** [comment]
How should we add Modifier? Each modifier has its onw logic which define its behaviour. Removing is already possible.

**Comment by mightydanp** [comment]
I sead add / remove a item as a modifier so like removed certus quarte being able to give you sharpness in the tool station

**Comment by Voidi** [comment]
Sorry, I don't think this good to implement in Minetweaker/Modtweaker. The items for the modifiers are save in the modifer object itself. Since each specific modifertype class has it's unique structure we can't access this in a general way.

**Comment by mightydanp** [comment]
it would be awesome because for example extra tic has a certus quarts pick axe and to repair it you need certus quarts but if you have an available modifier then it repairs it and gives you sharpness on the tool
