### ISSUE TITLE
Cannot remove specific ores from the orechid

### ISSUE THREAD

**Issue by Sunconure11** [jaredlll08/ModTweaker2#289]
I'm trying to remove erebus ores from the orechid, and, I get this message every time I do so:

https://www.dropbox.com/s/nhdd6lu93besza4/Screenshot%202015-12-14%2012.34.28.png?dl=0

The script I am using:

http://pastebin.com/fjWWw2HM

**Comment by Voidi** [comment]
Rtfm!

**Comment by Sunconure11** [comment]
Yeah, I just realized this too late. However, removing specific ores would be a nice feature. I managed to create a work around for this at the moment though.

**Comment by Voidi** [comment]
Not possible snce the Orechid only has a list of Oredict names.

**Comment by Yulife** [comment]
Well don't just say you found a workaround, post it as well :stuck_out_tongue_winking_eye: My guess you made a custom oredict for one item and added that to the removal?

**Comment by Sunconure11** [comment]
That is basically what I did, yes.
