### ISSUE TITLE
recipe conflict and plating problems

### ISSUE THREAD

**Issue by blackstaer** [jaredlll08/ModTweaker2#290]
The is a recipe conflict with steve's carts 2 "raw handler" and your "Iron Rod".
Also I'm not able to make Iron- and Goldplats with the Small Plate Presser, but Tin and Steel works fine.

**Comment by jaredlll08** [comment]
Hi please tell me... When you look at the "iron rod" what mod does it say it is from?? NOT MODTWEAKER, modtweaker does not add any items.
