### ISSUE TITLE
[Question?] Mekanism metallurgic infuser Infusion material addition.

### ISSUE THREAD

**Issue by karakufire** [jaredlll08/ModTweaker2#291]
Now we can use infusion materials from only limited materials.
Is it possible technically to add more materials to infuse?
and if it's possible, do this become operation on ModTweaker side or other?

**Comment by Voidi** [comment]
If you mean materials that get filled in the left bar (in the Infuser GUI) then no,
I don't think that this can done meaningful via ZenScript because you have to specify parameters like a texture name.

**Comment by karakufire** [comment]
I see. why are you regard as no mean?
and I also think this suggestion may be in Content Tweaker field, Do I have to re-post for there?

**Comment by Yulife** [comment]
Welll ContentTweaker is ZenScript and Voidi just said that it cannot be done easily with that :p

**Comment by jaredlll08** [comment]
What is going on here?

**Comment by Yulife** [comment]
Use your eyes to read Jared ;)

**Comment by jaredlll08** [comment]
Ok so, if you are asking if it is possible to create an item in zenscript, then yes.
If you are asking for it to go on the side of the infuser to be turned into liquid (or whatever the infuser does with the stuff on the side), then no.
