### ISSUE TITLE
Forestry module - fermenter removeRecipe

### ISSUE THREAD

**Issue by JasonMcRay** [jaredlll08/ModTweaker2#292]
Doing `mods.forestry.Fermenter.removeRecipe(<*>); `Works perfectly, it removes all Fermenter recipes, which I want to do, but it spams the chat with: http://pastebin.com/29GcASLw
used ModTweaker 0.9.5.

Is there a way to make it ignore the error?

**Comment by Voidi** [comment]
There is no way to ignore errors.
But there shouldn't be errors anyway; from which mods are these items/fluids? (Which need i to reproduce?)

**Comment by JasonMcRay** [comment]
I am trying to remove all forestry Fermenting recipes (by using wildcard <<*>> value in the script) and changing biomass creation. It is done in Infitech 2 modpack. The pastebin is just a small part of the spam i am getting...
