### ISSUE TITLE
Why is this script crapping out on me?

### ISSUE THREAD

**Issue by Sunconure11** [jaredlll08/ModTweaker2#294]
Note: I have the tabs and such created, but, when I add this, I get a null error from minetweaker. I was able to add one page fine, but, adding this new page craps it out:

http://pastebin.com/216arhCe

The log also gave me this error:

http://pastebin.com/bXkwnbin

**Comment by jaredlll08** [comment]
Can you post the whole script please

**Comment by Sunconure11** [comment]
It turned out to be a user error
