### ISSUE TITLE
Pure Daisy syntax is reversed

### ISSUE THREAD

**Issue by Zsashas** [jaredlll08/ModTweaker2#299]
On the wiki it says that Output is listed first, then Input. However, when actually using it in a script, the first item is apparently the input. Almost all other recipe types have the Output first.

Example:
mods.botania.PureDaisy.addRecipe(<Botania:bifrostPerm>, <Mystcraft:BlockCrystal>);

You would expect this to turn crystal blocks into Bifrost blocks, but it turns Bifrost blocks into crystal blocks.

**Comment by Yulife** [comment]
Oops will look into that!

**Comment by Yulife** [comment]
No it isn't? 

//Pure Daisy
//InputBlock, OutputBlock
mods.botania.PureDaisy.addRecipe(<minecraft:emerald_block>, <minecraft:diamond_block>);
//OutputBlock
mods.botania.PureDaisy.removeRecipe(<minecraft:obsidian>);

**Comment by Zsashas** [comment]
Compared to every other type of minetweaker recipe, which puts output first. This can cause some mods to think a recipe is being made for the input item, and trigger an auto commenting-out of the lines.

**Comment by Yulife** [comment]
Ahhh you mean in that way. Well, in 1.8 we will probably change the Syntax in a correct way, namely Output -> Input -> Misc with the parameters. If we would do this in 1.7 everyone's scripts would break. We are already working on changing the parameters for TC5 to be in the correct way and if we will get to Botania 1.8 we will change it according to that too :)
