### ISSUE TITLE
Command to update localizationName for materials in Tinkers' Construct.

### ISSUE THREAD

**Issue by Psithief** [jaredlll08/ModTweaker2#300]
Tinkers' Construct provides its own N.E.I. GUI for materials, but it only uses the material's localised name, it never falls back to the display name.

As the developers of TC have said that they won't be fixing anything except major bugs for 1.7.10, will you allow tool localisation names to be changed, not just the display names?

https://github.com/jaredlll08/ModTweaker2/blob/master/src/main/java/modtweaker2/mods/tconstruct/handlers/ToolStats.java

**Comment by Voidi** [comment]
Why should you want to change the localisation key of a material? For me the NEI Page works as it should.

**Comment by Psithief** [comment]
Some mods are adding their own materials to tinkers' construct, but they're not adding localised names, e.g. Extra Utilities with `material.bedrockium`, `material.magicwood`, `material.unstableIngot`, of anything from ExtraTiC

e.g. from EU code:
```java
ToolMaterial mat = new ToolMaterial("unstableIngot", "material.extrautils.unstableIngot", 4, 100, 700, 2, 0.6F, 4, 0.0F, EnumChatFormatting.WHITE.toString(), 16777215);
```

A screenshot may help:
![2016-01-26_22 06 10 - copy](https://cloud.githubusercontent.com/assets/1124846/12582602/25579b2c-c479-11e5-997a-fa2844cb472e.png)

**Comment by jaredlll08** [comment]
Well now we have a problem,  first of all,  if it is an issue with other
mods as well,  then we can't fix it,  also we are also kinda on the only
major bug fixes for 1.7

**Comment by Psithief** [comment]
So I've just realised that this is something that can be fixed in a resource pack, I think. Thanks anyway!

**Comment by Psithief** [comment]
If you don't mind I'll leave instructions for the next person that has this issue

---

I added the following to a file `assests/tinker/en_US.lang` file in a resource pack:

```
material.unstableingot=Unstable Ingot
material.bedrockium=Bedrockium
material.magicwood=Magical Wood
material.pinkslime=Pink Slime
material.certusquartz=Certus Quartz
material.netherquartz=Nether Quartz
material.plastic=Plastic
material.lead=Lead
material.nickel=Nickel
material.invar=Invar
```
