### ISSUE TITLE
[Request] Botanical Addons (Botania) support

### ISSUE THREAD

**Issue by Zsashas** [jaredlll08/ModTweaker2#301]
The fancy new Dendric Suffuser. Sort of a hybrid of the Runic Altar and Thaumcraft's Infusion Altar.

Functionality:
https://www.youtube.com/watch?v=KlrQioZ9fN0&feature=youtu.be

Context:
https://www.reddit.com/r/botania/comments/43fouv/botanical_addons_botania_thaumcraft_aspects_sound/cziae2r?context=3

Github:
https://github.com/L0neKitsune/Botanical-Addons

**Comment by yrsegal** [comment]
Also iridescent sapling variants! Custom trees, yay

**Comment by yrsegal** [comment]
imma implement this on BA's side, please close this in favor of https://github.com/L0neKitsune/Botanical-Addons/issues/82

**Comment by yrsegal** [comment]
close this, please
