### ISSUE TITLE
AE2 API outdated?

### ISSUE THREAD

**Issue by Robijnvogel** [jaredlll08/ModTweaker2#304]
I am getting this error when trying to add a recipe to the AE2 Inscriber, using ModTweaker 0.9.4:
appeng.api.features.iinscriberregistry.getrecipes()Ljava/util/list

I am using I am using AE2 rv3 beta 5, because the addon developers for AE2 are most often building against AE2's bet-builds. The latest stable build is half a year old and shouldn't have this problem, but that is half a year of updates I am not willing to miss.
If you already fixed this in MoT 0.9.5, I don't see it in your change logs.

My guess is that the AE2 API got updated since half a year ago.

**Comment by Robijnvogel** [comment]
All that seems to have changed is that the Collection returned by that API method is now actually an non-modifiable Collection made of a HashSet, instead of an ArrayList.

Maybe some workaround can be made to make ModTweaker work with both versions of the API?

**Comment by jaredlll08** [comment]
Well we only support the stable builds because the AE2 devs litterally change things we need every beta build, and then we have people complaining stuff like "oh but you don't support the beta build that came out 2 seconds ago!"

**Comment by Voidi** [comment]
Furthermore: isn't nearly everything we have handlers, configurable via AE2 own custom recipe system?

**Comment by Robijnvogel** [comment]
Thank you! I forgot that whole recipes folder inside the AE2 config folder as I did not need the functionality at the time. That must have been months ago.

NOTE
This:
"inscribe=
    oredictionary:itemSilicon ae2:ItemMaterial.SiliconPress
    -> ae2:ItemMaterial.SiliconPrint"
Does not seem to include items added to the itemSilicon oredictionary by means of MineTweaker.

Well then I guess this issue only serves to remind you of one thing that needs to be done whenever AE2 releases their next stable build.

**Comment by Robijnvogel** [comment]
The AE2 Github hasn't had any commits since this this beta version was released two months ago. Maybe AlgorithmX2 is taking a break?

Could I ask you to reconsider your decision on this issue?

**Comment by jaredlll08** [comment]
No.  We will never reconsider because of what updating to unreleased
versions has done for us. Nothing besides 20+ bug reports.

**Comment by Yulife** [comment]
How stable is them beta? I guess everyone has moved on and I don't think Modtweaker should hold modpack makers back.

**Comment by Robijnvogel** [comment]
I've been using that beta ever since it was released and have yet to run into any issues. (Besides ModTweaker compatibility.)

**Comment by Yulife** [comment]
Yeah she should move on them :P Although I'm not sure if 1.7 is still in development though for Jared. @Voidi?

**Comment by Robijnvogel** [comment]
This issue doesn't fall under "development", but under "maintenance". Those are two very different things.

**Comment by Voidi** [comment]
@Yulife hm yes would be nice to have 1.7 release that works with latest AE2.

Jared only does 1.8 things now isn't. And i would only fix bugs for the 1.7 version, because i can't find any motivation for me to do new features in 1.7 which now reaches slowly end of life.

But aside from if i have time for this, then people who use the AE stable branch can't update Modtweaker.

**Comment by Robijnvogel** [comment]
Can't you implement the code in such a way that it is compatible with both? (that would probably be hard).
Or do a branch with a resulting release that is for AE2 rv3 beta 5 compat in special, then continue updating the main branch of releases. I guess that would be a simple solution to scare off annoying people like me. :tongue:

**Comment by Yulife** [comment]
We could probably do it in a way that we did with forestry 3 to 4 and release two different versions, A and B with each them stable compability and the beta compability.

**Comment by jaredlll08** [comment]
That ended badly remember

**Comment by Yulife** [comment]
Nah I don't :smile:

**Comment by jaredlll08** [comment]
Well it did.
