### ISSUE TITLE
FPS removeDunking does not work

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#31]
With FPS you are able to dunk an Iron Ingot into 1/9 of a Gold Ingot to get Gilded Iron.
According to Flax's code the liquid string is "liquidGold".
However, when I try to remove the dunking with [this script](http://paste.ee/p/525rp) it does not work. It doesn't give an error either.
![2015-01-24_16 39 07](https://cloud.githubusercontent.com/assets/8559428/5887868/87b9460c-a3e7-11e4-8fb6-0ffbfb2d7bf0.png)

**Comment by jaredlll08** [comment]
FSP is not modtweaker friendly.
