### ISSUE TITLE
EnderIO support

### ISSUE THREAD

**Issue by Dijkstra1** [jaredlll08/ModTweaker2#313]
I know that you can edit EnderIO recipes with their XML configs, but it would be nice to able to do it zen script as then all recipe changes would be in one place, also enderIO does not always play fair, like a mod pack i am working i am rework all ingot/nugget/dust recipes to just you one of each, most stuff I can change even the enderIO sag using XML but when it comes the alloy smelter you can alloy recipes but even though have changed the furnace the alloy smelter will still default to TF/TE ingots, you may not be able do anything about that but I would still enderIO support in zen script to have every thing in one place.

**Comment by jaredlll08** [comment]
Not gna happen, unless @tterrag1098 says otherwise, since last time he said
there exist no point, also no new modtweaker for 1.7

**Comment by tterrag1098** [comment]
There is no point. You can do everything MT does with the xml configs.

**Comment by Dijkstra1** [comment]
Not quite for one I have to restart minecraft, to test it, a second is it does not work with ftb game modes, three I have no control over furnace recipes in the alloy smelter.

**Comment by Tsyklop** [comment]
any news?

**Comment by Yulife** [comment]
Did you try EIO's native config files? EnderIO would be the lowest priority to have MT support for haha

**Comment by Dijkstra1** [comment]
Yes I am using the configs I just wish I would be game mode compatible, but at least all ore process to one type of ingot and dust.

**Comment by Yulife** [comment]
Couldn't you just then use e.g. oreCopper as an input and the item name of EnderIO's copper ingot and dust as an output?

**Comment by Dijkstra1** [comment]
Say I am also working with IC2 I can not remove IC2 dust from maceator, but even removing all ore dic to other ones enderio still wants to TF dust which means I have to change sag mill in xml or have two dusts which I do not like, and leaving it does not help with FTB tweaks game modes.

**Comment by jaredlll08** [comment]
@Dijkstra1 deal with it. FINAL DECISION.
