### ISSUE TITLE
[Request] Vanilla minecraft fishing drops support

### ISSUE THREAD

**Issue by Timeslice42** [jaredlll08/ModTweaker2#317]
I know mods can add to the drops for fishing, but would it be possible for MT to add support for this, as it did for dungeon loot in the past?

**Comment by Yulife** [comment]
I think those would fit more into Minetweaker?

**Comment by jaredlll08** [comment]
Yea it would, the reason he is asking her is... I denied the minetweaker
one,  it just isn't possible, 1.8+ atleast. Yulife, I'm on mobile, close
this please

**Comment by Timeslice42** [comment]
I didn't even look at the minetweaker github. The ModTweaker team added chest loot, so I figured they might know about fish loot.

So are you saying it *is* possible in 1.7? I might have to look into that myself then. We have a pack specific mod for just such occasions.

**Comment by jaredlll08** [comment]
Except we never added chest loot. That was once again, minetweaker, I don't
know if it is possible in 1.7. I never looked into it.

**Comment by Timeslice42** [comment]
My mistake. I guess [this page](http://minetweaker3.powerofbytes.com/wiki/Tutorial:Loot) was referring to just the seeds functionality.

**Comment by jaredlll08** [comment]
That page says that it uses to be in modtweaker and now it is in
minetweaker, and I'm the new author of modtweaker, I never wrote the seeds
part

**Comment by Yulife** [comment]
Timeslice is correct. However, that got merged into Minetweaker as that is for vanilla handlers. Is fishing loot in 1.9 a loot table now?

**Comment by jaredlll08** [comment]
Yulife, hasn't checked, I can't even get 1.9 Mt to load

**Comment by Yulife** [comment]
Yup, good news, fishing is a loot table :D this can stay closed then.

**Comment by Timeslice42** [comment]
That's good news. Thanks for the follow up :)
