### ISSUE TITLE
FPS Steaming Handler does not work at all

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#32]
[Script](http://paste.ee/p/Wwoha)
Both of them do not work. They do not give any error.
In my understanding addSteamFood is kind of a wrong naming. Shouldn't it be addSteaming? I don't think the Furnace + Steam Heaters is limited to food.
Calling @SatanicSanta and @bonii-xx.

**Comment by bonii-xx** [comment]
And you're calling me because...?

**Comment by Yulife** [comment]
Things like Steamed Food - they can be only created by using a Furnace plus Steam Heaters. Is this "steaming" cooking limited to food only or can it be used for anything?

**Comment by bonii-xx** [comment]
And you're calling me because...?

**Comment by Yulife** [comment]
"Is this "steaming" cooking limited to food only or can it be used for anything?"

**Comment by Yulife** [comment]
Well, this is emberassing. I mixed ya up with @xbony2! T_T
Sorry.

**Comment by bonii-xx** [comment]
Lol. I wondered why you'd think I had anything to do with it. But I can see the resemblance ;P

**Comment by xbony2** [comment]
Poor Bonii :P Adding new steamed food needs an actually food item, but adding a recipe probably shouldn't. At least I think.

Going to look at this mod's API usage and see what they're doing.

**Comment by xbony2** [comment]
For whatever reason MT doesn't use the addSteamFood() that comes in FSP's API, does some other stuff.

**Comment by Yulife** [comment]
@jaredlll08 and @soundlogic2236 Would you mind changing it?

**Comment by xbony2** [comment]
I'm not sure if it's really the problem, but it would probably be better to call it then change the steamedFoods HashMap directly.

**Comment by joshiejack** [comment]
The reason I generally didn't use methods, and manipulated things directly is mods generally only have an add recipe and not a remove recipe in their apis. Plus it's easier than using different methods. Was less code xD.

I never actually tested the FSP, so not surprised it doesn't work.

**Comment by jaredlll08** [comment]
FSP is not modtweaker friendly.
