### ISSUE TITLE
[1.7.10] [BUG] Cannot specify low byproduct chance for Forestry squeezer

### ISSUE THREAD

**Issue by hron84** [jaredlll08/ModTweaker2#320]
I tried many ways but I cannot figure out how can I specify low chance for byproduct in Forestry Squeezer recipe. The following values tried:

 - ` <Forestry:craftingMaterial> % 5` - tooltip says 400% chance
 - ` <Forestry:craftingMaterial> % 20` - Tooltip says 2000% chance
 - ` <Forestry:craftingMaterial> % 0.5` - Tooltip says "never".

My best guess is you have to divide speciifed values by 100 or let us to specify decimals not only integers.

Also, byproduct field does not allow null. However there _is_ a Squeezer recipe that does not have a byproduct.

* **ModTweaker2** 0.9.5
* **Forestry** 4.2.11.59

**Comment by hron84** [comment]
@Voidi Could you please tell me when we can expect this fix in a released package?

**Comment by Voidi** [comment]
Honestly i don't know because when a new Version for 1.7.10 will be Released. Everything is slowly moving away from 1.7.10 now.
And i don't have much motivation to fixes issues which cost a large amount of time
I recommend grabbing the latest build from the [Jenkins Server](http://ci.tterrag.com/job/ModTweaker2/)

**Comment by hron84** [comment]
I see and I can accept it. Even if I think it's a too early move (1.8.9 is not an "LTS" version of MC from modding aspect like 1.6.4 or 1.7.10 was and everything is a moving target), I absolute understand your decision. I asked it because I building a modpack that's Curse-based, and I prefer versions that are uploaded to there. No hurry, no push. Thanks for your quick and great assistance anyway.
