### ISSUE TITLE
Modtweaker script no longer functioning. 

### ISSUE THREAD

**Issue by Benedictum** [jaredlll08/ModTweaker2#321]
I am having problems with the follow script - http://paste.ee/p/wbFuM specifically lines 40-62. This script worked with Modtweaker 2-0.9.5 and Botania r1.6-191. Updating to Botania r1.8-249 the scripts are no longer working. http://imgur.com/EZmx7tL theres some issues with that other script that ill get to once this one is working.

**Comment by Benedictum** [comment]
oh note that error screenshot is from before i cleaned up the script so the lines wont match to the lines causing errors. I could generate a new one if needed but its the same error codes just different lines.

**Comment by Voidi** [comment]
Yes please generate a new one, without the correct linenumber it's hard to find the line causing the error. And please no Screenshot of the Chat, the minetweaker.log exists for a reason.

**Comment by Benedictum** [comment]
http://paste.ee/p/wbFuM here is the up to date minetweaker.log. I think i found the issue however.

mods.botania.Lexicon.addEntry("botania.entry.etherealBloom","botania.category.functionalFlowers", **<Thaumcraft:blockCustomPlant:4>**)

In the old script, the above bolded entry was missing but the script was still functional, apparently it needs to be declared both in the entry AND the pages not just the pages as previously.

Unfortunately I cant test at the moment to confirm resolution because my system memory leaked out and crashed. Once I get back to the house I can reboot it and test, but i was able to add that to ethereal bloom and it no longer errors in the minetweaker.log but shimmerleaf still does, so i assume thats a positive sign.

**Comment by Benedictum** [comment]
Verified that that is indeed the issue, it was not pointing at the block ids. Dont know why that made it work in previous botania but not in more recent, but there ya go.
