### ISSUE TITLE
Can't use "addRepairMaterial" for TConstruct

### ISSUE THREAD

**Issue by Mncc08** [jaredlll08/ModTweaker2#322]
I'm testing things and I can't add repair materials to a tool, despite i can remove one.
I tried like that : `mods.tconstruct.Tweaks.addRepairMaterial(<minecraft:iron_ingot>, "Copper", 1);` but it doesn't work..

I'm using following mod versions :
MineTweaker3 3.0.10
ModTweaker2 0.9.5
Mantle 0.3.2b
TiC 1.8.8

**Comment by jaredlll08** [comment]
Tic stuff is broken

**Comment by Mncc08** [comment]
So there is no way to add repair material ? Will it be fixed  ?

**Comment by jaredlll08** [comment]
Honestly, 1.7 is dead / dying, so not in this version no.
