### ISSUE TITLE
[1.7.10] Not working /mt LexiconEntries

### ISSUE THREAD

**Issue by Shurik1236** [jaredlll08/ModTweaker2#323]
RUS:
Мне нужно кое что изменить в книжке.
Я поменял один рецепт и теперь там отображается не верный. Хочу это исправить.
Вписал команду "/mt LexiconEntries", в ответ получил "No such minetweaker command availadle"...
Как мне теперь что то изменить в книжке то?
ENG (Yandex Translator): 
I need to change something in the book.
I changed a recipe and now there is not true. I want to fix it.
Added the command "/mt LexiconEntries", in response I got "No such command minetweaker availadle"...
How do I now change something in the book?

**Comment by jaredlll08** [comment]
We don't add a command for that, and honestly I'm not to sure on how
lexicon entries work, @yulife you know?

Anyway, Take a look ay the documentation on the wiki for it.
