### ISSUE TITLE
[1.8.9] only works with CraftTweaker version 1.8.8-3.0.2

### ISSUE THREAD

**Issue by lehjr** [jaredlll08/ModTweaker2#325]
I can't get ModTweaker2-1.0.0 to work with any other version of CraftTweaker, only 1.8.8-3.0.2
CraftTweaker-Customized-1.8.9-3.0.5 crashes on load, the others aren't detected by ModTweaker.

**Comment by Yulife** [comment]
Sorry, we are skipping to 1.9 :)

**Comment by jaredlll08** [comment]
We are actually skipping to 1.9.4 :P

**Comment by lehjr** [comment]
Skipping you say? I prefer walking, but meh, to each his own. :P
