### ISSUE TITLE
Remove FSP integration

### ISSUE THREAD

**Issue by elifoster** [jaredlll08/ModTweaker2#327]
So, modtweakers fsp zen classes are conflicting with the native minetweaker support in fsp, preventing any of it from working. I pinged Jared about this on the issue on the fsp repo, but have yet to get a response. This is an issue for 1.7.10.

**Comment by jaredlll08** [comment]
I have read through them, just been super busy...

So imo, 1.7 is dead, I honestly don't see a point in building releases for it considering we are now on 1.9.4 with 1.10 on the horizon.

**Comment by elifoster** [comment]
1.7 being dead isn't really a reason to make our mods completely incompatible for no reason. It would take like 5 minutes to do this...

**Comment by Voidi** [comment]
I'll do this, do you need a official release on curse?

**Comment by elifoster** [comment]
That would be excellent.

**Comment by Omuck3** [comment]
Yay!

**Comment by Voidi** [comment]
Please test http://ci.tterrag.com/job/ModTweaker2/172/

**Comment by Omuck3** [comment]
How....  Would I download that? :/

**Comment by Dream-Master** [comment]
Its Building for 3 days so :P

**Comment by Voidi** [comment]
Fuck jenkis has crashed or get stucked. Again.
@jaredlll08 or @tterrag1098 ?

**Comment by tterrag1098** [comment]
Blame the IRC plugin. Stop using it. I use notifico instead.

**Comment by Voidi** [comment]
That means? i don't know how this jenkins integration works

**Comment by tterrag1098** [comment]
I just removed it

**Comment by elifoster** [comment]
Do you think we could get a new release of MT with this fix?

**Comment by Dream-Master** [comment]
http://ci.tterrag.com/job/ModTweaker2/172/

**Comment by Voidi** [comment]
Test it. if it works there will be a new Release.

**Comment by elifoster** [comment]
@Omuck3 Can you test it since you originally reported the issue?

**Comment by Omuck3** [comment]
So far, it works.
