### ISSUE TITLE
[Request] Command for Orechid Weights

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#33]
Using ...

"// Orechid
// Ore Dictionary Entry, Weight
mods.botania.Orechid.addOre("blockNetherStar", 9000);"

..you are able to add ores to the Orechid. From the first sight, those weights tell me nothing at all. A command that would print all weights of all ores in the minetweaker.txt would be pretty nifty.
"/mt botaniaOrechid" maybe?

**Comment by jaredlll08** [comment]
Done

**Comment by Yulife** [comment]
What's the command, though? lol

**Comment by 016Nojr** [comment]
Maybe as you requested? /mt botaniaOrechid :P

**Comment by talonos2** [comment]
Looks like it was put in wrong: 

MineTweakerAPI.server.addMineTweakerCommand("botaniaOrchid", new String[] { "/minetweaker botaniaOrechid", "    Outputs a list of keys for botania orechid weights" }, new BotaniaOrechidLogger());

Try /mt botaniaOrchid.

Also, this should probably be fixed. The "Help" description does not match the actual command.
