### ISSUE TITLE
[1.7.10] Weird problem

### ISSUE THREAD

**Issue by DestinyPlayer** [jaredlll08/ModTweaker2#334]
Basically, when I try to add this line:
`mods.thaumcraft.Research.addResearch("ALCHEMY", "EE", "permutatio 40, fabrico 10, ordo 20, perditio 20", 6, -1, 1, <EE3:alchemicalUpgrade>);`
It gives me this error:
http://pastebin.com/xfyKpDCK
And then keeps on blabbing about:
`ERROR: [ModTweaker2] Error removing Botania Rune Altar Recipe for <Avaritia:Resource>`
The whole script is here:
http://pastebin.com/yHGUUJRg
The whole modlist is here:
http://prntscr.com/brlw0k
Any ideas what's wrong?

**Comment by DestinyPlayer** [comment]
Ooh, wait, I've switched the tab and the research. Now I get it. Still, I'll leave this up, purely because the error should probably say that.

**Comment by jaredlll08** [comment]
We can't figure out what is and isn't a category, that is up to users to determine.

Also the other error, being the botania rune altar error is caused by reloading the game.
