### ISSUE TITLE
[Request] Move Centrifuge Chances

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#36]
For @jaredlll08 
Right now it is...

public static void addRecipe(int timePerItem, IItemStack itemInput, int[] chances, IItemStack[] output)

However, the chances should be after the Output.

**Comment by Yulife** [comment]
@Voidi could you take care of that?

**Comment by Voidi** [comment]
agree, but even better:
input, timePerItem, output[], chances[]

**Comment by Yulife** [comment]
Nah, time is at the beginning. That is with all other different recipes in Modtweaker.

**Comment by Voidi** [comment]
Nope Blast Furnace for example http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Railcraft_Support

We should think about some general rules.

I like the format Minetweaker has: first the output and then ingredients.
Vice versa is okay to.

**Comment by Yulife** [comment]
Could you please just set chance afterwards? We'll take care of unification at a very late point. If we do it now, people's script gonna break and that will cause many issues.

**Comment by jaredlll08** [comment]
Going to overrule here, inap knows his shit (I know it may seen like he doesn't but he really does...) So inap wins on this one

**Comment by joshiejack** [comment]
Yulife: You don't need to worry about that. When if/you standardise it. You can still keep the old methods. (Then remove them later down the line).

I think I pretty much just went with what the mods themselves were using?  xD

**Comment by Yulife** [comment]
Yeah, I used your documentation as a template :)
