### ISSUE TITLE
[Bug] Centrifuge doesn't accept Fuzzy Wildcard

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#37]
[This](http://paste.ee/p/Ida0Q) script would show up in NEI but if you try to put a sapling in, it wouldn't accept it. Removing the ":*" makes it work again.

**Comment by Voidi** [comment]
For me it shows it correct in NEI, but the machine does not process it. What exactly (if you use) addon/version have you for NEI Forestry recipes?

**Comment by Yulife** [comment]
Tonius' NEI Integration.

**Comment by Voidi** [comment]
I am currently uncertain: can the normal Minecraft Itemstack handle the metadata/Damagevalues wildcard?

**Comment by Voidi** [comment]
Similar behaviour in ThermicFabricator, Carpenter for example accepts wildcard. I assume that i implemented something different than jarred, so that my machines don't accept wildcards

**Comment by Voidi** [comment]
OK i found something, but don't know if i am stupid or Forestry do something wrong.
@mezz

Compare the matching methods of Centrifuge and Fermenter (are used to check if valid recipe):
https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/factory/gadgets/MachineCentrifuge.java#L75

https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/factory/gadgets/MachineFermenter.java#L95

I changend Centrifuges matches logic to the one used in the Fermenter and now it seems working.

**Comment by Voidi** [comment]
Is it now working? fixed they the Bug in Forestry.
