### ISSUE TITLE
[Request] Changing Squeezer Removal

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#39]
Right now the Squeezer has the OutputFluid as an option for the removal. However, using the InputStack for the removal would be much more convenient and less tedious.

**Comment by Yulife** [comment]
@Voidi you think you could do this as well? Jared's been off.

**Comment by Voidi** [comment]
Don't have that much time at the moment, let it open

**Comment by jaredlll08** [comment]
The squeezer needs an ItemStack array to remove... and that would mess up the undo command.
