### ISSUE TITLE
[Suggestion] Output is CVS format

### ISSUE THREAD

**Issue by BlakeDarwinXE** [jaredlll08/ModTweaker2#4]
While creating a Modpack I find it really helpful to use /mt names and /mt Blocks.

Sample out put:
<Metallurgy:adamantine.axe> -- Adamantine Axe
<Metallurgy:adamantine.hoe> -- Adamantine Hoe
<Metallurgy:adamantine.ingot> -- Adamantine Ingot

It would be helpful it the out was:
Metallurgy:adamantine.axe, Adamantine Axe
Metallurgy:adamantine.hoe, Adamantine Hoe
Metallurgy:adamantine.ingot, Adamantine Ingot

This would help with imports into spreadsheet software like Google doc.

**Comment by stanhebben** [comment]
It's MineTweaker providing the lmt names (and blocks) commands, so better ask this in the MineTweaker3 repository.

That being said, it's a good idea.

**Comment by jaredlll08** [comment]
Technically both of his requests should be minetweaker3 requests.

**Comment by BlakeDarwinXE** [comment]
Sorry, posted in the wrong mod
