### ISSUE TITLE
[Bug] Carpenter will not accept InputStack Box

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#47]
For @Voidi 
With Forestry changing some stuff with the box slot of the Carpenter, scripts that use the box slot no longer can be used properly. The script itself works and gives no error but I cannot put the box item in.
[Script](http://puu.sh/f4kNF/59a290e0cf.txt)
You may be wondering why I use logs as a Box item but it worked before while it doesn't now.
On the latest Forestry, Modtweaker and Forge.

**Comment by jaredlll08** [comment]
Fixed? needs testing!

**Comment by Yulife** [comment]
Told ya it isn't working. And why the hell are you closing issues if it needs testing? Think before you close an issue.

**Comment by jaredlll08** [comment]
Please try the newest version on jenkins, (wait a few hours)

**Comment by Yulife** [comment]
Well, it accepts the crate item defined in the custom recipe now...though..the recipe does not show up.
![2015-02-06_17 28 20](https://cloud.githubusercontent.com/assets/8559428/6082972/a410181a-ae25-11e4-9cac-18e85c035deb.png)
The script throws no errors, everything should work fine. Though, I crash when I look at the Carpenter Integration in NEI Integration.
