### ISSUE TITLE
[Request] Make A /Modtweaker or /Modtweaker Help Command

### ISSUE THREAD

**Issue by Lanse505** [jaredlll08/ModTweaker2#48]
I would like to Request a /Modtweaker or /Modtweaker Help command, that would list all the Modtweaker Added commands.

**Comment by Yulife** [comment]
Most of these are in /mt help. However, [all of the commands](https://github.com/jaredlll08/ModTweaker2/blob/975a8e3fe553c450e8b95a0de508530ebb1c7a40/src/main/java/modtweaker/Commands.java) are listed in there. Do note that most of them are WIP and in 0.7, a version that is not ready for the public yet.
