### ISSUE TITLE
[Bug] Tinkers Repair Materials Removal / Adding

### ISSUE THREAD

**Issue by artdude543** [jaredlll08/ModTweaker2#49]
It seems something change on Tinkers end with registering repair materials, thus now that ModTweaker can not remove or add repair materials as it throwing a null pointer while trying to apply the changes.

Error:
`java
java.lang.NoSuchMethodException: tconstruct.library.crafting.PatternBuilder$ItemKey.<init>(net.minecraft.item.ItemStack, int, int, java.lang.String)
`

I can paste a full log if you want but this is the main error being displayed.

Versions:
- Tinkers: 1.8.2a
- Mod Tweaker: 0.6-0 (joshiejack version)
  - I checked the source code for Tinkers; from this version and its the same as joshie's

**Comment by jaredlll08** [comment]
I need the full log, and the script you are using.

**Comment by artdude543** [comment]
I did some more testing and managed to get it to work for Vanilla items/block only but the `/minetweaker materials` seems to not be working, so I can not get the modded added materials to add metals to be used for repairing.

The error being displayed: 
`No such minetweaker command available`

Going back the original bug it works fine but for standard vanilla blocks/items. I would test with modded items but I can't find a way of me getting a list of the materials added as the command does not work.

**Comment by Yulife** [comment]
Jared asked you for a log and the script. If you don't give it, we can't help you.

**Comment by jaredlll08** [comment]
Please look at http://minecraft.curseforge.com/mc-mods/228458-jsonables
It does exactly what you want.
