### ISSUE TITLE
Thaumcraft scipts not working any more with 0.7b33 Build

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#50]
The Thaumcraft Scripts not working any more with 2.0.7b33. I write the scripts in Version 0.6. Did you change some things to make Thaumcraft Recipes ?

**Comment by Dream-Master** [comment]
https://github.com/Dream-Master/Mods-Get-Gregged/blob/master/Custom-Modpack-Scripts/Dream-Craft/scripts/Thaumcraft.zs

**Comment by Yulife** [comment]
Why in the world are you using the dev builds? Don't do that.

**Comment by Dream-Master** [comment]
Its only a question i not complain about changes or dev builds. Btw nice that some one working on Mod tweak because it makes nerfing much more easy. I see you add forestry support very nice.
And why you want to make jenkins privat?

**Comment by Yulife** [comment]
Weil das noch alles eine einzige Baustelle ist. Kein Wunder dass da was schief geht, bei deinen Scripts! Es muss erst noch alles fertig gemacht werden damit das für die Öffentlichkeit rausgebracht wird. Deswegen ist das auf einem Jenkins, einer Plattform die meistens nur für WIP mods benutzt wird. Damit keiner darüber meckert wie alles nicht funktioniert wird das privat gemacht.

**Comment by Dream-Master** [comment]
Ich mecker nicht ich finde super das ihr weiter macht. Hab selber mit Java erst gerade angefangen (da man Thaumcraft Stäbe nicht richtig Nerfen konnte) und mode aber schon seitdem es Mods für Minecraft gibt. War halt nur ne Frage hab mir nicht jede Änderung die ihr gemacht hab durchgeschaut. 
Wie gesagt das ihr bald Forestry unterstütz finde ich super. Danke für eure arbeit.

**Comment by Yulife** [comment]
Neeein, du hast mich falsch verstanden ^-^ Ich meinte nicht meckern sondern eher.. wundern warum es nicht funktioniert :)

**Comment by Dream-Master** [comment]
Ok kein Problem. 
Gibt es den signifikante Änderungen bei Thaumcraft? Hab halt alles was ich zum nerfen brauchte über die Minetweaker Seite und durch viel ausprobieren raus bekommen.

**Comment by Yulife** [comment]
SoundLogic hat etwas mit Thaumcraft verändert. Aber bist du dir sicher dass du alles richtig geschrieben hast?

**Comment by Dream-Master** [comment]
Ja vorher keine Fehler dann ZS 0 Fehler(nur bei Arcane Rezepten) Kann auch an Thaumcraft liegen. Azanor hat manche Sachen so programmiert das sie das removen der Rezepte verhindern. (hat er mir geschrieben) was das nerfen unmöglich macht.
