### ISSUE TITLE
[Bug] Removing Crucible Furnace's Liquid Fuel & Solid Fuel doesn't work

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#51]
Using [this](http://puu.sh/fh04t/a21bb10c9c.txt) script lava is supposed to be removed from the fuel sources, thus it should no longer heat the Crucible Furnace if the lava is in the Fluid Tank under the Crucible Furnace. However, that does not work. It throws no error, just doesn't work.
![2015-01-31_11 37 31](https://cloud.githubusercontent.com/assets/8559428/5987756/a1177596-a93d-11e4-9791-0700f0eef93e.png)
![2015-01-31_11 37 43](https://cloud.githubusercontent.com/assets/8559428/5987755/a1176bc8-a93d-11e4-8e4f-501faa1eb7a8.png)

The code says this:

 @ZenMethod
public static void removeFuel(ILiquidStack fuel) {
MineTweakerAPI.apply(new RemoveFuel(fuel));
}

@joshiejack is "ILiquidStack fuel" connected to the tank with the fuel under the Crucible or is it something different?

**Comment by Yulife** [comment]
Mhm, [this](http://puu.sh/fh0tt/7e5521b26c.txt) doesn't seem to work either. The string-oredictionary-removal works, though!

**Comment by joshiejack** [comment]
You can't remember lava that way because it's add as a string "lava" not as a fluid.

**Comment by Yulife** [comment]
So it does not accept "<liquid:[liquidname>" but rather a "[liquidstringname]" embedded in the code?

**Comment by joshiejack** [comment]
yes
