### ISSUE TITLE
[Bug] Crucible & Vat Removals are throwing errors

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#53]
If you try to remove a Crucible Furnace Smelting Recipe (Not a fuel one) and a Vat recipe in general you will end up with an error.

[Crucible Furnace Error](http://puu.sh/fiC1t/fd94a9c5ff.txt)
[Crucible Furnace Script](http://puu.sh/fiFGx/6f14e74251.txt)

[Vat Error](http://puu.sh/fiFzr/348d569960.txt)
[Vat Script](http://puu.sh/fiFMz/347d8f9e49.txt)

**Comment by jaredlll08** [comment]
Inserted some checks, will push later

**Comment by jaredlll08** [comment]
Mariculture seems to cache their recipes, or something, either way, I can't add recipes without it crashing when I look up recipes...

**Comment by Yulife** [comment]
@joshie is that true?

**Comment by jaredlll08** [comment]
@joshe We are still waiting for a reply...

**Comment by jaredlll08** [comment]
oops @joshiejack

**Comment by joshiejack** [comment]
no, but ya know, ya could look at the code, like I had to...

**Comment by joshiejack** [comment]
I know these work anyways... The crucible remove is used in regrowth...

**Comment by thephoenixlodge** [comment]
They do work, but like a few other things they aren't fond of a reload

**Comment by joshiejack** [comment]
The issue is removals seem to leave a null value in recipe lists, jared try using iterator instead, and maybe check and remove all null entries.

**Comment by jaredlll08** [comment]
... @Yulife It would be good if your crucible script tried to remove an ACTUAL recipe!
Anyway this has been fixed in an earlier commit.
