### ISSUE TITLE
[Request] Localization for Entity Page

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#54]
Right now the Entity Page only shows the unlocalized name of the Entity, which is not very pleasent. It would be nice if we could localize the page and write some text instead of just seeing the unlocalized name.

**Comment by jaredlll08** [comment]
Request denied, it also outputs the "localized name"

**Comment by jaredlll08** [comment]
or atleast a key for which the mob could be identified by

**Comment by Yulife** [comment]
Still, I would love to modify it. Leave it open.

**Comment by jaredlll08** [comment]
How would you modify it!?! This method is used in many mods! Morph for
example, to disable morphs...

**Comment by Yulife** [comment]
This was for SoundLogic, mainly. Do some black magic, then!

**Comment by jaredlll08** [comment]
not possible

**Comment by Yulife** [comment]
This issue still hasn't been resolved - is this even possible @Vazkii? For some reason all pages can be localized except the Entity page which will always display the entity name at the bottom.
