### ISSUE TITLE
[Bug] Ex Nihilo's Crucible Heat Source disfunctions on block-block update next to the heat source

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#55]
When I use [this](http://puu.sh/fkBKb/3683dd4aa8.txt) script I sucessfully remove lava from heating my Crucible. However, when the lava gets any kind of ... block update (?) it resumes to smelt stuff in the crucible for a **short** period of time.
I am not sure whether this is reproduceable with a block update as it is really strange behaving.. here are a few examples.

**On building:**
![2015-02-01_18 16 16](https://cloud.githubusercontent.com/assets/8559428/5992937/16c338be-aa3f-11e4-902a-db98596447d5.png)

**On removal of a block the lava is next to:**
![2015-02-01_18 16 28](https://cloud.githubusercontent.com/assets/8559428/5992940/1eaec106-aa3f-11e4-85cd-c6e01bf06540.png)

**On placing a barrel next to it:** (rebuilt it)
![2015-02-01_18 21 44](https://cloud.githubusercontent.com/assets/8559428/5992943/38bf8e0e-aa3f-11e4-85cb-9ce0dfabf79b.png)

**On putting something in the barrel:** (causes a block update)
![2015-02-01_18 22 11](https://cloud.githubusercontent.com/assets/8559428/5992945/42dc771c-aa3f-11e4-99f3-f9714eccf899.png)

This is rather weird because it only reacts to a block actually being broken next to it.

Or... **is it the switch from lava going from still to flow?**

**Comment by jaredlll08** [comment]
Im suspecting it is because lava has 2 states, Flowing and Still, Blacklist both and get back to me.

**Comment by Yulife** [comment]
Tried that. Though, I am unsure if I did it right. What are the unlocalized fluid names for each?

**Comment by jaredlll08** [comment]
not sure...

**Comment by jaredlll08** [comment]
If it reacts to a block update, (not changing the lava to flowing) then it must be on exnihilo side.

**Comment by jaredlll08** [comment]
This is exnihilo side, I am unsure what is causing this... as all I am doing is removing the block from the registry...

**Comment by MikeLydeamore** [comment]
Can you try this with the latest version from http://minecraft.curseforge.com/mc-mods/221696-ex-nihilo/files ?
I'm thinking it may be a server/client desync issue which has been changed in this version.

**Comment by Yulife** [comment]
Will do, thank you.

**Comment by Yulife** [comment]
http://gyazo.com/3d7c4b95f67ac62605ab1ac157afc4df 
Nope ;(

**Comment by MikeLydeamore** [comment]
OK, I believe I have fixed this in an upcoming ExN version. Note that this will need some backend change to ModTweaker though.
There is now a built-in method for removing ("unregister") which can be used.

For what it's worth, I believe the original issue is because meta's 0-15 were registered. Removing all of them solved the problem.

**Comment by jaredlll08** [comment]
From what I can see, this issue was resolved and it was not modtweaker side anyway.
