### ISSUE TITLE
[Bug] Ex Nihilo Hammer Recipe Removal still applies to Harvest Speed

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#56]
With [this](http://puu.sh/fkDK1/04162ace11.txt) script you are able to remove sand from being broken down to dust by a hammer - which works. However, it is still treated as a hammer-able material if you try to break it as it is very fast.

**Comment by jaredlll08** [comment]
There is no way to remove blocks form the hammer block list

**Comment by Yulife** [comment]
[orly](https://github.com/jaredlll08/ModTweaker2/blob/master/src/main/java/modtweaker/mods/exnihilo/handlers/Hammer.java#L45)

**Comment by jaredlll08** [comment]
[That removes the rewards you moron!](https://github.com/jaredlll08/ModTweaker2/blob/master/src/main/java/modtweaker/mods/exnihilo/handlers/Hammer.java#L66)

**Comment by Yulife** [comment]
Then make it remove harvest speed you moron! >:D

**Comment by Yulife** [comment]
Fixed \o/ Don't close issues so easily, Jared!
