### ISSUE TITLE
[Request] Swap Output & Chance sets in the Slag Furnace Handler

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#57]
This is only a visual issue but the Output1 and Chance1 render on the bottom part of the Output slots on the Slag Furnace. It would be more appealing if they were swapped, thus making Output1 and Chance1 on the upper part. Vice versa with Output2 and Chance2. 
https://github.com/jaredlll08/ModTweaker2/blob/master/src/main/java/modtweaker/mods/factorization/handlers/SlagFurnace.java#L19

**Comment by jaredlll08** [comment]
I do not understand what you are asking

**Comment by Yulife** [comment]
**Turn**
public static void addRecipe(IItemStack input, IItemStack output1, double chance1, IItemStack output2, double chance2) {

**into**
public static void addRecipe(IItemStack input, IItemStack output2, double chance2, IItemStack output1, double chance1) {

**Comment by jaredlll08** [comment]
will commit later
