### ISSUE TITLE
Removing Alloys causes script error during /mt reload

### ISSUE THREAD

**Issue by UndeadZeratul** [jaredlll08/ModTweaker2#58]
I mentioned this in https://github.com/jaredlll08/ModTweaker2/issues/17#issuecomment-70767121, but when I try to remove an alloy recipe, it both doesn't remove the original recipe, as well as after doing a /mt reload, throws a null pointer exception.  Just as bad, after I do a /mt reload, the new recipe doesn't even show up because the script breaks.

**Comment by Yulife** [comment]
Did you try a jenkins build?

**Comment by UndeadZeratul** [comment]
We actually pulled down the latest from GitHub and built it manually since we don't have access to the jenkins.  The build was from about a day or so ago.

**Comment by Yulife** [comment]
@jaredlll08 you never made a commit anywhere, **how** is it **fixed**?

**Comment by jaredlll08** [comment]
I thought I fixed it. I am suspecting it is a problem with the script HOWEVER I did insert a check to make sure that the liquid being removed actually exists

**Comment by jaredlll08** [comment]
and I cant always commit!

**Comment by UndeadZeratul** [comment]
The original issue of the removeMelting() method call sends to be working fine now, but now I'm having an issue on the removeAlloy() method call; if that clarifies anything.

**Comment by froghouse** [comment]
I and a friend are having the same problem. Java reports an error with the .zs-file followed by a stack trace from a null pointer exception. We are also trying to remove an alloy from TConstruct using the line:
`mods.tconstruct.Smeltery.removeAlloy(<liquid:angmallen.molten>);`
The error occurs when we run `/mt reload`. The main difference is that we're not trying to add the alloy back. But I thought I'd report it here since we're also failing at removing an alloy. We're using version 2.0.6, latest release.

**Comment by Yulife** [comment]
@froghouse could you test it with the latest version?

**Comment by UndeadZeratul** [comment]
So the new version doesn't throw the error anymore, but it's also not removing the alloys correctly. The initial load still shows the old and new recipes, but when I do a /mt reload, it doesn't error, but then only has the original alloy recipe, rather than the new one.

**Comment by Yulife** [comment]
@jaredlll08 shall look into it.

**Comment by Yulife** [comment]
Undead, remind me today to test it in the rewritten version xD

**Comment by UndeadZeratul** [comment]
Oh, has it been possibly fixed?  Sure, you can go ahead and test it if you'd like, otherwise if I have some free time I'll see what I can find.

**Comment by Yulife** [comment]
In the rewritten version it doesn't throw a null pointer anymore, however, it does nothing. With the script from the wiki I cannot remove Manyullin's alloy recipe. @jaredlll08 !

**Comment by UndeadZeratul** [comment]
That's what I recall happening when I took a look a few weeks ago.

**Comment by jaredlll08** [comment]
The problem was, you had to use the EXACT fluid amount, for example:
mods.tconstruct.Smeltery.removeAlloy(<liquid:manyullyn.molten>*16);

**Comment by jaredlll08** [comment]
I have fixed this now :)

**Comment by UndeadZeratul** [comment]
Yeah, I saw Joshie's comment on the other thread.  Once I get the chance, I'll pull down the latest and run some tests.
