### ISSUE TITLE
Document BetterStorage

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#59]

**Comment by Yulife** [comment]
https://github.com/copygirl/BetterStorage/releases/tag/v0.12.0.124

**Comment by Nentify** [comment]
Shouldn't this be on either MineTweaker's documentation or copygirl's documentation, seeing as it's support for the actual mod.

**Comment by Yulife** [comment]
I did the same with Tinkers' Steelworks. Put it [here](http://puu.sh/fysmB/7b39ae597d.png) because it isn't part of Modtweaker. I am posting it here because a reminder would be kind of weird on the Minetweaker repo <-< lol
