### ISSUE TITLE
[Suggestion] Adding AE2 Inscriber Support

### ISSUE THREAD

**Issue by artdude543** [jaredlll08/ModTweaker2#60]
Would it be possible to have support for adding recipes to the Inscriber?

**Comment by jaredlll08** [comment]
Is it only the Inscriber? if so, I just did it...

**Comment by Yulife** [comment]
You forgot the Grinding Stone ;)

**Comment by jaredlll08** [comment]
According to the AE devs the grindstone is protected... So I cant edit
recipes, sorry

**Comment by Yulife** [comment]
Aight.
