### ISSUE TITLE
[Bug] mods.tconstruct.Tweaks.setRFCapacity not working

### ISSUE THREAD

**Issue by Nentify** [jaredlll08/ModTweaker2#61]
Using the example from the wiki page doesn't seem to work, nor does the example below seem to do anything when applying a hardened flux capacitor to a cleaver.

```
mods.tconstruct.Tweaks.setRFCapacity("cleaver", 1);
```

**Comment by jaredlll08** [comment]
Unfortunately because @joshiejack fails to actually test his code... (#shotsFired) This does not seem to be possible, @joshiejack was setting the backup variable that is not used, basically it was a blank command... So unfortunatly I have removed the feature, sorry to disappoint.

**Comment by joshiejack** [comment]
jared i did test it. it used to work =p

**Comment by Yulife** [comment]
Calling @boni then.

**Comment by joshiejack** [comment]
no i mean its changed close it

**Comment by bonii-xx** [comment]
It did work because the capacitor used wasn't take into account. It does now, therefore that stuff is not possible anymore.
