### ISSUE TITLE
[Suggestion] Thaumcraft: Runic Shielding/Vis discount

### ISSUE THREAD

**Issue by DrStage** [jaredlll08/ModTweaker2#62]
It would be nice to add runic shielding to additional items. Maybe you could add that functionality to modtweaker 0.7!

**Comment by Yulife** [comment]
That would be possible via "IRunic".

**Comment by DrStage** [comment]
Thank you!
If there's an API for vis discount, please add that too!

**Comment by jaredlll08** [comment]
Since yulife seems to know sooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo much about the Thaumcraft API, i'll let him do it!

**Comment by Yulife** [comment]
No, @BluSunrize told me! Hah!

**Comment by Yulife** [comment]
Sorry, it is not possible. Due to Jared being lazy and it being an interface, nothing can be done about it :(

**Comment by jaredlll08** [comment]
IRunic is an interface, you have to implement IRunic in the actual class, that is why it is not possible

**Comment by hron84** [comment]
@jaredlll08 which interface adds the vis discount btw?

**Comment by BluSunrize** [comment]
@hron84 it's called "IRunicArmor"

Once again though, not implementable unless you wanna ASM it in. Wouldn't recommend that. Tends to blow up.

**Comment by jaredlll08** [comment]
I will not allow ASM into modtweaker at this stage. It can lead to very weird crash reports and can break compatability with newer forge versions or even newer mod versions

**Comment by BluSunrize** [comment]
ASM is always the last option to /anything/. It's unavoidable for a few situations, but even in those: Small doses and only modification of output values. Never replace an entire class or method, because anyone else who might have wanted to hook or modify there will clash.

**Comment by hron84** [comment]
@BluSunrize Is it not a part of the Thaumcraft API? As I see [IRunicArmor](https://github.com/Azanor/thaumcraft-api/blob/master/IRunicArmor.java) and [IVisDiscountGear](https://github.com/Azanor/thaumcraft-api/blob/master/IVisDiscountGear.java) is a part of the TC4 API. Also Botania can migrate Runic Shielding properties from the Revealing stuff because it is stored as an NBT data.

**Comment by jaredlll08** [comment]
Wow @hron84 that is like saying, "USB type C is part of the USB family! so it WILL work with USB Type B", hint, it will not. If you knew how to create a mod, then yes, you could create a CUSTOM item (as in the item is something that is added by your mod), then you would not need ASM. But using modtweaker, we cannot change a whole class structure especially at runtime.

**Comment by hron84** [comment]
@jaredlll08 my question was totally out of scope for MT. I just asked here because I _do_ plan to make a small mod around TC, but I could not figure out which class/interface I need for Vis discount. I examined Botania source, but it does not add vis discount for mana/terrasteel helmet of revealing.

**Comment by jaredlll08** [comment]
@hron84 Few things...
1) Specify that.
2) This is the MT github, we are not even expected to answer your question as it has nothing to do with MT
3) Keep your questions to the mod specific github / irc channel (#Thaumcraft)
4) It is simple:
```
public class ItemRep extends Item implements IVisDiscountGear
```

that is it.

**Comment by hron84** [comment]
Thanks.

**Comment by Yulife** [comment]
Jared don't be so grumpy, that guy can ASK :P

**Comment by jaredlll08** [comment]
Without giving any context it is annoying though, both Blu And I thought he
was talking about MT
