### ISSUE TITLE
Mekanism Enrichment Chamber's "input" (to remove recepies) is actually set to the output and doesn't work properly

### ISSUE THREAD

**Issue by simlhawk** [jaredlll08/ModTweaker2#66]
In the ModTweaker(1) wiki it says that to remove an enrichment chamber recipe, you need to provide the input materials. That is wrong, with both ModTweaker(1) and this ModTweaker2 src (I built a .jar).

What does work is to provide the output. The only issue with this is that if there are more than one recipe that creates the same output (ie Copper Ingot & Copper Ore), it will only remove one of them, instead of them all. In an attempt to get rid of them all, I got the command to run twice, but running the same command twice just breaks the recipes.

This is true of both ModTweaker(1) and ModTweaker2 (just built it this morning).

**Comment by Bunsan** [comment]
The issue of a script only removing one of the recipes producing  the indicated output is an issue for the crusher as well. The recipe for string is a wool of any colour produces 4 string. the script mods.mekanism.Crusher.removeRecipe(<minecraft:string>); only removes one of the 16 recipes. I've been able to remove all recipes by repeating command 16 times. I've not attempted to use a loop to clean up my script yet.

**Comment by Bunsan** [comment]
I believe in general that the Mekanism Remove recipe is not functioning as intended. It functions as expected when you remove one or two recipes with only one way to produce the output entered in script. After 3 recipes (or if output has 3 or more possible inputs to produce it) are removed from a machine all recipes are removed.

**Comment by simlhawk** [comment]
Still breaks the recipes. Luckily, I can use this behavior and re-add everything myself. That is, however, over 50 pages and will be very tedious.

**Comment by jaredlll08** [comment]
Ok I changed it to remove all recipes, and it is meant to work on the output, not the input, that must be a wiki mistake.
