### ISSUE TITLE
Omg Forestry!

### ISSUE THREAD

**Issue by Voidi** [jaredlll08/ModTweaker2#7]
I should have better monitoring the forum thread, didn't know the maintainer has changed.
Are you working on extending the forestry functions?
Because I am already working at it.

PS: It would have been better, you had forking the old ModTweaker Repo.

**Comment by jaredlll08** [comment]
I have already finished Forestry, May I ask what you mean by "extending the forestry functions?"?

**Comment by Voidi** [comment]
For the crafting Machines there is missing: Centrifuge, Thermic Fabricator and maybe crating.

**Comment by jaredlll08** [comment]
ok Centrifuge is not currently possible within minetweaker, I talked to the Minetweaker dev and he agreed with me, forestry's recipes are VERY wierd, Fabricator Ill look at, and crating?

**Comment by Voidi** [comment]
Adding Centrifuge recipes is possible. Since i have this always written, i check if its match the recently update and make pull request soon.
(Oh und it seems you don't have implemented the undo functions isn't?)

**Comment by jaredlll08** [comment]
BaseAdditionList / BaseRemovalList should implement the undo function

**Comment by Voidi** [comment]
Sorry my fault!

**Comment by Voidi** [comment]
add Support for fabricator and Dentrifuge, see my pull request
later on i look at the Crating support.

By the way: you removed the Bee methods. didn't they work as expected?

**Comment by Yulife** [comment]
@Voidi Thanks for the work.
