### ISSUE TITLE
[Feature Request] Remove All function

### ISSUE THREAD

**Issue by InfinityRaider** [jaredlll08/ModTweaker2#71]
Say I want to disable a certain recipe handler, or overhaul it completely, having a for example mods.ThermalExpanion.Smelter.removeAll() function would be very useful.
And yes I'm requesting this for everything there is support for at the moment.

(btw if you're too busy I can start this myself and make some pull requests)

**Comment by quentinrossetti** [comment]
That would be very nice indeed !

**Comment by Lanse505** [comment]
Or in General a mods.removeAll() Feature so you could remove all crafting recipes for a certain item from all supported mods would be great.

Also maybe check into adding oredictionary support for Removals, Its a bitch making 10 lines of removal code cause there are 10 different versions of copper ingots from several mods >.>

**Comment by jaredlll08** [comment]
Implemented in ModTweaker2 the rewrite
