### ISSUE TITLE
Alloy removing not working

### ISSUE THREAD

**Issue by Mrbysco** [jaredlll08/ModTweaker2#73]
Im trying to change the tinkers' construct alloying recipes.
The adding is working properly. but the removing part is doing nothing.

Im using:
mods.tconstruct.Smeltery.removeAlloy(<liquid:alumite.molten>);
mods.tconstruct.Smeltery.addAlloy(<liquid:alumite.molten> * 48, [<liquid:blood> * 80, <liquid:iron.molten> * 32, <liquid:obsidian.molten> * 32]);

But ingame:
![Nei recipe search](http://i.imgur.com/HFzqAwK.png)
It isnt being removed. its still usable:
![Still working](http://i.imgur.com/QZKsCzY.png)

**Comment by UndeadZeratul** [comment]
Related to #17 and #58.

**Comment by joshiejack** [comment]
Removals require you to specify the fluid amount currently. It was a side effect of me using isFluidStackIdentical rather than checking if the fluid was identical :P 

Jared is free to change that of course.

**Comment by Mrbysco** [comment]
*hugs @joshiejack* Thanks... Issue closed

**Comment by Yulife** [comment]
Jared needs to fix it first. Then close it with a commit :P

**Comment by jaredlll08** [comment]
I dont see an issue here...
