### ISSUE TITLE
[bug] Thermal Expansion Machine Recipe Removals

### ISSUE THREAD

**Issue by Fiirah** [jaredlll08/ModTweaker2#74]
Something seems to have changed in the latest thermal expansion release with regards to how ore processing recipes are added that is incompatible with remove functions.

I think they now automatically add smelting recipes for ores based on oredict tag after other recipes are registered.

I don't really know much about this but i suspect this is on their end to fix, i'll make an issue on their tracker if someone can confirm this isn't a modtweaker bug.

somehow this also affects the /mt reload command causing it to throw an error with the below script.

Versions:
MineTweaker3-1.7.10-3.0.9C
ModTweaker2-1.7.X-0.7.1

CoFHCore-[1.7.10]3.0.0RC2-195
CoFHLib-[1.7.10]1.0.0B9-118
ThermalDynamics-[1.7.10]1.0.0RC2-77
ThermalExpansion-[1.7.10]4.0.0RC2-129
ThermalFoundation-[1.7.10]1.0.0RC3-56

Script:
https://gist.github.com/45e34d84657142bd0e75.git

**Comment by jaredlll08** [comment]
Is there a crash log?

**Comment by Fiirah** [comment]
It crashed but this doesn't seem to happen every time, mostly just the recipes are still there.

Minetweaker Log of recipes being removed
https://gist.github.com/89c9cc347775b3e16265.git

A crash report, happened when trying to check the recipes in NEI
https://gist.github.com/953f90845f7b24c0aae3.git

**Comment by jaredlll08** [comment]
Can you test if the recipes work? (without looking in NEI) I have a feeling that nei is cacheing their recipes...

**Comment by wujekbrezniew** [comment]
I have the same problem and yes... the Redstone Furnace recipe works.

**Comment by jaredlll08** [comment]
There is a config option in the TE config, something like "unlock recipes" this may fix the errors.

**Comment by Timeslice42** [comment]
Set the config for the machine to AllowRecipeOverwrite=true, removed the recipe, restarted minecraft, and then tested the recipe. NEI still shows the recipe and the recipe still works. No errors show up in the minetweaker logfile.

**Comment by Timeslice42** [comment]
This is still broken (for adding and removing recipes, even when "AllowRecipeOverrides" is set to true. Has anyone looked into this yet?
