### ISSUE TITLE
[Suggestion] GT  5/6 Support

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#75]
is it possible to update Gt handlers  to Version 5 /6 and add Fluid support because many Machines are missing/not supported. I add this suggestion to Minetweaker 3 too .

https://github.com/stanhebben/MineTweaker3/issues/156

**Comment by Dream-Master** [comment]
Close the issue mean you add support to Gt or it is a Mintweaker thing and Stan have to do it?
A very short answer would be nice.
Thanks

**Comment by Yulife** [comment]
Stan has already added support.

**Comment by Dream-Master** [comment]
Mean have to wait for Version 3.1?

**Comment by Dream-Master** [comment]
In Version 3.09c I didn't see support for new gt5 machines and fluids not supported too.

**Comment by Yulife** [comment]
I have no clue, then. Calling @stanhebben
