### ISSUE TITLE
EnderIO support please - Sag Mill - Alloy Smelter

### ISSUE THREAD

**Issue by crunkazcanbe** [jaredlll08/ModTweaker2#78]
Title says it all. :)

Thank you 

-Crunk

**Comment by Yulife** [comment]
Check out the xml files in EnderIO's configs folder. Support is planned but not any time soon.

**Comment by jaredlll08** [comment]
Modtweaker is now officialy maintenance mode(to fix stuff). also mod has its own recipe implementation
