### ISSUE TITLE
<itemstack>.onlyWithTag() not supported

### ISSUE THREAD

**Issue by InfinityRaider** [jaredlll08/ModTweaker2#79]
It'd be nice to have support for stacks with certain NBT tags. I've tested Thaumcraft & Blood magic and neither work.

**Comment by jaredlll08** [comment]
This would be more a minetweaker related feature

**Comment by joshiejack** [comment]
Actually it's more the mods themselves having to support checking nbt.

**Comment by InfinityRaider** [comment]
Well Thaumcraft should have NBT support because the mana beans/essence use NBT IIRC, I could be wrong though
