### ISSUE TITLE
[Rubberized Tubes Question] Can't remove

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#82]
I try to remove all Electron Tubes out of the Thermionic Fabricator and it work for all Tubes except Rubberized Tubes i cant remove. 

Posted this Issue on Forestry Git all ready:

https://github.com/ForestryMC/ForestryMC/issues/544

My Mod Tweaker Code
``````````````````````````````````````````````````````
// --- Rubberrised Electron Tubes
mods.forestry.ThermionicFabricator.removeCasts(<Forestry:thermionicTubes:8>);
```````````````````````````````````````````````````````````````
Did I something wrong? I need help with this. And btw i  try to make a small Pack only with GT,IC2,Forestry and Mine/Modtweaker with fresh configs and i didnt work too. Could need help with this Problem. Thanks in advance.

**Comment by jaredlll08** [comment]
learn to read errors,

**Comment by Yulife** [comment]
Les dir das nochmal ganz genau durch was der geschrieben hat.

**Comment by GregoriusT** [comment]
If that Guy happened to have mention that Error on the GT Thread, he
would have received a ban for not reading the Q/A and also not reading
the Error Message itself, but still daring to post that thing.

But I don't know how you handle stupidity here over at your GitHub, so
I will leave it to you guys.

Am 06.03.15 schrieb Yulife <notifications@github.com>:

**Comment by jaredlll08** [comment]
@GregoriusT you handle it anyway you want :), (preferably mean because I
can't be mean :(, reputation and stuff :( )

**Comment by GregoriusT** [comment]
There are people who are just "too friendly" or "not mean enough", tehe ;)

2015-03-06 17:25 GMT, Jared <notifications@github.com>:
> @GregoriusT you handle it anyway you want :), (preferably mean because I
> can't be mean :(, reputation and stuff :( )
>

**Comment by jaredlll08** [comment]
I want to be mean, if you got a place where I can send you a picture I got
something to show you

**Comment by GregoriusT** [comment]
Wait a second, why the fuck did the reply go to something else. That
Reply was supposed to go to someone violating the GT-ERR-01 Code,
which is nowhere mentioned here (but in the linked Issue). Now I did
what Azanor accidentially did a few days ago and replied to the wrong
issue...

**Comment by Dream-Master** [comment]
My solution double remove :
````````````````````````````````````````````````````````````````````````````````````````````````
// --- Rubberrised Electron Tubes
mods.forestry.ThermionicFabricator.removeCasts(<Forestry:thermionicTubes:8>);
mods.forestry.ThermionicFabricator.removeCasts(<Forestry:thermionicTubes:8>);
``````````````````````````````````````````````````````````````````````````````````````````

Thanks Guys for your time. (And nice to know that i am the only one using Modtweaker really.)

**Comment by Yulife** [comment]
**Don't be a jerk, guys. Hateful comments got removed, Github is for reporting issues.**
Though, @Dream-Master please next time read more carefully.

**Comment by Dream-Master** [comment]
It has nothing to do with GT-ERR-01. There are two recipes maybe because the two different rubber types. I delete the recipes twice and for me the problem is solved.

**Comment by UndeadZeratul** [comment]
Correction: you're the only one using ModTweaker for Forestry :)

**Comment by Dream-Master** [comment]
;-)

**Comment by mezz** [comment]
Glad you found a workaround @Dream-Master.
I think it should only take one call to remove all recipes, anything else is confusing.

**Comment by Dream-Master** [comment]
Yes I know but it is the only way to remove this special recipe. May Java knowledge isn't really big to go deeper inside.
