### ISSUE TITLE
[Question!] Botania mana infusion crafting

### ISSUE THREAD

**Issue by dylanpiera** [jaredlll08/ModTweaker2#83]
Is it possible to remove the need of a living rock, Or change the living rock to complete the crafting?

**Comment by Yulife** [comment]
Before you ask such questions, look through the [documentation](http://minetweaker3.powerofbytes.com/wiki/ModTweaker). 
It would be [like this](http://puu.sh/gqkhF/14b75fe8c6.txt).

**Comment by joshiejack** [comment]
That wasnt their question, the answer is no btw

**Comment by dylanpiera** [comment]
ty

**Comment by Yulife** [comment]
Oh ffs, I can't read.
