### ISSUE TITLE
Crash w/ThermalExpansion + 0.7.4

### ISSUE THREAD

**Issue by mmelvin0** [jaredlll08/ModTweaker2#85]
Just tried 0.7.4 and if I join a server then join a single player world, or simply join a singe player world twice, I get this crash. It doesn't happen with 0.7.1.

Crash log: https://gist.github.com/mmelvin0/f35a1a3b58d40ece696d

Steps to reproduce: join a single player world twice in one session.

**Comment by mmelvin0** [comment]
For reference, here is my MineTweaker script: https://gist.github.com/mmelvin0/f62e6a031bb293317e52

**Comment by jaredlll08** [comment]
I honestly have no idea... this is more a CoFH issue...
