### ISSUE TITLE
Bug when adding Induction Smelter recipes

### ISSUE THREAD

**Issue by c0nnex** [jaredlll08/ModTweaker2#86]
Consider following script:
'''
import mods.thermalexpansion.Smelter;
var certusQuartz = <appliedenergistics2:item.ItemMultiMaterial>;
var boneMeal = <minecraft:dye:15>;
var fusedQuartz  = <EnderIO:blockFusedQuartz>;
Smelter.addRecipe(1000, certusQuartz*4 , boneMeal*4 , fusedQuartz, null, 0);

Which should craft a Fused Quart from 4 Bonemeal and 4 certus quartz crystals.
Scrip loads fine, and NEI show the correct recipe.
However I can put the bone meal and the quartz only into the right input slot into the induction smelter :(
It will not accept any of it in the left input slot.

MineTweaker3 - MineTweaker 3 - 3.0.9B ( MineTweaker3-1.7.10-3.0.9C.jar )
modtweaker2 - Mod Tweaker 2 - 0.7 ( ModTweaker2-1.7.X-0.7.1.jar ) ( 0.7.3 will not work on my server)

**Comment by UndeadZeratul** [comment]
What version of Thermal Expansion are you using?  The newest version has the ability to lock the left slot, so it may be locked without you knowing.

**Comment by c0nnex** [comment]
ThermalExpansion - Thermal Expansion - 1.7.10R4.0.0RC6

**Comment by c0nnex** [comment]
Ah ok that was it ... the "Unlock/Lock" Button is invisible in my ressourcepack!
Thanks for the hint!
