### ISSUE TITLE
Cannot connect to multiplayer server

### ISSUE THREAD

**Issue by zlepper** [jaredlll08/ModTweaker2#93]
It seems the client gets disconnected  everytime i try to join my multiplayer server.
There following error happens on the client: http://paste.ubuntu.com/10599022/
If you want to the full log, please do tell, since it's quite large and not really handy.
I'm using modtweaker version 0.7.4 from curseforge.

**Comment by Dream-Master** [comment]
There is a updated Version available (2-0.7.5)

http://minecraft.curseforge.com/mc-mods/220954-modtweaker
